Repository JoinColony/colonyDapp, pull requests merged in 2019-09, with the labels that each got.

#1789 Firesale fixes for production
  src/modules/dashboard/components/TaskFeed/TaskFeedEvent.tsx
  src/modules/users/components/Inbox/InboxContainer/InboxContainer.css
  src/modules/users/components/Inbox/InboxContainer/InboxContainer.tsx
  src/modules/users/components/Inbox/InboxItem/InboxItem.css
  src/modules/users/components/Inbox/InboxItem/InboxItem.tsx
Labels: under-review

#1793 Fix Mainnet Task Skills Minor Spelling Error
  src/modules/dashboard/components/TaskSkills/taskSkillsTree.mainnet.ts
Labels: under-review

#1797 Fix description field (for good this time?)
  src/modules/core/components/Fields/InlineEdit/MultiLineEdit/MultiLineEdit.tsx
  src/modules/dashboard/components/TaskDescription/TaskDescription.tsx
  src/utils/hooks/index.ts
Labels: under-review

#1772 Add UserList to admin Permissions tab
  src/i18n/en.json
  src/modules/admin/components/Permissions/Permissions.css
  src/modules/admin/components/Permissions/Permissions.css.d.ts
  src/modules/admin/components/Permissions/Permissions.tsx
  src/modules/admin/components/Permissions/UserPermissions.css
  src/modules/admin/components/Permissions/UserPermissions.css.d.ts
  src/modules/admin/components/Permissions/UserPermissions.tsx
  src/modules/admin/components/UserList/UserList.tsx
  src/modules/admin/components/UserListItem/UserListItem.css
  src/modules/admin/components/UserListItem/UserListItem.css.d.ts
  src/modules/admin/components/UserListItem/UserListItem.tsx
  src/modules/admin/components/UserListItem/index.ts
  src/modules/admin/constants.ts
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/core/components/Fields/Select/keyTypes.ts
  src/modules/core/components/OmniPicker/withOmniPicker.ts
  src/modules/core/components/Table/Table.tsx
  src/modules/core/components/Table/TableBody/TableBody.tsx
  src/modules/dashboard/components/TaskComments/TaskComments.tsx
  src/modules/dashboard/components/TaskComments/keyTypes.ts
  src/types/index.ts
  src/types/keyTypes.ts
Labels: under-review

#1808 InfoPopover align to spec
  src/modules/admin/components/UserList/UserListItem.css
  src/modules/admin/components/UserList/UserListItem.tsx
  src/modules/core/components/InfoPopover/InfoPopover.css
  src/modules/core/components/InfoPopover/InfoPopover.css.d.ts
  src/modules/core/components/InfoPopover/InfoPopover.tsx
  src/modules/core/components/UserAvatar/UserAvatar.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMeta/ColonyMeta.css
  src/modules/dashboard/components/ColonyHome/ColonyMeta/ColonyMeta.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyMeta/ColonyMeta.tsx
  src/modules/dashboard/components/TaskFeed/TaskFeedComment.css
  src/modules/dashboard/components/TaskFeed/TaskFeedEvent.tsx
  src/modules/users/components/Inbox/InboxItem/InboxItem.css
  src/modules/users/components/Inbox/InboxItem/InboxItem.css.d.ts
  src/modules/users/components/Inbox/InboxItem/InboxItem.tsx
Labels: under-review

#1810 Prevent names with periods (dots) when registering a ENS domain
  src/lib/TextDecorator/schemas.ts
  src/modules/validations.ts
Labels: under-review

#1817 Fix tasks not being shown in ColonyHome
  src/modules/dashboard/components/ColonyHome/ColonyTasks/ColonyTasks.tsx
Labels: P3, bug, under-review

#1826 User Wallet proper component import
  src/modules/dashboard/components/Wallet/index.ts
  src/modules/validations.ts
Labels: under-review

#1771 Cache purser identities
  src/data/PurserIdentityProvider.ts
  src/lib/database/stores/EventStore.ts
Labels: under-review

#1829 Fix colony admin permissions dialog
  src/modules/admin/components/Permissions/ColonyPermissionEditDialog.tsx
  src/modules/admin/components/Permissions/Permissions.tsx
Labels: bug, under-review

#1827 Automatically build and push dapp images on successful builds
  .circleci/config.yml
  scripts/authGoogle.sh
Labels: maintenance, under-review

#1818 Add colony admin "add domain" hint
  src/modules/admin/components/Organizations/OrganizationAddDomains.tsx
  src/modules/admin/components/Profile/ColonyAvatarUploader.tsx
  src/modules/admin/components/Profile/ProfileEdit.tsx
  src/modules/core/components/AvatarUploader/AvatarUploader.md
  src/modules/core/components/Fields/Input/Input.tsx
  src/modules/core/components/Fields/InputLabel/InputLabel.css
  src/modules/core/components/Fields/InputLabel/InputLabel.css.d.ts
  src/modules/core/components/Fields/InputLabel/InputLabel.md
  src/modules/core/components/Fields/InputLabel/InputLabel.tsx
  src/modules/core/components/Fields/InputLabel/__tests__/InputLabel.test.tsx
  src/modules/dashboard/components/CreateColonyWizard/StepCreateToken.tsx
  src/modules/dashboard/components/TaskRatingDialogs/ManagerRatingDialog.tsx
  src/modules/users/components/ConnectWalletWizard/StepJSONUpload/StepJSONUpload.tsx
Labels: under-review

#1838 Fix Automated CI Docker Image Builds
  .circleci/config.yml
  Dockerfile
Labels: bug

#1837 Add user balance listener
  src/modules/core/sagas/setupUserBalanceListener.ts
  src/modules/core/sagas/setupUserContext.ts
  src/modules/users/actionCreators/user.ts
  src/modules/users/components/GasStation/GasStationContent/GasStationContent.tsx
  src/modules/users/components/GasStation/GasStationContent/index.ts
  src/modules/users/reducers/currentUser/profile.ts
  src/modules/users/sagas/user.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/currentUser.ts
Labels: under-review

#1825 Reset task comment field on success
  src/modules/core/components/Fields/Form/ActionForm.tsx
  src/modules/dashboard/components/TaskComments/TaskComments.tsx
Labels: under-review

#1832 Adjust transaction sorting
  src/modules/core/selectors/__tests__/transactions.test.ts
  src/modules/core/selectors/transactions.ts
Labels: under-review

#1803 Add moveFundsBetweenPots saga
  src/modules/dashboard/data/commands/colony.ts
  src/modules/dashboard/data/commands/domains.ts
  src/modules/dashboard/data/commands/index.ts
  src/modules/dashboard/data/queries/domains.ts
  src/modules/dashboard/data/queries/index.ts
  src/modules/dashboard/sagas/domains.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/domain.ts
Labels: under-review

#1834 Refactor token balances [DLF/P]
  src/immutable/Colony.ts
  src/immutable/ColonyTokenReference.ts
  src/immutable/UserTokenReference.ts
  src/immutable/index.ts
  src/modules/admin/components/Profile/ProfileEdit.tsx
  src/modules/admin/components/Tokens/TokenCard.tsx
  src/modules/admin/components/Tokens/TokenList.tsx
  src/modules/admin/components/Tokens/Tokens.tsx
  src/modules/admin/constants.ts
  src/modules/admin/sagas/index.ts
  src/modules/core/checks.ts
  src/modules/core/components/Assignment/Assignment.tsx
  src/modules/core/components/ItemsList/ItemsList.css
  src/modules/core/components/ItemsList/ItemsList.tsx
  src/modules/core/components/ItemsList/index.ts
  src/modules/core/components/PayoutsList/PayoutsList.tsx
  src/modules/core/components/TokenEditDialog/TokenCheckbox.tsx
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/core/components/TokenIcon/TokenIcon.tsx
  src/modules/dashboard/actionCreators/colony.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyHome/TabContribute/TabContribute.tsx
  src/modules/dashboard/components/TaskDomains/TaskDomains.tsx
  src/modules/dashboard/components/TaskEditDialog/TaskEditDialog.tsx
  src/modules/dashboard/components/TaskEditDialog/WrappedPayout.tsx
  src/modules/dashboard/components/Wallet/UserTokenEditDialog.tsx
  src/modules/dashboard/components/Wallet/Wallet.tsx
  src/modules/dashboard/constants.ts
  src/modules/dashboard/data/queries/colonies.ts
  src/modules/dashboard/hooks/useColonyNativeToken.ts
  src/modules/dashboard/hooks/useColonyTokens.ts
  src/modules/dashboard/reducers/coloniesReducer.ts
  src/modules/dashboard/sagas/colony.ts
  src/modules/dashboard/selectors/colony.ts
  src/modules/dashboard/selectors/tasks.ts
  src/modules/dashboard/selectors/tokens.ts
  src/modules/users/reducers/currentUserReducer/tokens.ts
  src/modules/users/state/CurrentUser.ts
  src/modules/validations.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colony.ts
  src/redux/types/actions/user.ts
  src/utils/arrays/index.ts
  src/utils/tokens/index.ts
Labels: under-review

#1856 Add Inbox Empty State
  src/modules/users/components/Inbox/InboxContainer/InboxContainer.css
  src/modules/users/components/Inbox/InboxContainer/InboxContainer.css.d.ts
  src/modules/users/components/Inbox/InboxContainer/InboxContainer.tsx
  src/modules/users/components/Inbox/InboxContent/InboxContent.tsx
Labels: under-review

#1863 Initialize FetchableData with no arguments
  src/immutable/state/index.ts
  src/modules/core/state/index.ts
  src/modules/dashboard/state/index.ts
  src/modules/users/state/CurrentUser.ts
  src/modules/users/state/index.ts
Labels: under-review

#1865 Update T&C file link
  src/modules/users/components/ConnectWalletWizard/StepStart/StepStart.tsx
Labels: maintenance, needs-code-review

#1864 Re-Add Inbox Notification Dot Functionality
  src/modules/users/components/Inbox/InboxIcon/InboxIcon.css
  src/modules/users/components/Inbox/InboxIcon/InboxIcon.css.d.ts
  src/modules/users/components/Inbox/InboxIcon/InboxIcon.tsx
Labels: under-review

#1866 Prefer group id in getGroupId
  src/modules/users/components/GasStation/transactionGroup.ts
Labels: under-review

#1870 Permissions Edit Dialog Render Avatar
  src/modules/admin/components/Permissions/ColonyPermissionEditDialog.tsx
Labels: under-review

#1871 Make SingleUserPicker fill available width
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css
Labels: under-review

#1874 Transaction List long values wrapping cell
  src/modules/core/components/TransactionList/TransactionListItem.css
Labels: under-review

#1858 Add move tokens dialog
  src/dialogComponents.ts
  src/i18n/en.json
  src/modules/admin/checks.ts
  src/modules/admin/components/Tokens/Tokens.tsx
  src/modules/admin/components/Tokens/TokensMoveDialog.tsx
  src/modules/admin/components/Tokens/TokensMoveDialogForm.css
  src/modules/admin/components/Tokens/TokensMoveDialogForm.css.d.ts
  src/modules/admin/components/Tokens/TokensMoveDialogForm.tsx
  src/modules/admin/components/Tokens/index.ts
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/dashboard/reducers/coloniesReducer.ts
  src/modules/dashboard/sagas/domains.ts
Labels: under-review

#1873 Hide ARCHITECTURE_SUBDOMAIN, allow setting of RECOVERY
  src/i18n/en.json
  src/modules/admin/components/Permissions/ColonyPermissionEditDialog.tsx
  src/modules/admin/components/Permissions/UserPermissions.tsx
  src/modules/dashboard/sagas/roles.ts
Labels: under-review

#1876 Fix edit tokens submit
  src/modules/admin/sagas/index.ts
Labels: bug, under-review

#1823 Update home screen
  src/modules/core/components/BreadCrumb/BreadCrumb.css
  src/modules/core/components/BreadCrumb/BreadCrumb.css.d.ts
  src/modules/core/components/BreadCrumb/BreadCrumb.md
  src/modules/core/components/BreadCrumb/BreadCrumb.tsx
  src/modules/core/components/BreadCrumb/index.ts
  src/modules/core/components/Button/Button.css
  src/modules/core/components/ExpandedParagraph/ExpandedParagraph.css
  src/modules/core/components/ExpandedParagraph/ExpandedParagraph.css.d.ts
  src/modules/core/components/ExpandedParagraph/ExpandedParagraph.md
  src/modules/core/components/ExpandedParagraph/ExpandedParagraph.tsx
  src/modules/core/components/ExpandedParagraph/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyDomains/ColonyDomains.css
  src/modules/dashboard/components/ColonyHome/ColonyDomains/ColonyDomains.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyDomains/ColonyDomains.tsx
  src/modules/dashboard/components/ColonyHome/ColonyDomains/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.css
  src/modules/dashboard/components/ColonyHome/ColonyHome.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMeta/ColonyMeta.css
  src/modules/dashboard/components/ColonyHome/ColonyMeta/ColonyMeta.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyMeta/ColonyMeta.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMeta/ColonySubscribe.css
  src/modules/dashboard/components/ColonyHome/ColonyMeta/ColonySubscribe.tsx
  src/utils/strings/index.ts
  styleguide.config.js
Labels: under-review
