Repository JoinColony/colonyDapp, pull requests merged in 2019-08, with the labels that each got.

#1755 Properly Handle Task Title Removal
  src/immutable/Task.ts
  src/modules/dashboard/components/TaskFeed/TaskFeedEvent.tsx
  src/modules/dashboard/components/TaskList/TaskListItem.css
  src/modules/dashboard/components/TaskList/TaskListItem.css.d.ts
  src/modules/dashboard/components/TaskList/TaskListItem.tsx
Labels: under-review

#1752 Don't show Mint Tokens link for Colonies that brought they're own tokens
  src/modules/dashboard/data/queries/colonies.ts
Labels: under-review

#1759 Claim Username Wizard pick latest Transaction Group
  src/modules/dashboard/components/CreateUserWizard/StepConfirmTransaction.tsx
Labels: under-review

#1726 Hide Colony Recovery for Non-Founders
  src/modules/dashboard/checks.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
Labels: P3, bug, under-review

#1738 Upgrade `eslint-config-colony` to v8
  .circleci/config.yml
  .eslintrc.js
  .nvmrc
  Dockerfile
  package.json
  src/data/accessControllers/AbstractAccessController.ts
  src/data/accessControllers/EthereumWalletAccessController.ts
  src/lib/TextDecorator/TextDecorator.ts
  src/lib/database/DDB.ts
  src/lib/database/stores/Store.ts
  src/modules/core/components/Button/Button.tsx
  src/modules/core/components/EthUsd/EthUsd.tsx
  src/modules/core/components/ItemsList/ItemsList.tsx
  src/modules/core/components/MnemonicDnDSorter/MnemonicDnDSorter.tsx
  src/modules/core/components/OmniPicker/OmniPickerContent.tsx
  src/modules/core/components/Wizard/__tests__/withWizard.test.tsx
  src/modules/core/sagas/utils/getGasPrices.ts
  src/modules/dashboard/checks.ts
  src/modules/dashboard/components/ColonyHome/ColonyDomains/ColonyDomains.tsx
  src/modules/dashboard/components/HookedTokenIcon/HookedTokenIcon.tsx
  src/modules/users/components/ConnectWalletWizard/StepStart/StepStart.tsx
  src/modules/users/components/CreateWalletWizard/StepBackupPhrase.tsx
  src/modules/users/components/CreateWalletWizard/StepCreatePhrase.tsx
  src/styles/shared/layout.css
  src/styles/shared/layout.css.d.ts
  src/utils/arrays/index.ts
  src/utils/external/index.ts
  src/utils/hooks/index.ts
  webpack.config.js
  yarn.lock
Labels: maintenance, under-review

#1758 Create LICENSE
  LICENSE
Labels: under-review

#1757 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: under-review

#1747 Add colonyDomainUserRolesSet saga
  src/i18n/en.json
  src/immutable/state/dashboard/AllRoles.ts
  src/modules/dashboard/reducers/allRoles.ts
  src/modules/dashboard/sagas/roles.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colony.ts
Labels: under-review

#1766 Transactions and Messages items inside the Gas Station now have a unique key
  src/modules/users/components/GasStation/transactionGroup.ts
Labels: under-review

#1765 Disable Remove Button when no Avatar is set
  src/modules/admin/components/Profile/ColonyAvatarUploader.tsx
  src/modules/core/components/AvatarUploader/AvatarUploader.tsx
  src/modules/users/components/UserProfileEdit/UserAvatarUploader.tsx
Labels: under-review

#1714 Cancel colony creation when leaving wizard step
  src/modules/dashboard/components/CreateColonyWizard/StepConfirmTransactions.tsx
  src/modules/dashboard/sagas/colonyCreate.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colony.ts
  src/utils/saga/effects.ts
Labels: under-review

#1767 Repair Docker build file
  .dockerignore
  Dockerfile
Labels: maintenance

#1776 Fix integration tests
  ava.config.js
  integration-testing/DDB.test.ts
  integration-testing/EventStore.test.ts
  integration-testing/IPFS.test.ts
  package.json
  tsconfig.json
  yarn.lock
Labels: maintenance, under-review

#1773 Notification Items Fetch Missing Data
  src/data/normalizers/index.ts
  src/modules/users/data/utils.ts
Labels: under-review

#1775 Fix inbox fetching (and show username registered notification)
  src/data/normalizers/index.ts
  src/modules/dashboard/sagas/colony.ts
  src/modules/dashboard/sagas/colonyCreate.ts
  src/modules/users/actionCreators/user.ts
  src/modules/users/components/Inbox/InboxContent/InboxContent.tsx
  src/modules/users/components/Inbox/InboxIcon/InboxIcon.ts
  src/modules/users/components/Inbox/InboxIcon/InboxIcon.tsx
  src/modules/users/components/Inbox/InboxIcon/index.ts
  src/modules/users/components/Inbox/InboxItem/InboxItem.tsx
  src/modules/users/components/Inbox/events.ts
  src/modules/users/data/queries.ts
  src/modules/users/data/utils.ts
  src/modules/users/fetchers.ts
  src/modules/users/reducers/currentUser/activities.ts
  src/modules/users/reducers/currentUser/notifications.ts
  src/modules/users/sagas/inbox.ts
  src/modules/users/sagas/user.ts
  src/modules/users/selectors/user.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/inboxItems.ts
  src/utils/saga/effects.ts
Labels: under-review

#1778 Properly react on message signing errors
  src/lib/ipfs/IPFSNode.ts
  src/lib/ipfs/ipfsConfig.production.ts
  src/lib/ipfs/ipfsConfig.qa.ts
  src/modules/core/components/Fields/Form/ActionForm.tsx
  src/modules/core/reducers/messages.ts
  src/modules/core/sagas/index.ts
  src/modules/core/sagas/messages.ts
  src/modules/dashboard/components/TaskComments/TaskComments.tsx
  src/modules/dashboard/sagas/task.ts
  src/modules/users/components/ConnectWalletWizard/ConnectWalletWizard.ts
  src/modules/users/components/CreateWalletWizard/CreateWalletWizard.ts
  src/modules/users/components/CreateWalletWizard/CreateWalletWizard.tsx
  src/modules/users/components/GasStation/MessageCardDetails/MessageCardControls.tsx
  src/redux/types/actions/message.ts
  src/utils/saga/effects.ts
Labels: under-review

#1739 Add InboxPopover and extract InboxContainer
  docs/Using_Modules.md
  src/modules/pages/components/NavigationWrapper/UserNavigation.tsx
  src/modules/users/components/Inbox/InboxContainer/InboxContainer.css
  src/modules/users/components/Inbox/InboxContainer/InboxContainer.css.d.ts
  src/modules/users/components/Inbox/InboxContainer/InboxContainer.tsx
  src/modules/users/components/Inbox/InboxContainer/index.ts
  src/modules/users/components/Inbox/InboxContent/InboxContent.css
  src/modules/users/components/Inbox/InboxContent/InboxContent.css.d.ts
  src/modules/users/components/Inbox/InboxContent/index.ts
  src/modules/users/components/Inbox/InboxFullscreen/InboxFullscreen.tsx
  src/modules/users/components/Inbox/InboxFullscreen/index.ts
  src/modules/users/components/Inbox/InboxIcon/InboxIcon.tsx
  src/modules/users/components/Inbox/InboxItem/InboxItem.css
  src/modules/users/components/Inbox/InboxItem/InboxItem.css.d.ts
  src/modules/users/components/Inbox/InboxItem/InboxItem.tsx
  src/modules/users/components/Inbox/InboxPopover/InboxPopover.tsx
  src/modules/users/components/Inbox/InboxPopover/index.ts
  src/modules/users/components/Inbox/index.ts
  src/utils/css/index.ts
Labels: under-review

#1781 Disable hardware wallets (temporarily)
  src/modules/core/components/DecisionHub/DecisionOption.css
  src/modules/core/components/DecisionHub/DecisionOption.css.d.ts
  src/modules/core/components/DecisionHub/DecisionOption.tsx
  src/modules/users/components/ConnectWalletWizard/StepStart/StepStart.tsx
Labels: UI
