Repository JoinColony/colonyDapp, pull requests merged in 2020-12, with the labels that each got.

#2300 Update transfer funds modal styles and add new component
  src/modules/admin/components/Tokens/Tokens.tsx
  src/modules/admin/components/Tokens/TokensMoveDialogForm.css
  src/modules/admin/components/Tokens/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css.d.ts
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
  src/modules/dashboard/components/TransferFundsDialog/index.ts
Labels: feature

#2305 Add IndexModal
  src/modules/core/components/IndexModal/IndexModal.css
  src/modules/core/components/IndexModal/IndexModal.css.d.ts
  src/modules/core/components/IndexModal/IndexModal.tsx
  src/modules/core/components/IndexModal/IndexModalItem.css
  src/modules/core/components/IndexModal/IndexModalItem.css.d.ts
  src/modules/core/components/IndexModal/IndexModalItem.tsx
  src/modules/core/components/IndexModal/index.ts
  src/modules/dashboard/components/ColonyActionsDialog/ColonyActionsDialog.tsx
Labels: feature

#2306 Actions Page
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/index.ts
  src/data/resolvers/transactions.ts
  src/img/naked-mole-404.svg
  src/img/naked-mole.svg
  src/modules/dashboard/components/ActionsPage/ActionsPage.css
  src/modules/dashboard/components/ActionsPage/ActionsPage.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/TransactionHash/Hash.tsx
  src/modules/dashboard/components/ActionsPage/TransactionHash/TransactionHash.css
  src/modules/dashboard/components/ActionsPage/TransactionHash/TransactionHash.css.d.ts
  src/modules/dashboard/components/ActionsPage/TransactionHash/TransactionHash.tsx
  src/modules/dashboard/components/ActionsPage/TransactionHash/index.ts
  src/modules/dashboard/components/ActionsPage/TransactionMeta/TransactionMeta.css
  src/modules/dashboard/components/ActionsPage/TransactionMeta/TransactionMeta.css.d.ts
  src/modules/dashboard/components/ActionsPage/TransactionMeta/TransactionMeta.tsx
  src/modules/dashboard/components/ActionsPage/TransactionMeta/index.ts
  src/modules/dashboard/components/ActionsPage/TransactionStatus/TransactionStatus.css
  src/modules/dashboard/components/ActionsPage/TransactionStatus/TransactionStatus.css.d.ts
  src/modules/dashboard/components/ActionsPage/TransactionStatus/TransactionStatus.tsx
  src/modules/dashboard/components/ActionsPage/TransactionStatus/index.ts
  src/modules/dashboard/components/ActionsPage/index.ts
  src/modules/dashboard/components/ActionsPage/types.ts
  src/modules/dashboard/components/FourOFour/FourOFour.tsx
  src/routes/Routes.tsx
  src/routes/routeConstants.ts
  src/utils/web3/index.ts
Labels: feature

#2294 Add "Funds" page, update mint tokens modal
  src/modules/admin/components/AdminDashboard/AdminDashboard.tsx
  src/modules/admin/components/Tokens/TokenMintDialog.css
  src/modules/admin/components/Tokens/Tokens.css
  src/modules/admin/components/Tokens/Tokens.css.d.ts
  src/modules/admin/components/Tokens/Tokens.tsx
  src/modules/admin/components/Tokens/index.ts
  src/modules/admin/sagas/index.ts
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.css
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.css.d.ts
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/ColonyFunding/index.ts
  src/modules/dashboard/components/ColonyFundingBanner/ColonyFundingBanner.css
  src/modules/dashboard/components/ColonyFundingBanner/ColonyFundingBanner.css.d.ts
  src/modules/dashboard/components/ColonyFundingBanner/ColonyFundingBanner.tsx
  src/modules/dashboard/components/ColonyFundingBanner/index.ts
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.css
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.css.d.ts
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyFundingMenu/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/ColonyHome/ColonyInitialFunding/ColonyInitialFunding.tsx
  src/modules/dashboard/components/ColonyTokenEditDialog/ColonyTokenEditDialog.tsx
  src/modules/dashboard/components/ColonyTokenEditDialog/index.ts
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css.d.ts
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.tsx
  src/modules/dashboard/components/TokenCard/TokenCard.css
  src/modules/dashboard/components/TokenCard/TokenCard.css.d.ts
  src/modules/dashboard/components/TokenCard/TokenCard.tsx
  src/modules/dashboard/components/TokenCard/index.ts
  src/modules/dashboard/components/TokenCardList/TokenCardList.css
  src/modules/dashboard/components/TokenCardList/TokenCardList.css.d.ts
  src/modules/dashboard/components/TokenCardList/TokenCardList.tsx
  src/modules/dashboard/components/TokenCardList/index.ts
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.css
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.css.d.ts
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.tsx
  src/modules/dashboard/components/TokenMintDialog/TokenMintForm.tsx
  src/modules/dashboard/components/TokenMintDialog/index.ts
  src/modules/dashboard/components/Wallet/Wallet.tsx
  src/modules/pages/components/VerticalNavigation/VerticalNavigation.tsx
  src/redux/types/actions/colony.ts
  src/routes/Routes.tsx
  src/routes/routeConstants.ts
Labels: feature

#2308 Add actions page items
  src/modules/admin/components/Permissions/UserPermissions.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPageEvent/ActionsPageEvent.css
  src/modules/dashboard/components/ActionsPage/ActionsPageEvent/ActionsPageEvent.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPageEvent/index.ts
  src/modules/dashboard/components/ActionsPage/ActionsPageFeedItem/ActionsPageFeedItem.css
  src/modules/dashboard/components/ActionsPage/ActionsPageFeedItem/ActionsPageFeedItem.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsPageFeedItem/ActionsPageFeedItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPageFeedItem/index.ts
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/dashboard/components/UserPermissions/UserPermissions.css
  src/modules/dashboard/components/UserPermissions/UserPermissions.css.d.ts
  src/modules/dashboard/components/UserPermissions/UserPermissions.tsx
  src/modules/dashboard/components/UserPermissions/index.ts
Labels: feature

#2301 Update Permission Management Modal
  src/modules/admin/components/Permissions/ColonyPermissionsDialog.css
  src/modules/admin/components/Permissions/ColonyPermissionsDialog.css.d.ts
  src/modules/admin/components/Permissions/ColonyPermissionsEditDialog.tsx
  src/modules/admin/components/Permissions/PermissionCheckbox.css
  src/modules/admin/components/Permissions/PermissionCheckbox.tsx
  src/modules/admin/components/Permissions/PermissionForm.tsx
  src/modules/admin/components/Permissions/index.ts
  src/modules/core/components/Fields/Checkbox/Checkbox.tsx
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/ColonyPermissionsAddDialog/ColonyPermissionsAddDialog.tsx
  src/modules/dashboard/components/ColonyPermissionsAddDialog/index.ts
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementCheckbox.css
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementCheckbox.css.d.ts
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementCheckbox.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.css
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.css.d.ts
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
  src/modules/dashboard/components/PermissionManagementDialog/constants.ts
  src/modules/dashboard/components/PermissionManagementDialog/index.ts
  src/modules/transformers.ts
Labels: feature

#2314 Expenditures Index Modal
  src/img/icons.json
  src/img/icons/emoji-calendar.svg
  src/img/icons/emoji-dollar-stack.svg
  src/img/icons/emoji-superman.svg
  src/img/icons/triangle-warning.svg
  src/modules/core/components/IndexModal/IndexModal.tsx
  src/modules/core/components/IndexModal/IndexModalItem.css
  src/modules/core/components/IndexModal/IndexModalItem.css.d.ts
  src/modules/core/components/IndexModal/IndexModalItem.tsx
  src/modules/dashboard/components/ColonyActionsDialog/ColonyActionsDialog.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/ColonyTokenEditDialog/ColonyTokenEditDialog.tsx
  src/modules/dashboard/components/ExpendituresDialog/ExpendituresDialog.tsx
  src/modules/dashboard/components/ExpendituresDialog/index.ts
  src/types/index.ts
  src/utils/hooks/index.ts
  src/utils/hooks/naiveBranchingDialogWizardHook.ts
Labels: feature

#2312 Add MultisigWidget component
  src/i18n/en.json
  src/modules/core/components/ProgressBar/ProgressBar.css
  src/modules/core/components/ProgressBar/ProgressBar.css.d.ts
  src/modules/core/components/ProgressBar/ProgressBar.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.css
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.tsx
  src/modules/dashboard/components/ActionsPage/MultisigWidget/index.tsx
Labels: feature

#2309 Add Create Payment modal
  src/modules/core/components/Fields/Select/Select.css
  src/modules/core/components/Fields/Textarea/Textarea.css
  src/modules/core/components/Fields/Textarea/Textarea.tsx
  src/modules/core/components/PermissionRequiredInfo/PermissionRequiredInfo.css
  src/modules/core/components/PermissionRequiredInfo/PermissionRequiredInfo.css.d.ts
  src/modules/core/components/PermissionRequiredInfo/PermissionRequiredInfo.tsx
  src/modules/core/components/PermissionRequiredInfo/index.ts
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialog.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.css
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.css.d.ts
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/CreatePaymentDialog/index.ts
Labels: feature

#2311 Add DetailsWidget component
  src/modules/core/components/DetailsWidgetUser/DetailsWidgetUser.css
  src/modules/core/components/DetailsWidgetUser/DetailsWidgetUser.css.d.ts
  src/modules/core/components/DetailsWidgetUser/DetailsWidgetUser.tsx
  src/modules/core/components/DetailsWidgetUser/index.ts
  src/modules/core/components/InvisibleCopyableAddress/InvisibleCopyableAddress.css
  src/modules/core/components/InvisibleCopyableAddress/InvisibleCopyableAddress.css.d.ts
  src/modules/core/components/InvisibleCopyableAddress/InvisibleCopyableAddress.tsx
  src/modules/core/components/InvisibleCopyableAddress/index.ts
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.css
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetTeam/DetailsWidgetTeam.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetTeam/index.ts
  src/modules/dashboard/components/ActionsPage/DetailsWidget/index.ts
  src/modules/dashboard/components/ActionsPage/types.ts
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.tsx
Labels: feature

#2319 Make tooltip copy message customisable
  src/modules/core/components/InvisibleCopyableAddress/InvisibleCopyableAddress.tsx
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.tsx
Labels: feature

#2316 Added input storage widget in action page
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/InputStorageWidget/InputStorageWidget.css
  src/modules/dashboard/components/ActionsPage/InputStorageWidget/InputStorageWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/InputStorageWidget/InputStorageWidget.tsx
  src/modules/dashboard/components/ActionsPage/InputStorageWidget/index.ts
  src/styles/variables.css
Labels: feature

#2317 Add and update Dialog component themes
  src/modules/core/components/Dialog/Dialog.css
  src/modules/core/components/Dialog/DialogSection.css
  src/modules/core/components/Dialog/DialogSection.css.d.ts
  src/modules/core/components/Dialog/DialogSection.tsx
  src/modules/core/components/TokenEditDialog/TokenEditDialog.css
  src/modules/core/components/TokenEditDialog/TokenEditDialog.css.d.ts
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/dashboard/components/ColonyPermissionsAddDialog/ColonyPermissionsAddDialog.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.css
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.css.d.ts
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.css
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.css.d.ts
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.tsx
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.css
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.css.d.ts
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css.d.ts
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: maintenance

#2320 Add Annotations core component
  src/modules/core/components/Fields/Annotations/Annotations.css
  src/modules/core/components/Fields/Annotations/Annotations.css.d.ts
  src/modules/core/components/Fields/Annotations/Annotations.tsx
  src/modules/core/components/Fields/Annotations/index.ts
  src/modules/core/components/Fields/Textarea/index.ts
  src/modules/core/components/Fields/index.ts
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.css
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css.d.ts
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: maintenance

#2321 Refactor MemberInfoPopover and TokenInfoPopover
  src/modules/core/components/InfoPopover/InfoPopover.tsx
  src/modules/core/components/InfoPopover/MemberInfo.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover.tsx
  src/modules/core/components/InfoPopover/NotAvailableMessage.tsx
  src/modules/core/components/InfoPopover/TokenInfo.tsx
  src/modules/core/components/InfoPopover/TokenInfoPopover.tsx
  src/modules/core/components/InfoPopover/UserInfoNotAvailable.tsx
  src/modules/core/components/InfoPopover/UserInfoPopover.tsx
Labels: maintenance

#2318 Add ColorSelect core component
  src/modules/core/components/ColorSelect/ColorSelect.css
  src/modules/core/components/ColorSelect/ColorSelect.css.d.ts
  src/modules/core/components/ColorSelect/ColorSelect.tsx
  src/modules/core/components/ColorSelect/index.tsx
  src/modules/core/components/Fields/Select/Select.css
  src/modules/core/components/Fields/Select/Select.css.d.ts
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/core/components/Fields/Select/SelectListBox.css
  src/modules/core/components/Fields/Select/SelectListBox.css.d.ts
  src/modules/core/components/Fields/Select/types.ts
  src/modules/core/components/Fields/SelectOption/SelectOption.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
Labels: feature

#2324 Fix `TokenInfoPopover` infinite loop render
  src/modules/core/components/InfoPopover/TokenInfoPopover.tsx
Labels: P1, bug

#2322 Refactor TokenIcon component
  package-lock.json
  package.json
  src/modules/constants.ts
  src/modules/dashboard/components/HookedTokenIcon/HookedTokenIcon.tsx
  webpack.base.js
Labels: maintenance

#2330 Remove Transactions and TransactionList components
  src/modules/admin/components/Transactions/Transactions.css
  src/modules/admin/components/Transactions/Transactions.css.d.ts
  src/modules/admin/components/Transactions/Transactions.tsx
  src/modules/admin/components/Transactions/index.ts
  src/modules/core/components/TransactionList/TransactionDetails.css
  src/modules/core/components/TransactionList/TransactionDetails.css.d.ts
  src/modules/core/components/TransactionList/TransactionDetails.tsx
  src/modules/core/components/TransactionList/TransactionList.tsx
  src/modules/core/components/TransactionList/TransactionListItem.css
  src/modules/core/components/TransactionList/TransactionListItem.css.d.ts
  src/modules/core/components/TransactionList/TransactionListItem.tsx
  src/modules/core/components/TransactionList/index.ts
Labels: maintenance

#2329 TokenIcon component updates
  src/modules/dashboard/components/HookedTokenIcon/HookedTokenIcon.tsx
  src/utils/dataReader.ts
Labels: maintenance

#2332 Removed ActivityFeed
  src/immutable/ActivityFeedItem.ts
  src/immutable/Using-Immutable.md
  src/immutable/index.ts
  src/modules/core/components/ActivityFeed/ActivityFeed.css
  src/modules/core/components/ActivityFeed/ActivityFeed.css.d.ts
  src/modules/core/components/ActivityFeed/ActivityFeed.md
  src/modules/core/components/ActivityFeed/ActivityFeed.tsx
  src/modules/core/components/ActivityFeed/ActivityFeedItem.css
  src/modules/core/components/ActivityFeed/ActivityFeedItem.css.d.ts
  src/modules/core/components/ActivityFeed/ActivityFeedItem.tsx
  src/modules/core/components/ActivityFeed/index.ts
  styleguide.config.js
Labels: maintenance

#2331 Rework auth local storage token
  src/api/auth.ts
Labels: maintenance

#2327 Transfer Funds Action Wiring
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colonyActions.ts
  src/i18n/en-actions.ts
  src/i18n/en-events.ts
  src/modules/dashboard/components/ActionsPage/ActionsPage.css
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/InputStorageWidget/InputStorageWidget.tsx
  src/modules/dashboard/components/ActionsPage/index.ts
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.css
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.css.d.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.css
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.css.d.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyHome/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css.d.ts
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
  src/modules/dashboard/sagas/actions.ts
  src/modules/dashboard/sagas/domains.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colonyActions.ts
  src/redux/types/actions/domain.ts
  src/types/colonyActions.ts
  src/utils/events/index.ts
  src/utils/saga/effects.ts
Labels: feature

#2325 Update ColonyTokenEditDialog
  src/data/index.ts
  src/modules/core/components/TokenEditDialog/TokenEditDialog.css
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/core/components/TokenEditDialog/TokenItem/TokenItem.css
  src/modules/core/components/TokenEditDialog/TokenItem/TokenItem.css.d.ts
  src/modules/core/components/TokenEditDialog/TokenItem/TokenItem.tsx
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyTokenEditDialog/ColonyTokenEditDialog.tsx
  src/modules/dashboard/components/ColonyTokenEditDialog/index.ts
  src/modules/dashboard/components/ColonyTokenManagementDialog/ColonyTokenManagementDialog.tsx
  src/modules/dashboard/components/ColonyTokenManagementDialog/getTokenList.ts
  src/modules/dashboard/components/ColonyTokenManagementDialog/index.ts
  src/modules/dashboard/components/ColonyTokenManagementDialog/tokens/tokenList.goerli.json
  src/modules/dashboard/components/ColonyTokenManagementDialog/tokens/tokenList.mainnet.json
  src/modules/dashboard/components/ColonyTokenManagementDialog/tokens/tokenList.xdai.json
  src/modules/dashboard/components/CreateColonyWizard/TokenSelector.css
  src/modules/dashboard/components/CreateColonyWizard/TokenSelector.css.d.ts
  src/modules/dashboard/components/CreateColonyWizard/TokenSelector.tsx
  src/modules/dashboard/components/Wallet/UserTokenEditDialog.tsx
  src/types/index.ts
Labels: maintenance

#2337 Manage Domains "Index" Modal
  src/img/icons.json
  src/img/icons/emoji-pencil-note.svg
  src/modules/dashboard/components/ColonyActionsDialog/ColonyActionsDialog.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/ManageDomainsDialog/ManageDomainsDialog.tsx
  src/modules/dashboard/components/ManageDomainsDialog/index.ts
Labels: feature

#2342 Add advanced modal
  src/img/icons.json
  src/img/icons/emoji-dna.svg
  src/img/icons/emoji-edit-tools.svg
  src/img/icons/emoji-strong-person.svg
  src/modules/dashboard/components/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/AdvancedDialog/index.ts
  src/modules/dashboard/components/ColonyActionsDialog/ColonyActionsDialog.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
Labels: feature
