Repository JoinColony/colonyDapp, pull requests merged in 2021-09, with the labels that each got.

#2673 Fix Reputation Oracle Endpoint
  src/modules/core/sagas/utils/getNetworkClient.ts
Labels: bug

#2662 Refactor remaining display widget
  src/modules/dashboard/components/CoinMachine/CoinMachine.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidget/RemainingDisplayWidget.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidget/index.ts
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingDisplayWidget.css
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingDisplayWidget.css.d.ts
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingDisplayWidget.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTime.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTokens.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/index.ts
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.tsx
  src/utils/colonyCoinMachine.ts
  src/utils/components/RemainingTokensValue.tsx
Labels: maintenance

#2678 Add permissions section to MembersInfoPopover
  src/modules/core/components/Heading/Heading.css
  src/modules/core/components/Heading/Heading.css.d.ts
  src/modules/core/components/InfoPopover/InfoPopover.css
  src/modules/core/components/InfoPopover/InfoPopover.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.css
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.css.d.ts
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/UserPermissions.tsx
  src/modules/core/components/MembersList/MembersList.tsx
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/core/components/UserAvatar/UserAvatar.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/dashboard/components/Whitelist/Whitelist.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistAddresses.tsx
  src/modules/users/components/UserInfo/UserInfo.tsx
Labels: feature

#2689 Add smite dialog
  src/modules/dashboard/components/ColonyActionsDialog/ColonyActionsDialog.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/SmiteDialog/SmiteDialog.tsx
  src/modules/dashboard/components/SmiteDialog/SmiteDialogForm.css
  src/modules/dashboard/components/SmiteDialog/SmiteDialogForm.css.d.ts
  src/modules/dashboard/components/SmiteDialog/SmiteDialogForm.tsx
  src/modules/dashboard/components/SmiteDialog/TeamDropdownItem.css
  src/modules/dashboard/components/SmiteDialog/TeamDropdownItem.css.d.ts
  src/modules/dashboard/components/SmiteDialog/TeamDropdownItem.tsx
  src/modules/dashboard/components/SmiteDialog/index.ts
Labels: feature

#2680 Update extension setup styles based on new specs
  src/modules/core/components/BreadCrumb/BreadCrumb.css
  src/modules/dashboard/components/Extensions/ExtensionDetails.css
  src/modules/dashboard/components/Extensions/ExtensionSetup.css
  src/modules/dashboard/components/Extensions/ExtensionSetup.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
Labels: feature

#2698 Update not enough reputation copy
  src/modules/dashboard/components/NotEnoughReputation/NotEnoughReputation.tsx
Labels: bug

#2696 Fix User Profile page not loading
  src/modules/core/components/UserMention/UserMention.tsx
  src/modules/users/components/UserProfile/UserProfile.tsx
  src/modules/users/hooks.ts
  src/modules/users/sagas/user.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/user.ts
Labels: bug

#2715 Add Blockscout link to event list
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.css
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.css.d.ts
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.tsx
Labels: feature

#2709 Filter out duplicated forced events for motions
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
  src/modules/dashboard/transformers.ts
  src/utils/hooks/useEnabledExtensions.tsx
Labels: feature

#2717 Update tell me more link
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.tsx
Labels: feature

#2716 Update motion page
  src/modules/core/components/Slider/Slider.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
Labels: maintenance

#2729 Fix the token address in token selector part in `ExtensionSetup`
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
Labels: bug

#2734 Fix/2726 update remaining tokens price status icon
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTokens.tsx
  src/utils/colonyCoinMachine.ts
Labels: bug

#2731 Update BuyTokens validation
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.tsx
Labels: bug

#2722 Add copy button to coin machine contract address
  src/modules/dashboard/components/Extensions/ExtensionDetails.css
  src/modules/dashboard/components/Extensions/ExtensionDetails.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
Labels: feature

#2725 Use transaction token instead of colony token
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/transformers.ts
  src/types/colonyActions.ts
  src/utils/colonyActions.ts
Labels: bug

#2735 Add confetti when token are sold out
  package-lock.json
  package.json
  src/modules/dashboard/components/CoinMachine/CoinMachine.tsx
  src/modules/dashboard/components/CoinMachine/Confetti/Confetti.tsx
  src/modules/dashboard/components/CoinMachine/Confetti/index.tsx
  src/utils/hooks/useWindowSize.ts
Labels: feature

#2736 Update totalStakeFraction and userMinStakeFraction default value
  src/data/staticData/extensionData.ts
Labels: maintenance

#2738 Better Metamask Login Experience
  package-lock.json
  package.json
  src/modules/users/components/ConnectWalletWizard/StepMetaMask/StepMetaMask.tsx
Labels: maintenance

#2741 Add autofocus to comment box input
  package-lock.json
  package.json
  src/modules/core/components/Fields/Textarea/TextareaAutoresize.tsx
  src/modules/dashboard/components/ActionsPage/InputStorageWidget/InputStorageWidget.tsx
  src/modules/dashboard/components/ActionsPageComment/ActionsPageComment.tsx
Labels: feature

#2742 Fix ipfs domain error showing "Ooops, action not found"
  src/utils/events/index.ts
Labels: bug

#2744 Support upgrade colony motion
  src/i18n/en-actions.ts
  src/i18n/en-motions.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialog.tsx
  src/utils/events/index.ts
Labels: feature
