Repository JoinColony/colonyDapp, pull requests merged in 2021-03, with the labels that each got.

#2392 Token activation button UI updates
  src/modules/pages/components/RouteLayouts/UserNavigation.css
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.css
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.css.d.ts
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.tsx
Labels: feature

#2394 Fixed UserPermissions headRole conditional
  src/modules/dashboard/components/UserPermissions/UserPermissions.tsx
Labels: bug

#2397 Fix Token Management Modal Back Button
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/dashboard/components/ColonyTokenManagementDialog/ColonyTokenManagementDialog.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.tsx
Labels: bug

#2396 Add Tooltip to colony event list titles
  src/modules/core/components/Fields/Checkbox/Checkbox.tsx
  src/modules/core/components/IndexModal/IndexModalItem.css
  src/modules/core/components/IndexModal/IndexModalItem.tsx
  src/modules/core/components/InvisibleCopyableAddress/InvisibleCopyableAddress.css
  src/modules/core/components/InvisibleCopyableAddress/InvisibleCopyableAddress.css.d.ts
  src/modules/core/components/InvisibleCopyableAddress/InvisibleCopyableAddress.tsx
  src/modules/core/components/PermissionRequiredInfo/PermissionRequiredInfo.css
  src/modules/core/components/PermissionRequiredInfo/PermissionRequiredInfo.tsx
  src/modules/core/components/Popover/PopoverWrapper.css
  src/modules/core/components/Popover/PopoverWrapper.css.d.ts
  src/modules/core/components/Popover/Tooltip.tsx
  src/modules/core/components/Popover/types.ts
  src/modules/dashboard/components/ActionsPage/TransactionStatus/TransactionStatus.css
  src/modules/dashboard/components/ActionsPage/TransactionStatus/TransactionStatus.css.d.ts
  src/modules/dashboard/components/ActionsPage/TransactionStatus/TransactionStatus.tsx
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.css
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.css.d.ts
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.tsx
Labels: bug

#2399 Remove outline globally
  src/styles/main.css
Labels: maintenance

#2395 Added loading message to colony extension section
  src/modules/dashboard/components/ColonyHome/ColonyExtensions/ColonyExtensions.css
  src/modules/dashboard/components/ColonyHome/ColonyExtensions/ColonyExtensions.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyExtensions/ColonyExtensions.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css
Labels: maintenance

#2401 ColonyUpgrade add optional upgrade styles
  src/modules/constants.ts
  src/modules/core/components/Alert/Alert.css
  src/modules/core/components/Alert/Alert.css.d.ts
  src/modules/core/components/Alert/Alert.tsx
  src/modules/core/sagas/setupUserContext.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageSystemInfo/ActionsPageSystemInfo.css
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.css
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.tsx
  src/utils/external/index.ts
Labels: feature

#2403 Hide Coin Machine Extensions
  src/modules/dashboard/components/Extensions/Extensions.tsx
Labels: maintenance

#2404 Fix "All Teams" reputation display
  src/data/resolvers/user.ts
Labels: bug

#2405 Display wallet address instead of colony address in membersListItem
  src/modules/core/components/MembersList/MembersListItem.tsx
Labels: bug

#2402 Create Slider component
  package-lock.json
  package.json
  src/modules/core/components/Slider/Slider.tsx
  src/modules/core/components/Slider/index.ts
  webpack.base.js
Labels: feature

#2409 Create radio buttons structure
  src/modules/core/components/Fields/Radio/CustomRadio.css
  src/modules/core/components/Fields/Radio/CustomRadio.css.d.ts
  src/modules/core/components/Fields/Radio/CustomRadio.tsx
  src/modules/core/components/Fields/Radio/index.ts
  src/modules/core/components/Fields/RadioGroup/CustomRadioGroup.css
  src/modules/core/components/Fields/RadioGroup/CustomRadioGroup.css.d.ts
  src/modules/core/components/Fields/RadioGroup/CustomRadioGroup.md
  src/modules/core/components/Fields/RadioGroup/CustomRadioGroup.tsx
  src/modules/core/components/Fields/RadioGroup/index.ts
Labels: feature

#2400 Add themes and threshold to ProgressBar
  src/modules/core/components/ProgressBar/ProgressBar.css
  src/modules/core/components/ProgressBar/ProgressBar.css.d.ts
  src/modules/core/components/ProgressBar/ProgressBar.tsx
Labels: feature

#2385 Implement token activation popover
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/index.ts
  src/data/resolvers/user.ts
  src/img/icons.json
  src/img/icons/emoji-padlock-closed.svg
  src/modules/core/components/Button/Button.css
  src/modules/core/components/Button/Button.css.d.ts
  src/modules/core/components/Button/Button.tsx
  src/modules/core/components/Fields/Input/Input.tsx
  src/modules/core/components/Fields/Input/InputComponent.css
  src/modules/core/components/Fields/Input/InputComponent.css.d.ts
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/core/components/IndexModal/IndexModalItem.css
  src/modules/core/components/IndexModal/IndexModalItem.css.d.ts
  src/modules/core/components/MembersList/MembersListItem.css
  src/modules/core/components/MembersList/MembersListItem.css.d.ts
  src/modules/core/components/Numeral/Numeral.tsx
  src/modules/core/components/Tabs/Tab.tsx
  src/modules/core/components/Tabs/TabList.tsx
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.css
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.css.d.ts
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/ChangeTokenStateForm.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/ClaimsTab.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/TokenActivationContent.css
  src/modules/users/components/TokenActivation/TokenActivationContent/TokenActivationContent.css.d.ts
  src/modules/users/components/TokenActivation/TokenActivationContent/TokenActivationContent.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/TokenTooltip.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/TokensTab.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/index.ts
  src/modules/users/components/TokenActivation/TokenActivationPopover.css
  src/modules/users/components/TokenActivation/TokenActivationPopover.css.d.ts
  src/modules/users/components/TokenActivation/TokenActivationPopover.tsx
  src/modules/users/components/TokenActivation/index.ts
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.css
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.tsx
  src/redux/actionTypes.ts
  src/redux/types/actions/user.ts
  src/styles/variables.css
  src/utils/numbers/formatTokenValue.ts
  src/utils/numbers/index.ts
Labels: feature

#2412 Create tag components variants
  src/modules/core/components/Tag/Tag.css
  src/modules/core/components/Tag/Tag.css.d.ts
  src/modules/core/components/Tag/Tag.tsx
  src/styles/variables.css
Labels: feature

#2411 Add MemberReputation component
  src/modules/core/components/MemberReputation/MemberReputation.css
  src/modules/core/components/MemberReputation/MemberReputation.css.d.ts
  src/modules/core/components/MemberReputation/MemberReputation.tsx
  src/modules/core/components/MemberReputation/index.ts
  src/modules/core/components/MembersList/MembersList.tsx
  src/modules/core/components/MembersList/MembersListItem.css
  src/modules/core/components/MembersList/MembersListItem.css.d.ts
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/pages/components/RouteLayouts/UserNavigation.css
  src/modules/pages/components/RouteLayouts/UserNavigation.css.d.ts
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
Labels: feature

#2415 Create `Toggle` form core component
  src/modules/core/components/Fields/Toggle/Toggle.css
  src/modules/core/components/Fields/Toggle/Toggle.css.d.ts
  src/modules/core/components/Fields/Toggle/Toggle.tsx
  src/modules/core/components/Fields/Toggle/index.ts
  src/modules/core/components/Fields/index.ts
Labels: feature

#2406 Add vote results widget
  src/img/icons.json
  src/img/icons/circle-thumbs-down.svg
  src/img/icons/circle-thumbs-up.svg
  src/modules/core/components/ProgressBar/ProgressBar.css
  src/modules/core/components/ProgressBar/ProgressBar.css.d.ts
  src/modules/core/components/ProgressBar/ProgressBar.tsx
  src/modules/dashboard/components/ActionsPage/VoteResultsWidget/VoteResultsWidget.css
  src/modules/dashboard/components/ActionsPage/VoteResultsWidget/VoteResultsWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/VoteResultsWidget/VoteResultsWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteResultsWidget/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.tsx
  src/utils/hooks/useAvatarDisplayCounter.ts
Labels: feature

#2414 Add motion and objection displays
  src/modules/core/components/ArgumentDisplay/ArgumentDisplay.css
  src/modules/core/components/ArgumentDisplay/ArgumentDisplay.css.d.ts
  src/modules/core/components/ArgumentDisplay/ArgumentDisplay.tsx
  src/modules/core/components/ArgumentDisplay/index.ts
  src/modules/core/components/Tag/Tag.css
  src/modules/core/components/Tag/Tag.css.d.ts
  src/modules/core/components/Tag/Tag.tsx
Labels: feature

#2417 Create logic for displaying toggle in modals
  src/modules/core/components/Dialog/DialogSection.css
  src/modules/core/components/Fields/Toggle/Toggle.tsx
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/ManageFundsDialog/ManageFundsDialog.tsx
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.tsx
  src/modules/dashboard/components/TokenMintDialog/TokenMintForm.tsx
  src/utils/hooks/useEnabledExtensions.tsx
Labels: feature

#2419 Mint token motion component
  src/App.tsx
  src/i18n/en-motions.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/index.ts
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/types/colonyMotions.ts
  src/types/index.ts
  src/utils/colonyActions.ts
Labels: feature

#2424 Fix Payment Action Roles in Static Map
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
Labels: bug

#2425 Permissions Modal rename Domain to Team
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementCheckbox.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
Labels: bug

#2426 Allow `HookedTokenIcon` to Fetch Token Images for More Networks
  src/modules/constants.ts
  src/modules/dashboard/components/HookedTokenIcon/HookedTokenIcon.tsx
Labels: maintenance

#2422 Show Join Colony Button for All Users
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.tsx
Labels: maintenance

#2427 Filter out Reputation Mining Cycle Incoming Transfers
  src/data/resolvers/colony.ts
  src/data/resolvers/transactions.ts
Labels: maintenance

#2423 Colony Title aligned with Colony Navigation
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.css
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.tsx
Labels: maintenance

#2428 Add `TokenSymbolSelector` & replace in `TransferFunds` & `CreatePayment`
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/core/components/Fields/Select/types.ts
  src/modules/core/components/Fields/TokenSymbolSelector/TokenSymbolSelector.css
  src/modules/core/components/Fields/TokenSymbolSelector/TokenSymbolSelector.css.d.ts
  src/modules/core/components/Fields/TokenSymbolSelector/TokenSymbolSelector.tsx
  src/modules/core/components/Fields/TokenSymbolSelector/index.ts
  src/modules/core/components/Fields/index.ts
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css.d.ts
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: maintenance

#2421 Fix Permission Modal bugs
  package-lock.json
  package.json
  src/modules/dashboard/components/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementCheckbox.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
Labels: bug

#2430 Add mini side loading states
  src/modules/core/components/Heading/Heading.tsx
  src/modules/core/components/Heading/index.ts
  src/modules/core/components/Preloaders/MiniSpinnerLoader.css
  src/modules/core/components/Preloaders/MiniSpinnerLoader.css.d.ts
  src/modules/core/components/Preloaders/MiniSpinnerLoader.tsx
  src/modules/core/components/Preloaders/SpinnerLoader.css
  src/modules/core/components/Preloaders/SpinnerLoader.css.d.ts
  src/modules/core/components/Preloaders/SpinnerLoader.tsx
  src/modules/core/components/Preloaders/index.ts
  src/modules/dashboard/components/ActionsPage/InputStorageWidget/InputStorageWidget.tsx
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.css
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
  src/modules/dashboard/components/ColonyHome/ColonyExtensions/ColonyExtensions.css
  src/modules/dashboard/components/ColonyHome/ColonyExtensions/ColonyExtensions.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyExtensions/ColonyExtensions.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css.d.ts
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.tsx
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.css
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.css.d.ts
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.tsx
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfers.css
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfers.css.d.ts
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfers.tsx
  src/modules/users/components/GasStation/MessageCard/MessageCardStatus.tsx
  src/modules/users/components/GasStation/TransactionCard/TransactionStatus.tsx
Labels: maintenance

#2433 Remove unused core items & refactor dashboard shared
  src/modules/core/components/OverviewList/OverviewList.css
  src/modules/core/components/OverviewList/OverviewList.css.d.ts
  src/modules/core/components/OverviewList/OverviewList.tsx
  src/modules/core/components/OverviewList/OverviewListItem.tsx
  src/modules/core/components/OverviewList/index.ts
  src/modules/core/components/Panel/Panel.css
  src/modules/core/components/Panel/Panel.css.d.ts
  src/modules/core/components/Panel/Panel.md
  src/modules/core/components/Panel/Panel.tsx
  src/modules/core/components/Panel/PanelSection.css
  src/modules/core/components/Panel/PanelSection.css.d.ts
  src/modules/core/components/Panel/PanelSection.tsx
  src/modules/core/components/Panel/index.ts
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
  src/modules/dashboard/components/ColonyEvents/ColonyEvents.tsx
  src/modules/dashboard/components/shared/eventsSort.ts
  src/modules/dashboard/components/shared/sortOptions.ts
Labels: maintenance

#2431 Extract IPFS logic from ActionsPageFeedItem
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/RecoveryAction.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItem/ActionsPageFeedItem.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItem/index.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItemWithIPFS/ActionsPageFeedItemWithIPFS.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItemWithIPFS/index.ts
  src/modules/dashboard/components/ActionsPageFeed/index.ts
Labels: maintenance
