Repository JoinColony/colonyDapp, pull requests merged in 2021-01, with the labels that each got.

#2341 Update default state when nativeToken is fetched
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.tsx
Labels: maintenance

#2339 Create domain modal
  src/modules/core/components/ColorSelect/ColorSelect.tsx
  src/modules/core/components/Fields/Input/Input.tsx
  src/modules/core/components/Fields/Input/InputComponent.css
  src/modules/core/components/Fields/Input/InputComponent.css.d.ts
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/core/components/Fields/Select/Select.css
  src/modules/core/components/Fields/Select/SelectListBox.css
  src/modules/core/components/Fields/Select/index.ts
  src/modules/core/components/Fields/index.ts
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/CreateEditDomainDialog/CreateEditDomainDialog.tsx
  src/modules/dashboard/components/CreateEditDomainDialog/CreateEditDomainDialogForm.css
  src/modules/dashboard/components/CreateEditDomainDialog/CreateEditDomainDialogForm.css.d.ts
  src/modules/dashboard/components/CreateEditDomainDialog/CreateEditDomainDialogForm.tsx
  src/modules/dashboard/components/CreateEditDomainDialog/index.ts
  src/modules/dashboard/components/ManageDomainsDialog/ManageDomainsDialog.tsx
Labels: feature

#2343 Enter Recovery Modal
  src/modules/admin/components/Profile/ProfileAdvanced.tsx
  src/modules/admin/components/RecoveryModeDialog/RecoveryModeDialog.tsx
  src/modules/dashboard/components/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/RecoveryModeDialog/RecoveryModeDialog.tsx
  src/modules/dashboard/components/RecoveryModeDialog/RecoveryModeDialogForm.css
  src/modules/dashboard/components/RecoveryModeDialog/RecoveryModeDialogForm.css.d.ts
  src/modules/dashboard/components/RecoveryModeDialog/RecoveryModeDialogForm.tsx
  src/modules/dashboard/components/RecoveryModeDialog/index.ts
Labels: feature

#2335 Mint Tokens flow wiring
  src/data/resolvers/colonyActions.ts
  src/i18n/en-actions.ts
  src/i18n/en-events.ts
  src/modules/admin/sagas/index.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/core/components/FriendlyName/FriendlyName.css
  src/modules/core/components/FriendlyName/FriendlyName.css.d.ts
  src/modules/core/components/FriendlyName/FriendlyName.tsx
  src/modules/core/components/FriendlyName/FriendlyNamecss.d.ts
  src/modules/core/components/FriendlyName/index.ts
  src/modules/core/components/FriendlyUserName/index.ts
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItem/ActionsPageFeedItem.tsx
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyHome/ColonyInitialFunding/ColonyInitialFunding.css
  src/modules/dashboard/components/ColonyHome/ColonyInitialFunding/ColonyInitialFunding.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyInitialFunding/ColonyInitialFunding.tsx
  src/modules/dashboard/components/ColonyHome/ColonyInitialFunding/index.ts
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialog.tsx
  src/modules/dashboard/components/ManageFundsDialog/ManageFundsDialog.tsx
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.tsx
  src/modules/dashboard/components/TokenMintDialog/TokenMintForm.css
  src/modules/dashboard/components/TokenMintDialog/TokenMintForm.css.d.ts
  src/modules/dashboard/components/TokenMintDialog/TokenMintForm.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialog.tsx
  src/modules/dashboard/sagas/actions.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colony.ts
  src/redux/types/actions/colonyActions.ts
  src/types/colonyActions.ts
  src/utils/colonyActions.ts
  src/utils/events/index.ts
Labels: feature

#2344 Upgrade Colony Modal
  src/modules/dashboard/components/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/CreateEditDomainDialog/CreateEditDomainDialogForm.css
  src/modules/dashboard/components/CreateEditDomainDialog/CreateEditDomainDialogForm.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.css
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialog.tsx
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.css
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.css.d.ts
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.tsx
  src/modules/dashboard/components/RecoveryModeDialog/RecoveryModeDialogForm.css
  src/modules/dashboard/components/RecoveryModeDialog/RecoveryModeDialogForm.tsx
Labels: feature

#2351 Wire `Mint Tokens` annotation
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.tsx
  src/modules/dashboard/sagas/actions.ts
  src/redux/types/actions/colonyActions.ts
Labels: feature

#2352 Wire `Transfer Funds` annotation
  src/i18n/en.json
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialog.tsx
  src/modules/dashboard/sagas/actions.ts
  src/redux/types/actions/colonyActions.ts
Labels: feature

#2345 Edit Colony Details Modal
  src/modules/admin/components/Profile/ColonyAvatarUploader.tsx
  src/modules/core/components/AvatarUploader/AvatarUploadItem.css
  src/modules/core/components/AvatarUploader/AvatarUploader.css
  src/modules/core/components/AvatarUploader/AvatarUploader.css.d.ts
  src/modules/core/components/AvatarUploader/AvatarUploader.tsx
  src/modules/core/components/FileUpload/DefaultPlaceholder.tsx
  src/modules/core/components/FileUpload/FileUpload.css
  src/modules/core/components/FileUpload/FileUpload.css.d.ts
  src/modules/core/components/FileUpload/FileUpload.tsx
  src/modules/core/components/FileUpload/index.ts
  src/modules/dashboard/components/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/EditColonyDetailsDialog/EditColonyDetailsDialog.tsx
  src/modules/dashboard/components/EditColonyDetailsDialog/EditColonyDetailsDialogForm.css
  src/modules/dashboard/components/EditColonyDetailsDialog/EditColonyDetailsDialogForm.css.d.ts
  src/modules/dashboard/components/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
  src/modules/dashboard/components/EditColonyDetailsDialog/index.ts
  src/modules/dashboard/sagas/colony.ts
  src/modules/users/components/UserProfileEdit/UserAvatarUploader.tsx
  src/redux/actionTypes.ts
  src/redux/types/actions/colony.ts
Labels: feature

#2350 Wire "Colony Actions" filter by domain
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/shared/actionsSort.ts
Labels: feature

#2349 Add "Load more" logic to Colony Actions
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/modules/core/components/Button/index.ts
  src/modules/core/components/LoadMoreButton/LoadMoreButton.css
  src/modules/core/components/LoadMoreButton/LoadMoreButton.css.d.ts
  src/modules/core/components/LoadMoreButton/LoadMoreButton.tsx
  src/modules/core/components/LoadMoreButton/index.ts
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
Labels: feature

#2354 Metamask v9 migration
  package-lock.json
  package.json
  src/modules/core/sagas/setupUserContext.ts
  src/modules/users/sagas/wallet.ts
Labels: bug
