Repository JoinColony/colonyDapp, pull requests merged in 2021-06, with the labels that each got.

#2526 Fix `Passed` tag
  src/utils/events/index.ts
Labels: bug

#2525 Improve token activation navigation button styles
  src/modules/pages/components/RouteLayouts/UserNavigation.css
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.css
Labels: bug

#2519 Add missing motion titles to the action list
  src/data/resolvers/motions.ts
  src/i18n/en-actions.ts
  src/modules/core/components/ActionsList/ActionsListItem.css
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/transformers.ts
  src/types/colonyActions.ts
  src/utils/colonyMotions.ts
  src/utils/hooks/useFormatRolesTitle.ts
Labels: feature

#2520 Wire Extensions Compatibility Mapping
  package-lock.json
  package.json
  src/modules/dashboard/components/Extensions/ExtensionActionButton.tsx
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/dashboard/components/Extensions/ExtensionUpgrade/ExtensionUpgrade.tsx
Labels: feature

#2529 Update copy for motion finalized event
  src/i18n/en-events.ts
Labels: bug

#2528 Feat: add voting progress bar tooltip
  src/modules/core/components/QuestionMarkTooltip/QuestionMarkTooltip.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteDetails.tsx
Labels: feature

#2532 Update motion tags and some message copies
  src/i18n/en-system-messages.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
  src/utils/colonyMotions.ts
  src/utils/events/index.ts
Labels: feature

#2508 Fix countdown timer not updating
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
Labels: bug

#2534 Remove reveal vote event from events
  src/data/resolvers/motions.ts
  src/i18n/en-events.ts
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
Labels: feature

#2537 Fix long action titles hiding the motion state tag
  src/modules/core/components/ActionsList/ActionsListItem.css
  src/modules/core/components/ActionsList/ActionsListItem.css.d.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
Labels: bug

#2536 Update copy of voting extension uninstallation
  src/modules/core/components/Warning/Warning.css
  src/modules/dashboard/components/Extensions/extensionsMSG.ts
Labels: feature

#2538 Add extra condition for motion failed system message
  src/data/resolvers/motions.ts
Labels: bug

#2533 Fix missing motion fully staked event
  src/data/resolvers/motions.ts
Labels: bug

#2531 Fix permission modal UI
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.css
Labels: bug

#2539 Improve event feed items spacing
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.css
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItem/ActionsPageFeedItem.css
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageSystemMessage/ActionsPageSystemMessage.css
Labels: bug

#2540 Update spacing and alignment on VotingWidget
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/VoteResults/VoteResults.css
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/VoteResults/VoteResultsItem.css
Labels: bug

#2543 Update `TransferFundsDialog` form to avoid validation error on `to` domain field
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: bug

#2541 Update voting widget UI
  src/img/icons.json
  src/img/icons/circle-thumbs-down-grey.svg
  src/img/icons/circle-thumbs-down-outlined.svg
  src/img/icons/circle-thumbs-up-grey.svg
  src/img/icons/circle-thumbs-up-outlined.svg
  src/modules/core/components/Fields/Radio/CustomRadio.css
  src/modules/core/components/ProgressBar/ProgressBar.css
  src/modules/core/components/ProgressBar/ProgressBar.css.d.ts
  src/modules/core/components/ProgressBar/ProgressBar.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
Labels: bug

#2544 Enable extension without reloading
  src/modules/core/sagas/setupUserContext.ts
  src/modules/core/sagas/utils/index.ts
  src/modules/core/sagas/utils/rehydrateClients.ts
  src/modules/core/sagas/utils/reinitializeColonyManager.ts
  src/modules/dashboard/sagas/extensions.ts
Labels: bug

#2542 Fix being able to claim when total is 0
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
Labels: bug

#2545 Fix MotionHasFailedFinalizable system message
  src/data/resolvers/motions.ts
Labels: bug

#2549 Fix motions are not displaying
  src/data/resolvers/motions.ts
Labels: bug

#2548 Remove Required Stake Off-by-one Compensation Hack
  src/data/resolvers/motions.ts
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidgetFlow.tsx
  src/modules/dashboard/components/ActionsPage/TotalStakeWidget/SingleTotalStake.tsx
  src/utils/colonyMotions.ts
  src/utils/events/index.ts
Labels: maintenance

#2551 Voting rewards updates
  src/data/resolvers/motions.ts
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteDetails.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.css
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.css.d.ts
Labels: bug

#2546 Fix CountdownTimer copies
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
Labels: bug

#2550 Update styles of UserPicker core component
  src/img/icons.json
  src/img/icons/filled-circle-person.svg
  src/modules/core/components/OmniPicker/OmniPicker.css
  src/modules/core/components/OmniPicker/OmniPicker.css.d.ts
  src/modules/core/components/OmniPicker/OmniPicker.tsx
  src/modules/core/components/OmniPicker/OmniPickerContent.css
  src/modules/core/components/SingleUserPicker/ItemDefault.css
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css.d.ts
  src/modules/core/components/SingleUserPicker/SingleUserPicker.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
Labels: maintenance

#2553 Update motion system messages
  src/data/resolvers/motions.ts
  src/i18n/en-system-messages.ts
  src/modules/dashboard/components/ActionsPageFeed/types.ts
Labels: bug

#2557 Fix event transaction link
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
Labels: bug

#2560 Fix wrongly represented big numbers while sending staking value
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
Labels: bug

#2552 Finalize Motion Manual Gas Estimation
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/sagas/motions/finalizeMotion.ts
Labels: bug

#2547 Add countdown timer to motions in actions list
  src/data/generated.ts
  src/data/graphql/subscriptions.graphql
  src/data/graphql/typeDefsSubscriptions.ts
  src/data/resolvers/motions.ts
  src/modules/core/components/ActionsList/ActionsListItem.css
  src/modules/core/components/ActionsList/ActionsListItem.css.d.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.css
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
  src/modules/dashboard/transformers.ts
  src/types/colonyActions.ts
Labels: feature

#2558 Update claim widget copy
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
Labels: feature

#2554 Update NotEnoughReputation component
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/dashboard/components/CreateDomainDialog/CreateDomainDialogForm.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialogForm.tsx
  src/modules/dashboard/components/NotEnoughReputation/NotEnoughReputation.css
  src/modules/dashboard/components/NotEnoughReputation/NotEnoughReputation.css.d.ts
  src/modules/dashboard/components/NotEnoughReputation/NotEnoughReputation.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: bug

#2561 Motion `args` Resolver handle native chain token payments (ETH/XDAI)
  src/data/resolvers/motions.ts
Labels: bug

#2556 Fix and update objection annotation
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialog.tsx
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialogForm.tsx
  src/modules/dashboard/sagas/utils/updateMotionValues.ts
Labels: bug

#2564 Fix system message using domain instead of teams
  src/i18n/en-system-messages.ts
Labels: bug

#2563 Hide New Action button on event list
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
Labels: bug

#2566 Improve tag base styles
  src/modules/core/components/Tag/Tag.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/Extensions/ExtensionStatus.css
  src/modules/dashboard/components/Extensions/ExtensionStatus.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionStatus.tsx
Labels: bug

#2569 Update styles of StakingWidget
  src/modules/core/components/Slider/Slider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialogForm.tsx
Labels: bug

#2559 Fix Successful Permissions Management Motions Titles (Permissions Comparisons)
  package-lock.json
  package.json
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/subscriptions.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colony.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/transformers.ts
  src/types/colonyActions.ts
  src/utils/colonyActions.ts
  src/utils/colonyMotions.ts
  src/utils/events/index.ts
Labels: bug

#2572 Fix issue with not reseting timer after fully object
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
  src/modules/dashboard/sagas/utils/updateMotionValues.ts
  src/modules/dashboard/transformers.ts
  src/types/colonyActions.ts
Labels: bug

#2573 Fix transfer funds action description copy
  src/modules/dashboard/components/ManageFundsDialog/ManageFundsDialog.tsx
Labels: bug

#2575 Fix nay side staking calculation
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialog.tsx
Labels: bug

#2574 Fix countdown timer loading UI with voting progress bar
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.css
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.css.d.ts
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
Labels: bug

#2571 Remove XDAI conversion to USD
  src/modules/core/components/EthUsd/EthUsd.tsx
Labels: bug

#2562 New action domain preselection
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyHome/ColonyDomainSelector/ColonyDomainSelector.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialog.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialog.tsx
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialogForm.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialog.tsx
Labels: feature

#2576 Fix ColonyFromName messing up Home, Funding and Members
  src/data/resolvers/colony.ts
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/pages/components/BackTexts/ColonyBackText.tsx
Labels: bug

#2568 Update domain description styles on DetailsWidget
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.css
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
Labels: bug

#2567 Update alignment of countdown timer
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
Labels: bug

#2577 Increase Finalize Motion Saga Gas Estimate
  src/modules/dashboard/sagas/motions/finalizeMotion.ts
Labels: bug

#2579 Update root, admin, and arbitration permission icons
  src/img/icons.json
  src/img/icons/emoji-balance.svg
  src/img/icons/emoji-clipboard.svg
  src/img/icons/emoji-yellow-superman.svg
  src/modules/core/components/PermissionsLabel/permissions.ts
Labels: maintenance

#2580 Replace feedback.fish widget with External link
  .env.example
  package-lock.json
  package.json
  src/modules/core/components/FeedbackWidget/FeedbackWidget.css
  src/modules/core/components/FeedbackWidget/FeedbackWidget.css.d.ts
  src/modules/core/components/FeedbackWidget/FeedbackWidget.tsx
Labels: maintenance
