Repository JoinColony/colonyDapp, pull requests merged in 2021-05, with the labels that each got.

#2475 Balance activation issue
  src/modules/dashboard/sagas/actions/payment.ts
Labels: bug

#2473 Fixed user outcome message not considering winner side
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
Labels: bug

#2472 Add MotionRewardClaimed event
  src/data/resolvers/motions.ts
  src/i18n/en-events.ts
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
Labels: feature

#2474 User reputation in Feed using rootHash
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colonyActions.ts
  src/data/resolvers/user.ts
  src/modules/core/components/MemberReputation/MemberReputation.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
  src/utils/events/index.ts
Labels: feature

#2476 Fix invalid tag
  src/utils/colonyMotions.ts
  src/utils/events/index.ts
Labels: bug

#2479 Add reveal result system message
  src/data/resolvers/motions.ts
  src/i18n/en-system-messages.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/index.ts
  src/modules/dashboard/components/ActionsPageFeed/types.ts
  src/utils/colonyMotions.ts
Labels: feature

#2459 Flesh out DetailsWidget of motion page
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
Labels: feature

#2481 Filter out events from contract
  src/modules/dashboard/transformers.ts
Labels: bug

#2486 Update objection modal
  src/modules/core/components/Dialog/Dialog.css
  src/modules/core/components/Slider/Slider.css
  src/modules/core/components/Slider/Slider.css.d.ts
  src/modules/core/components/Slider/Slider.tsx
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialogForm.css
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialogForm.tsx
Labels: bug

#2491 UseEnabledExtensions hook refactoring
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.tsx
  src/utils/hooks/useEnabledExtensions.tsx
Labels: bug

#2483 Fix ActionPage showing StakeRequired on Failed motion
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/motions.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/utils/colonyMotions.ts
Labels: bug

#2493 Hide claim button if there is nothing to claim
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
Labels: bug

#2496 Fix slider limit
  src/modules/core/components/Slider/Slider.tsx
Labels: bug

#2494 Fix winner/loser side messages conditional
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
Labels: bug

#2488 Add mapping for all motions for `DetailsWidget`
  src/i18n/en-motions.ts
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/types/colonyMotions.ts
Labels: feature

#2487 Default 1 Gwei Gas Price on Xdai
  src/immutable/Transaction.ts
  src/modules/core/reducers/transactions.ts
  src/redux/types/actions/multisig.ts
  src/redux/types/actions/transaction.ts
Labels: maintenance

#2498 Fix permissions issues
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.tsx
Labels: bug

#2492 Fix Staking, Voting, Revealing Countdown Timer
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colonyActions.ts
  src/data/resolvers/extensions.ts
  src/data/resolvers/motions.ts
  src/modules/core/components/CountDownTimer/CountDownTimer.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/MintTokenMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.css
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.css.d.ts
  src/modules/dashboard/components/ActionsPage/CountDownTimer/CountDownTimer.tsx
  src/modules/dashboard/components/ActionsPage/CountDownTimer/index.ts
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.css
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/RevealWidget/RevealWidget.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidgetFlow.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialog.tsx
  src/modules/dashboard/sagas/motions/claimMotionRewards.ts
  src/modules/dashboard/sagas/motions/finalizeMotion.ts
  src/modules/dashboard/sagas/motions/index.ts
  src/modules/dashboard/sagas/motions/revealVoteMotion.ts
  src/modules/dashboard/sagas/motions/stakeMotion.ts
  src/modules/dashboard/sagas/motions/updateState.ts
  src/modules/dashboard/sagas/motions/voteMotion.ts
  src/modules/dashboard/sagas/utils/updateMotionValues.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colonyActions.ts
  src/redux/types/actions/index.ts
  src/redux/types/actions/motion.ts
  src/utils/colonyMotions.ts
  src/utils/events/index.ts
  src/utils/time/calculateTimeLeft.ts
  src/utils/time/index.ts
Labels: bug

#2500 Fix disabled input state
  src/modules/core/components/Fields/Input/InputComponent.css
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css
  src/modules/core/components/SingleUserPicker/SingleUserPicker.tsx
  src/modules/dashboard/components/Extensions/ExtensionStatus.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
Labels: bug

#2497 Add validation messages to StakingWidget
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.css
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.css.d.ts
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
  src/modules/dashboard/components/ActionsPage/StakingValidationError/index.ts
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialogForm.tsx
Labels: feature

#2499 Fix motion page banner and objection modal covering gas station
  src/modules/pages/components/RouteLayouts/NavBar/NavBar.css
Labels: bug

#2503 Uninstall extension warning modal
  src/modules/dashboard/components/Extensions/ExtensionDetails.css
  src/modules/dashboard/components/Extensions/ExtensionDetails.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/dashboard/components/Extensions/ExtensionUninstallConfirmDialog/ExtensionUninstallConfirmDialog.css
  src/modules/dashboard/components/Extensions/ExtensionUninstallConfirmDialog/ExtensionUninstallConfirmDialog.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionUninstallConfirmDialog/ExtensionUninstallConfirmDialog.tsx
  src/modules/dashboard/components/Extensions/ExtensionUninstallConfirmDialog/index.ts
  src/modules/dashboard/components/Extensions/extensionsMSG.ts
Labels: feature

#2469 Use moveDecimal to display stake rewards
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
Labels: bug

#2489 Decode motion types and redirect them to default motion
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/index.ts
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/utils/events/index.ts
Labels: feature

#2505 Voting reputation extension copies and validation
  src/data/staticData/extensionData.ts
  src/modules/dashboard/components/Extensions/ExtensionDetails.css
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/dashboard/components/Extensions/ExtensionSetup.css
  src/modules/dashboard/components/Extensions/ExtensionSetup.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
Labels: maintenance

#2501 Improve Token Activation popover styles
  src/modules/core/components/Fields/Input/InputComponent.css
  src/modules/pages/components/RouteLayouts/UserNavigation.css
  src/modules/users/components/TokenActivation/TokenActivationContent/TokenActivationContent.css
Labels: bug

#2507 Include staked tokens in total. Balance
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.tsx
Labels: bug

#2506 Adjust displaying rewards updated colonyNetwork
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/motions.ts
  src/img/icons.json
  src/img/icons/clny-token.svg
  src/modules/core/components/Numeral/Numeral.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/RevealWidget/RevealWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteDetails.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.css
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
Labels: feature

#2510 Slider staking limit visual, logic & explanation messages
  src/modules/core/components/Slider/Slider.css
  src/modules/core/components/Slider/Slider.tsx
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.css
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialogForm.tsx
  src/modules/dashboard/sagas/motions/paymentMotion.ts
Labels: feature

#2509 Decode motion values of wire up motions
  src/data/resolvers/colonyActions.ts
  src/data/resolvers/motions.ts
  src/i18n/en-motions.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialog.tsx
  src/modules/dashboard/sagas/motions/moveFundsMotion.ts
  src/redux/types/actions/motion.ts
  src/utils/events/index.ts
  src/utils/hooks/useFormatRolesTitle.ts
Labels: feature

#2512 Add incompatible extension warning
  src/modules/core/components/Warning/Warning.css
  src/modules/core/components/Warning/Warning.css.d.ts
  src/modules/core/components/Warning/Warning.tsx
  src/modules/core/components/Warning/index.tsx
  src/modules/dashboard/components/Extensions/ExtensionDetails.css
  src/modules/dashboard/components/Extensions/ExtensionDetails.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
Labels: feature

#2516 Fix edit/create domain motion
  src/utils/events/index.ts
Labels: bug

#2518 Add 1 to required stake
  src/data/resolvers/motions.ts
  src/utils/colonyMotions.ts
Labels: bug

#2517 Extension initialization gas station copy
  src/i18n/en.json
Labels: feature

#2515 Remove staking error messages when user is not logged in
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
Labels: bug

#2511 Update Voting / Revealing Entropy Message
  src/modules/dashboard/sagas/motions/revealVoteMotion.ts
  src/modules/dashboard/sagas/motions/voteMotion.ts
Labels: bug

#2523 Fix issue with wrongly displayed total staked value
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidgetFlow.tsx
  src/modules/dashboard/components/ActionsPage/TotalStakeWidget/SingleTotalStake.tsx
Labels: bug

#2504 Fix token activation displays of locked tokens
  src/modules/users/components/TokenActivation/TokenActivationContent/ChangeTokenStateForm.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/TokensTab.tsx
Labels: bug

#2522 Update voting reputation copies
  src/data/staticData/extensionData.ts
  src/modules/dashboard/components/Extensions/ExtensionSetup.css
  src/modules/dashboard/components/Extensions/ExtensionSetup.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
Labels: feature
