Repository JoinColony/colonyDapp, pull requests merged in 2021-12, with the labels that each got.

#2981 Members List Poor Man's Pagination
  src/modules/dashboard/components/CreateUserWizard/StepConfirmTransaction.tsx
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
  src/modules/users/components/AvatarDropdown/AvatarDropdown.tsx
  src/modules/users/components/AvatarDropdown/AvatarDropdownPopover.tsx
Labels: maintenance

#2984 Automatically add Xdai Chain when using Metamask
  package-lock.json
  package.json
  src/modules/constants.ts
  src/modules/users/sagas/wallet.ts
Labels: feature

#2983 Fixes assigning motionId properly when team is pre-selected
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialog.tsx
Labels: bug

#2987 Add annotations to the Unlock Token modal
  src/i18n/en.json
  src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenDialog.tsx
  src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx
  src/modules/dashboard/sagas/actions/unlockToken.ts
  src/redux/types/actions/colonyActions.ts
Labels: feature

#2957 Fixes coin machine footer padding issue
  src/modules/dashboard/components/CoinMachine/CoinMachine.css
Labels: maintenance

#2994 Fix edit domain dialog
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialog.tsx
Labels: bug

#3005 Updates beta warning link to gitbook
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.tsx
Labels: maintenance

#2997 Fixes permissions bug on unlock modal when token already unlocked
  src/modules/dashboard/components/ManageFundsDialog/ManageFundsDialog.tsx
  src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.css
  src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.css.d.ts
  src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx
Labels: bug

#3000 Better handling of long usernames
  src/modules/core/components/DetailsWidgetUser/DetailsWidgetUser.css
  src/modules/core/components/DetailsWidgetUser/DetailsWidgetUser.css.d.ts
  src/modules/core/components/DetailsWidgetUser/DetailsWidgetUser.tsx
  src/modules/core/components/FriendlyName/FriendlyName.css
  src/modules/core/components/FriendlyName/FriendlyName.css.d.ts
  src/modules/core/components/FriendlyName/FriendlyName.tsx
  src/modules/core/components/InfoPopover/InfoPopover.css
  src/modules/core/components/MembersList/MembersListItem.css
  src/modules/core/components/Popover/PopoverWrapper.tsx
  src/modules/core/components/SingleUserPicker/ItemDefault.css
  src/modules/core/components/SingleUserPicker/ItemDefault.css.d.ts
  src/modules/core/components/SingleUserPicker/ItemDefault.tsx
  src/modules/core/components/UserMention/UserMention.css
  src/modules/users/components/GasStation/TransactionCard/TransactionCard.css
  src/modules/users/components/UserProfile/UserMeta.css
  src/modules/users/components/UserProfileEdit/UserProfileEdit.css
  src/styles/main.css
Labels: maintenance

#2999 Show member popover when user avatar selected
  src/modules/core/components/ActionsList/ActionsListItem.css
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/core/components/Comment/Comment.tsx
  src/modules/core/components/DetailsWidgetUser/DetailsWidgetUser.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.css
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.css
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.tsx
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
Labels: feature

#3016 Modifies SaleFailed state to be more versatile
  src/modules/dashboard/components/CoinMachine/SaleStateWidget/SaleStateWidget.tsx
Labels: maintenance

#3008 Makes caret in single user picker open omni picker
  src/modules/core/components/SingleUserPicker/SingleUserPicker.tsx
Labels: bug

#3020 Fix conditions for red color text in remaining display widgets
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTime.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTokens.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTokensValue.tsx
Labels: bug

#3025 Fix transfer funds motion
  src/modules/dashboard/sagas/motions/moveFundsMotion.ts
Labels: bug

#3023 Fix interpretation of the decimal points in amount fields
  src/data/staticData/extensionData.tsx
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialog.tsx
  src/modules/dashboard/components/TokenMintDialog/TokenMintDialog.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialog.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/ChangeTokenStateForm.tsx
Labels: bug

#3032 Updates help link for Recovery Mode
  src/modules/externalUrls.ts
Labels: bug

#3029 Update validation error copy
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
Labels: feature

#3028 UX Improvements to members list views
  src/modules/core/components/MemberReputation/MemberReputation.tsx
  src/modules/core/components/MembersList/MembersListItem.css
  src/modules/core/components/MembersList/MembersListItem.css.d.ts
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/dashboard/components/Members/Members.tsx
Labels: feature

#3054 Improve UI of Claiming Tokens for a Colony
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfers.tsx
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfersItem.css
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfersItem.tsx
Labels: feature

#3055 Fix extensions page overflowing on lower resolutions
  src/modules/dashboard/components/Extensions/Extensions.css
  src/modules/dashboard/components/Extensions/Extensions.css.d.ts
  src/modules/dashboard/components/Extensions/Extensions.tsx
Labels: bug

#3049 Fix initial motion domain selection in `CreatePayment` & `Permissions` dialogs
  src/modules/dashboard/components/MotionDomainSelect/MotionDomainSelect.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
Labels: bug

#3050 Fix sold out conditionals of coin machine
  src/data/generated.ts
  src/data/graphql/queries/coinMachine.graphql
  src/data/graphql/typeDefs/coinMachine.ts
  src/data/resolvers/coinMachine.ts
  src/modules/dashboard/components/CoinMachine/CoinMachine.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTokens.tsx
Labels: bug

#3067 Add token info popover to Funding and Token Activation
  src/modules/core/components/InfoPopover/InfoPopover.css
  src/modules/core/components/InfoPopover/InfoPopover.css.d.ts
  src/modules/core/components/InfoPopover/TokenInfo.tsx
  src/modules/dashboard/components/TokenCard/TokenCard.css
  src/modules/dashboard/components/TokenCard/TokenCard.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/TokenActivationContent.css
  src/modules/users/components/TokenActivation/TokenActivationContent/TokensTab.tsx
Labels: feature

#3066 Fixes annotation comment hover state and spacing
  src/modules/core/components/Comment/Comment.css
  src/modules/core/components/Comment/Comment.css.d.ts
  src/modules/core/components/Comment/Comment.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItemWithIPFS/ActionsPageFeedItemWithIPFS.tsx
Labels: bug

#3071 Fix motions using old motion events
  src/data/generated.ts
  src/data/graphql/queries/motions.graphql
  src/data/resolvers/motions.ts
  src/data/resolvers/user.ts
Labels: bug

#3068 Add extension re-enabling functionality
  src/modules/dashboard/components/Extensions/ExtensionDetails.css
  src/modules/dashboard/components/Extensions/ExtensionDetails.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/dashboard/sagas/extensions/colonyExtensionDeprecate.ts
  src/redux/types/actions/colony.ts
Labels: feature
