Repository JoinColony/colonyDapp, pull requests merged in 2021-02, with the labels that each got.

#2358 Fix the user's wallet route
  src/data/cache.ts
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/token.ts
  src/data/resolvers/user.ts
  src/modules/dashboard/components/Wallet/UserTokenEditDialog.tsx
  src/modules/dashboard/components/Wallet/UserTokenEditDialogForm.css
  src/modules/dashboard/components/Wallet/UserTokenEditDialogForm.css.d.ts
  src/modules/dashboard/components/Wallet/UserTokenEditDialogForm.tsx
Labels: bug

#2362 Fix typo issues across the app
  src/i18n/en-events.ts
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscriptionInfoPopover.tsx
  src/modules/dashboard/components/CreateEditDomainDialog/CreateEditDomainDialog.tsx
  src/modules/dashboard/components/CreateEditDomainDialog/CreateEditDomainDialogForm.tsx
Labels: bug

#2357 Edit domain flow wiring
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colonyActions.ts
  src/i18n/en-actions.ts
  src/i18n/en-events.ts
  src/i18n/en.json
  src/modules/core/actionCreators/transactions.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/core/components/Fields/SelectOption/SelectOption.css
  src/modules/core/reducers/transactions.ts
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/CreateDomainDialog/CreateDomainDialog.tsx
  src/modules/dashboard/components/CreateDomainDialog/CreateDomainDialogForm.css
  src/modules/dashboard/components/CreateDomainDialog/CreateDomainDialogForm.css.d.ts
  src/modules/dashboard/components/CreateDomainDialog/CreateDomainDialogForm.tsx
  src/modules/dashboard/components/CreateDomainDialog/index.ts
  src/modules/dashboard/components/CreateEditDomainDialog/index.ts
  src/modules/dashboard/components/DomainDropdown/CreateDomainButton.tsx
  src/modules/dashboard/components/DomainDropdown/DomainDropdown.tsx
  src/modules/dashboard/components/DomainDropdown/DomainSelectItem.tsx
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialog.tsx
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialogForm.css
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialogForm.css.d.ts
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialogForm.tsx
  src/modules/dashboard/components/EditDomainDialog/index.ts
  src/modules/dashboard/components/ManageDomainsDialog/ManageDomainsDialog.tsx
  src/modules/dashboard/sagas/actions.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colonyActions.ts
  src/redux/types/actions/transaction.ts
  src/types/colonyActions.ts
  src/utils/colonyActions.ts
  src/utils/events/index.ts
Labels: feature

#2361 ColonyEvents: sorting, filtering, load more, fix `TransferFunds` event
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/i18n/en-events.ts
  src/modules/dashboard/components/ColonyEvents/ColonyEvents.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/shared/actionsSort.ts
  src/modules/dashboard/components/shared/eventsFilter.ts
  src/modules/dashboard/components/shared/eventsSort.ts
Labels: feature

#2363 Add beta caution banner
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.css
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.css.d.ts
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.tsx
  src/modules/core/components/BetaCautionAlert/index.ts
  src/modules/pages/components/RouteLayouts/NavBar/NavBar.tsx
  src/routes/AlwaysAccesibleRoute.tsx
  src/routes/WalletRequiredRoute.tsx
Labels: feature

#2367 Fix transfer funds validation issue
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: bug

#2336 Fixes, and changes for Dapp styling
  src/img/icons.json
  src/img/icons/caret-right-small.svg
  src/modules/core/components/CopyableAddress/CopyableAddress.css
  src/modules/core/components/Dialog/Dialog.css
  src/modules/core/components/DropdownMenu/DropdownMenu.css
  src/modules/core/components/Fields/Checkbox/Checkbox.css
  src/modules/core/components/Fields/Checkbox/Checkbox.css.d.ts
  src/modules/core/components/Fields/SelectOption/SelectOption.css
  src/modules/core/components/Icon/Icon.css
  src/modules/core/components/Icon/Icon.css.d.ts
  src/modules/core/components/InfoPopover/InfoPopover.css
  src/modules/core/components/InfoPopover/InfoPopover.css.d.ts
  src/modules/core/components/InfoPopover/MemberInfo.tsx
  src/modules/core/components/InfoPopover/TokenInfo.tsx
  src/modules/core/components/MaskedAddress/MaskedAddress.css
  src/modules/core/components/MembersList/MembersListItem.css
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/core/components/Modal/Modal.css
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css
  src/modules/dashboard/components/ColonyHome/ColonyHome.css
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyNavigation/NavItem.css
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css
  src/modules/dashboard/components/DomainDropdown/DomainDropdown.css
  src/modules/dashboard/components/DomainDropdown/DomainDropdown.tsx
  src/modules/dashboard/components/DomainDropdown/DomainSelectItem.css
  src/modules/dashboard/components/DomainDropdown/DomainSelectItem.css.d.ts
  src/modules/dashboard/components/DomainDropdown/DomainSelectItem.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementCheckbox.css
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
  src/modules/pages/components/RouteLayouts/Default/Default.css
  src/modules/users/components/AvatarDropdown/AvatarDropdown.css
  src/modules/users/components/AvatarDropdown/AvatarDropdown.css.d.ts
  src/modules/users/components/AvatarDropdown/AvatarDropdown.tsx
  src/styles/variables.css
Labels: maintenance

#2364 Use subscriptions to fetch Subgraph Actions and Events
  .env.example
  codegen.yml
  package-lock.json
  package.json
  src/context/apolloClient.ts
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/subscriptions.graphql
  src/data/graphql/typeDefs.ts
  src/data/graphql/typeDefsSubscriptions.ts
  src/data/index.ts
  src/data/resolvers/events.ts
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
  src/modules/dashboard/components/ColonyEvents/ColonyEvents.tsx
  src/modules/dashboard/sagas/actions.ts
  src/modules/dashboard/transformers.ts
  src/utils/colonyActions.ts
Labels: maintenance

#2366 Prevent ColonyHome children constant re-rendering
  src/modules/dashboard/components/ColonyHome/ColonyFinishDeployment/ColonyFinishDeployment.css
  src/modules/dashboard/components/ColonyHome/ColonyFinishDeployment/ColonyFinishDeployment.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyFinishDeployment/ColonyFinishDeployment.tsx
  src/modules/dashboard/components/ColonyHome/ColonyFinishDeployment/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.css
  src/modules/dashboard/components/ColonyHome/ColonyHome.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.css
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.tsx
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/index.ts
Labels: bug

#2368 Create Colony IPFS Metadata Upload Fallback/Retry
  src/modules/dashboard/sagas/colonyCreate.ts
Labels: maintenance

#2372 Add feedback link & integrate feedback.fish
  .env.example
  package-lock.json
  package.json
  src/modules/core/components/FeedbackWidget/FeedbackWidget.css
  src/modules/core/components/FeedbackWidget/FeedbackWidget.css.d.ts
  src/modules/core/components/FeedbackWidget/FeedbackWidget.tsx
  src/modules/core/components/FeedbackWidget/index.ts
  src/routes/AlwaysAccesibleRoute.tsx
  src/routes/WalletRequiredRoute.tsx
  src/styles/main.css
Labels: feature

#2375 Fix `useColonyFromNameQuery` not returning token balances for all domains
  src/data/generated.ts
  src/data/graphql/fragments.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/token.ts
  src/modules/dashboard/components/ColonyHome/ColonyFunding/TokenItem.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFundsPopover.tsx
  src/modules/dashboard/components/TokenCardList/TokenCardList.tsx
  src/utils/tokens.ts
Labels: bug

#2374 Prepare for Launch!
  .env.example
  package-lock.json
  package.json
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.css
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.tsx
  src/modules/core/components/FeedbackWidget/FeedbackWidget.css
  src/modules/core/sagas/utils/getNetworkClient.ts
Labels: maintenance

#2378 Add z-index to ColonyUpgrade and ColonyFinishDeployment banners
  src/modules/dashboard/components/ColonyHome/ColonyFinishDeployment/ColonyFinishDeployment.css
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.css
Labels: bug

#2377 Allow users to create payments in subdomains
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/ExpendituresDialog/ExpendituresDialog.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
Labels: bug

#2376 Fixed FriendlyName showing incorrect name/address
  src/modules/core/components/FriendlyName/FriendlyName.tsx
Labels: bug

#2379 Fix 404 redirection in ColonyHome page
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
Labels: bug

#2380 Add validation for AddressZero while creating colony
  src/modules/dashboard/components/CreateColonyWizard/StepSelectToken.tsx
Labels: feature

#2384 Display correct block explorer name in Transaction Meta
  src/modules/dashboard/components/ActionsPage/TransactionMeta/TransactionMeta.tsx
Labels: bug

#2386 Fix ERC20 unclaimed transfers to show up properly
  src/data/resolvers/transactions.ts
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfers.css
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfers.css.d.ts
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfers.tsx
Labels: bug

#2387 Fix FriendlyName not using the colony display
  src/modules/core/components/FriendlyName/FriendlyName.tsx
Labels: bug

#2389 Change banner position from absolute to fixed
  src/modules/dashboard/components/ColonyHome/ColonyFinishDeployment/ColonyFinishDeployment.css
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.css
Labels: bug

#2388 Remove what's left of the admin module
  src/modules/admin/checks.ts
  src/modules/admin/components/AdminDashboard/AdminDashboard.css
  src/modules/admin/components/AdminDashboard/AdminDashboard.css.d.ts
  src/modules/admin/components/AdminDashboard/AdminDashboard.tsx
  src/modules/admin/components/AdminDashboard/index.ts
  src/modules/admin/components/Permissions/PermissionForm.css
  src/modules/admin/components/Permissions/PermissionForm.css.d.ts
  src/modules/admin/components/RecoveryModeAlert/RecoveryModeAlert.css
  src/modules/admin/components/RecoveryModeAlert/RecoveryModeAlert.css.d.ts
  src/modules/admin/components/RecoveryModeAlert/RecoveryModeAlert.tsx
  src/modules/admin/components/RecoveryModeAlert/index.ts
  src/modules/admin/components/UserList/UserList.css
  src/modules/admin/components/UserList/UserList.css.d.ts
  src/modules/admin/components/UserList/UserList.tsx
  src/modules/admin/components/UserList/index.ts
  src/modules/admin/components/UserListItem/UserListItem.css
  src/modules/admin/components/UserListItem/UserListItem.css.d.ts
  src/modules/admin/components/UserListItem/UserListItem.tsx
  src/modules/admin/components/UserListItem/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyFunding/ColonyFunding.tsx
  src/redux/actionTypes.ts
  src/redux/types/actions/domain.ts
  src/redux/types/actions/index.ts
Labels: maintenance

#2383 Fix/dev 202 colony selectors styles
  src/img/icons/circle-plus.svg
  src/modules/core/components/Button/DottedAddButton.css
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.css
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.css.d.ts
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.tsx
  src/modules/pages/components/LandingPage/LandingPage.css
Labels: bug
