Repository JoinColony/colonyDapp, pull requests merged in 2021-11, with the labels that each got.

#2659 User Profile Popover
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/user.ts
  src/modules/core/components/Heading/Heading.css
  src/modules/core/components/Heading/Heading.css.d.ts
  src/modules/core/components/InfoPopover/InfoPopover.css
  src/modules/core/components/InfoPopover/InfoPopover.css.d.ts
  src/modules/core/components/InfoPopover/InfoPopover.tsx
  src/modules/core/components/InfoPopover/MemberInfo.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.css
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.css.d.ts
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/UserPermissions.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/UserReputation.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/UserTokens.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/index.ts
  src/modules/core/components/InfoPopover/UserInfo.tsx
  src/modules/core/components/MemberReputation/MemberReputation.tsx
  src/modules/core/components/MembersList/MembersList.tsx
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/core/components/UserAvatar/UserAvatar.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/dashboard/components/Whitelist/Whitelist.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistAddresses.tsx
  src/modules/users/components/UserInfo/UserInfo.tsx
  src/utils/reputation.ts
Labels: feature

#2790 Add error message for finalize motion widget
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/token.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.css
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
Labels: bug

#2830 Add default user to user picker in `Smite` dialog
  src/modules/dashboard/components/SmiteDialog/SmiteDialog.tsx
  src/modules/dashboard/components/SmiteDialog/SmiteDialogForm.tsx
  src/utils/hooks/useSelectedUser.ts
Labels: feature

#2832 Fix alignment on friendly name and masked address in events list
  src/modules/core/components/FriendlyName/FriendlyName.css
  src/modules/core/components/Popover/Tooltip.css
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.css
Labels: maintenance

#2827 Add award reputation action/motion saga
  src/i18n/en.json
  src/modules/dashboard/components/SmiteDialog/SmiteDialog.tsx
  src/modules/dashboard/sagas/actions/index.ts
  src/modules/dashboard/sagas/actions/manageReputation.ts
  src/modules/dashboard/sagas/motions/index.ts
  src/modules/dashboard/sagas/motions/manageReputationMotion.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colonyActions.ts
  src/redux/types/actions/motion.ts
Labels: feature

#2770 Add award reputation dialog
  src/modules/dashboard/components/AwardAndSmiteDialogs/AwardDialog/AwardDialog.tsx
  src/modules/dashboard/components/AwardAndSmiteDialogs/AwardDialog/index.ts
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationContainer/ManageReputationContainer.tsx
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationContainer/index.ts
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.css
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.css.d.ts
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.tsx
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationDialogForm/TeamDropdownItem.css
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationDialogForm/TeamDropdownItem.css.d.ts
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationDialogForm/TeamDropdownItem.tsx
  src/modules/dashboard/components/AwardAndSmiteDialogs/ManageReputationDialogForm/index.ts
  src/modules/dashboard/components/AwardAndSmiteDialogs/SmiteDialog/SmiteDialog.tsx
  src/modules/dashboard/components/AwardAndSmiteDialogs/SmiteDialog/index.ts
  src/modules/dashboard/components/AwardAndSmiteDialogs/index.ts
  src/modules/dashboard/components/AwardAndSmiteDialogs/types.ts
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/ManageReputationDialog/ManageReputationDialog.tsx
Labels: feature

#2841 Fix alignment of the wallet text in wizard
  src/modules/pages/components/WizardTemplateColony/WizardTemplateColony.css
Labels: maintenance

#2838 Update actionThatNeedAtension resolver to not use logs
  src/data/resolvers/events.ts
Labels: feature

#2773 Fix staking slider no more rep error
  src/modules/core/components/Slider/Slider.tsx
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/ChangeTokenStateForm.tsx
Labels: bug

#2858 Add DeleteCommentDialog
  src/modules/core/components/CommentDeleteDialog/CommentDeleteDialog.css
  src/modules/core/components/CommentDeleteDialog/CommentDeleteDialog.css.d.ts
  src/modules/core/components/CommentDeleteDialog/CommentDeleteDialog.tsx
  src/modules/core/components/CommentDeleteDialog/index.tsx
Labels: feature

#2872 Add missing smite motion title to vote and finalize widget
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
Labels: bug

#2864 Add BanUser dialog UI
  src/modules/core/components/BanUserDialog/BanUserDialog.css
  src/modules/core/components/BanUserDialog/BanUserDialog.css.d.ts
  src/modules/core/components/BanUserDialog/BanUserDialog.tsx
  src/modules/core/components/BanUserDialog/index.ts
Labels: feature

#2877 Fix permission label not being centered
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.css
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
Labels: bug

#2865 UI - add hover state with actions to a comment
  src/img/icons.json
  src/img/icons/circle-minus.svg
  src/img/icons/trash.svg
  src/immutable/Comment.ts
  src/immutable/index.ts
  src/modules/core/components/Comment/Comment.css
  src/modules/core/components/Comment/Comment.css.d.ts
  src/modules/core/components/Comment/Comment.tsx
  src/modules/core/components/Comment/CommentActions.css
  src/modules/core/components/Comment/CommentActions.css.d.ts
  src/modules/core/components/Comment/CommentActions.tsx
  src/modules/core/components/Comment/CommentActionsPopover.css
  src/modules/core/components/Comment/CommentActionsPopover.css.d.ts
  src/modules/core/components/Comment/CommentActionsPopover.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/RecoveryAction.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
  src/modules/dashboard/components/CoinMachine/Chat/Chat.css
  src/modules/dashboard/components/CoinMachine/Chat/Chat.tsx
Labels: feature

#2844 Fix ETH to USD conversion
  src/modules/core/components/EthUsd/EthUsd.tsx
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.css
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.css.d.ts
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.css.d.ts
  src/modules/dashboard/components/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: maintenance

#2881 Copies updates
  src/modules/dashboard/components/CreateColonyWizard/StepTokenChoice.tsx
  src/modules/dashboard/components/CreateDomainDialog/CreateDomainDialogForm.tsx
  src/modules/dashboard/components/EditDomainDialog/EditDomainDialogForm.tsx
  src/modules/dashboard/components/ExpendituresDialog/ExpendituresDialog.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementCheckbox.tsx
Labels: feature

#2880 Add fetch policy - network only to colony funding
  src/modules/dashboard/components/ColonyHome/ColonyFunding/ColonyFunding.tsx
Labels: bug

#2893 Update learn more and bug report links
  src/modules/dashboard/components/CreateColonyWizard/StepTokenChoice.tsx
  src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx
  src/modules/users/components/AvatarDropdown/AvatarDropdownPopover.tsx
Labels: maintenance

#2857 Wire up award action and motion page
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/motions.ts
  src/i18n/en-actions.ts
  src/i18n/en-events.ts
  src/i18n/en-motions.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.tsx
  src/modules/dashboard/transformers.ts
  src/types/colonyActions.ts
  src/types/colonyMotions.ts
  src/utils/colonyActions.ts
  src/utils/events/index.ts
Labels: feature

#2895 Update maximum per period field description
  src/data/staticData/extensionData.tsx
Labels: bug

#2907 Fix comments subscription using wrong data
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
  src/modules/dashboard/components/CoinMachine/Chat/Chat.tsx
  src/utils/hooks/useCurrentComments.ts
Labels: bug

#2920 Remove permission display from whitelist extension details
  src/data/staticData/extensionData.tsx
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
Labels: bug

#2919 Added event list copies for PeriodUpdated and TokenBought
  src/i18n/en-events.ts
  src/modules/dashboard/components/ColonyEvents/ColonyEventsListItem.tsx
  src/modules/dashboard/transformers/transformers.ts
  src/types/colonyActions.ts
Labels: feature

#2922 Fix long dates occupying 2 lines on Sale End column
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.css
Labels: bug

#2929 Improve token displays of SaleStateWidget and BuyTokens
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.tsx
  src/modules/dashboard/components/CoinMachine/SaleStateWidget/SaleStateWidget.tsx
  src/utils/tokens.ts
Labels: bug

#2924 Add polling logic to CoinMachine
  src/modules/dashboard/components/CoinMachine/CoinMachine.tsx
Labels: maintenance

#2925 Refactor coinMachineBoughtTokens to use chain events
  src/data/generated.ts
  src/data/graphql/queries/coinMachine.graphql
  src/data/graphql/typeDefs/coinMachine.ts
  src/data/resolvers/coinMachine.ts
  src/modules/dashboard/components/CoinMachine/SaleStateWidget/SaleStateWidget.tsx
  src/modules/dashboard/sagas/coinMachine/buyTokens.ts
Labels: bug

#2927 Update SynapsKYCDialog verified user copy
  src/img/icons.json
  src/img/icons/emoji-party.svg
  src/modules/dashboard/components/CoinMachine/SynapsKYCDialog/SynapsKYCDialog.css
  src/modules/dashboard/components/CoinMachine/SynapsKYCDialog/SynapsKYCDialog.tsx
Labels: maintenance

#2928 Refactor Whitelist user status
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/queries/extensions.graphql
  src/data/graphql/queries/whitelist.graphql
  src/data/graphql/typeDefs.ts
  src/data/graphql/typeDefs/coinMachine.ts
  src/data/graphql/typeDefs/extensions.ts
  src/data/graphql/typeDefs/whitelist.ts
  src/data/resolvers/extensions.ts
  src/data/resolvers/whitelist.ts
  src/data/staticData/extensionData.tsx
  src/i18n/en-events.ts
  src/modules/dashboard/components/CoinMachine/GetWhitelisted/GetWhitelisted.tsx
  src/modules/dashboard/components/Whitelist/AgreementDialog/AgreementDialog.tsx
  src/modules/dashboard/components/Whitelist/Whitelist.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistAddresses.css
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistAddresses.tsx
  src/modules/dashboard/sagas/extensions/colonyExtensionEnable.ts
  src/modules/dashboard/sagas/extensions/colonyExtensionUninstall.ts
  src/modules/dashboard/sagas/extensions/index.ts
  src/modules/dashboard/sagas/utils/refreshExtension.ts
  src/modules/dashboard/sagas/whitelist/index.ts
  src/modules/dashboard/sagas/whitelist/signAgreement.ts
  src/modules/dashboard/sagas/whitelist/updateWhitelist.ts
  src/redux/types/actions/whitelist.ts
  src/types/colonyActions.ts
  src/types/extensions.ts
  src/types/index.ts
  src/utils/contracts/index.ts
  src/utils/events/subgraphEvents.ts
Labels: bug

#2891 Replace kebab menu icon in dapp
  src/img/icons/three-dots-row.svg
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.tsx
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.tsx
Labels: maintenance

#2946 Fix countdown timer on motion finished
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
Labels: bug

#2956 Add Reputation auto-mining toggle details to readme
  Readme.md
Labels: maintenance

#2958 Hide `userLimitFraction` during coin machine installation when there is no whitelist
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
Labels: bug

#2959 Adds icon arrow-right for manage funds link
  src/img/icons.json
  src/img/icons/arrow-right.svg
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.tsx
Labels: maintenance

#2964 Update font weight of BuyTokens info tooltip
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.css
Labels: bug

#2963 Contain the scroll on dialogs
  src/modules/core/components/Dialog/Dialog.css
Labels: maintenance

#2962 Add missing permission tooltip copies
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
Labels: bug

#2961 Updated button size, copy and removed microcopy
  src/modules/core/components/Comment/Dialogs/BanComment/BanComment.css
  src/modules/core/components/Comment/Dialogs/BanComment/BanComment.tsx
Labels: maintenance

#2898 Add total sold vs available widget
  package-lock.json
  package.json
  src/data/generated.ts
  src/data/graphql/queries/coinMachine.graphql
  src/data/graphql/typeDefs/coinMachine.ts
  src/data/resolvers/coinMachine.ts
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.tsx
  src/modules/dashboard/components/CoinMachine/CoinMachine.css
  src/modules/dashboard/components/CoinMachine/CoinMachine.css.d.ts
  src/modules/dashboard/components/CoinMachine/CoinMachine.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingDisplayWidget.css
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingDisplayWidget.css.d.ts
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingDisplayWidget.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTokens.tsx
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTokensValue.tsx
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.css
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.css.d.ts
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.tsx
  src/modules/dashboard/components/CoinMachine/utils.ts
Labels: feature

#2968 Update dropdown copy
  src/modules/dashboard/components/MotionDomainSelect/MotionDomainSelect.tsx
Labels: feature

#2969 "I agree" button disabled, changing zoom makes button enabled
  src/modules/dashboard/components/Whitelist/AgreementDialog/AgreementDialog.tsx
Labels: bug

#2939 Add Userflow to Colony
  .env.example
  package-lock.json
  package.json
  src/index.ts
Labels: feature

#2948 Time remaining fix
  src/modules/dashboard/components/CoinMachine/RemainingDisplayWidgets/RemainingTime.tsx
  src/modules/dashboard/components/CoinMachine/SaleStateWidget/SaleStateWidget.tsx
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.tsx
  src/utils/hooks/useSplitTime.ts
Labels: bug

#2971 Refresh sales data period query after extension install
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.tsx
  src/modules/dashboard/sagas/utils/refreshExtension.ts
Labels: bug
