Repository JoinColony/colonyDapp, pull requests merged in 2021-07, with the labels that each got.

#2565 Improve formatting of TokenActivationPopover
  src/modules/constants.ts
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/ActionsPage/TotalStakeWidget/GroupedTotalStake.tsx
  src/modules/dashboard/components/ActionsPage/TotalStakeWidget/SingleTotalStake.tsx
  src/modules/dashboard/components/RaiseObjectionDialog/RaiseObjectionDialogForm.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/ChangeTokenStateForm.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/SmallTokenAmountMessage.css
  src/modules/users/components/TokenActivation/TokenActivationContent/SmallTokenAmountMessage.css.d.ts
  src/modules/users/components/TokenActivation/TokenActivationContent/SmallTokenAmountMessage.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/TokensTab.tsx
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.tsx
  src/utils/tokens.ts
Labels: bug

#2582 Use Blockscout GasStation Oracle for Xdai Gas Estimation
  src/immutable/Transaction.ts
  src/modules/core/sagas/transactions/estimateGasCost.ts
  src/modules/core/sagas/utils/getGasPrices.ts
  src/modules/users/components/GasStation/GasStationControls/GasStationControls.tsx
Labels: feature

#2578 Fix avatar count on ColonyHome page
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.tsx
  src/utils/hooks/useAvatarDisplayCounter.ts
Labels: bug

#2586 Force OneTxPayment Extension Upgrade to v2
  src/modules/dashboard/checks.ts
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyHome/ColonyDomainSelector/ColonyDomainSelector.tsx
  src/modules/dashboard/components/ColonyHome/ColonyFinishDeployment/ColonyFinishDeployment.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.tsx
  src/modules/dashboard/components/ColonyHome/ExtensionUpgrade/ExtensionUpgrade.css
  src/modules/dashboard/components/ColonyHome/ExtensionUpgrade/ExtensionUpgrade.css.d.ts
  src/modules/dashboard/components/ColonyHome/ExtensionUpgrade/ExtensionUpgrade.tsx
  src/modules/dashboard/components/ColonyHome/ExtensionUpgrade/index.ts
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.tsx
Labels: feature

#2583 Update UserPicker size and validation
  src/img/icons/filled-circle-person.svg
  src/modules/core/components/Fields/Input/Input.tsx
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/core/components/Fields/InputStatus/InputStatus.tsx
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css
  src/modules/dashboard/components/CreatePaymentDialog/CreatePaymentDialog.tsx
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementDialog.tsx
Labels: bug

#2587 Fix styles of ActionsListItem
  src/modules/core/components/ActionsList/ActionsListItem.css
Labels: bug

#2585 Display whitelist in available extensions
  package-lock.json
  package.json
  src/data/staticData/extensionData.ts
  src/modules/dashboard/components/Extensions/ExtensionDetails.css
  src/modules/dashboard/components/Extensions/ExtensionDetails.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
  src/modules/dashboard/components/Extensions/WhitelistExtensionBody/WhitelistExtensionBody.tsx
Labels: feature

#2589 Add Input/Upload placeholder component for adding address
  src/data/staticData/extensionData.ts
  src/modules/dashboard/components/Extensions/WhitelistExtensionBody/WhitelistExtensionBody.tsx
  src/modules/dashboard/components/Extensions/WhitelistExtensionBody/index.tsx
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/UploadAddressesWidget.css
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/UploadAddressesWidget.css.d.ts
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/UploadAddressesWidget.tsx
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/index.ts
  src/modules/dashboard/components/Whitelist/Whitelist.tsx
  src/modules/dashboard/components/Whitelist/index.tsx
  src/redux/actionTypes.ts
  src/redux/types/actions/colony.ts
Labels: feature

#2590 Add agreement textArea
  src/data/staticData/extensionData.ts
  src/modules/dashboard/components/Extensions/ExtensionSetup.css
  src/modules/dashboard/components/Extensions/ExtensionSetup.css.d.ts
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
Labels: feature

#2592 Wallet Auto-Login
  src/modules/pages/components/RouteLayouts/UserNavigation.css
  src/modules/pages/components/RouteLayouts/UserNavigation.css.d.ts
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
  src/modules/users/components/ConnectWalletWizard/StepGanache/StepGanache.tsx
  src/modules/users/components/ConnectWalletWizard/StepGanache/index.ts
  src/utils/autoLogin.ts
Labels: feature

#2595 Wire up Enable Whitelist extension
  src/data/staticData/extensionData.ts
  src/i18n/en.json
  src/lib/ColonyManager/ColonyManager.ts
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
  src/modules/dashboard/sagas/extensions.ts
Labels: feature

#2594 Add WhitelistAddresses component
  src/data/staticData/extensionData.ts
  src/modules/core/components/ListGroup/ListGroup.css
  src/modules/core/components/ListGroup/ListGroup.css.d.ts
  src/modules/core/components/ListGroup/ListGroup.tsx
  src/modules/core/components/ListGroup/index.ts
  src/modules/core/components/MembersList/MembersList.tsx
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/dashboard/components/Whitelist/Whitelist.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistAddresses.css
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistAddresses.css.d.ts
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistAddresses.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistMembersListExtraContent.css
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistMembersListExtraContent.css.d.ts
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistMembersListExtraContent.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/index.tsx
Labels: feature

#2606 Estimate Gas Cost prevent gasLimit Race Condition
  src/modules/core/sagas/transactions/estimateGasCost.ts
Labels: P1, bug

#2608 Wire up removing addresses and fetching whitelisted users
  src/data/cache.ts
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/extensions.ts
  src/i18n/en.json
  src/modules/dashboard/components/Whitelist/Whitelist.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistAddresses.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/WhitelistMembersListExtraContent.tsx
  src/modules/dashboard/sagas/extensions.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colony.ts
Labels: feature

#2605 Prevent Dapp Use if Wrong Network
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHome/WrongNetworkDialog/WrongNetworkDialog.css
  src/modules/dashboard/components/ColonyHome/WrongNetworkDialog/WrongNetworkDialog.css.d.ts
  src/modules/dashboard/components/ColonyHome/WrongNetworkDialog/WrongNetworkDialog.tsx
  src/modules/dashboard/components/ColonyHome/WrongNetworkDialog/index.ts
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/pages/components/LandingPage/LandingPage.tsx
Labels: feature

#2607 Add download template
  src/modules/core/components/ExternalLink/ExternalLink.tsx
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/DownloadTemplate.css
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/DownloadTemplate.css.d.ts
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/DownloadTemplate.tsx
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/UploadAddressesWidget.css
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/UploadAddressesWidget.css.d.ts
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/UploadAddressesWidget.tsx
Labels: feature

#2610 Update slider error message logic
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
Labels: bug

#2596 Add agreement dialog
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/index.ts
  src/data/resolvers/whitelist.ts
  src/data/staticData/extensionData.ts
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/dashboard/components/Whitelist/AgreementDialog/AgreementDialog.css
  src/modules/dashboard/components/Whitelist/AgreementDialog/AgreementDialog.css.d.ts
  src/modules/dashboard/components/Whitelist/AgreementDialog/AgreementDialog.tsx
  src/modules/dashboard/components/Whitelist/AgreementDialog/index.ts
  src/modules/dashboard/components/Whitelist/Whitelist.css
  src/modules/dashboard/components/Whitelist/Whitelist.css.d.ts
  src/modules/dashboard/components/Whitelist/Whitelist.tsx
  static/.DS_Store
Labels: feature

#2597 Add CSV uploader functionality
  package-lock.json
  package.json
  src/modules/core/components/CSVUploader/CSVUploader.tsx
  src/modules/core/components/CSVUploader/CSVUploaderItem.css
  src/modules/core/components/CSVUploader/CSVUploaderItem.css.d.ts
  src/modules/core/components/CSVUploader/CSVUploaderItem.tsx
  src/modules/core/components/CSVUploader/index.tsx
  src/modules/core/components/Fields/InputStatus/InputStatus.css
  src/modules/core/components/Fields/InputStatus/InputStatus.css.d.ts
  src/modules/core/components/Fields/InputStatus/InputStatus.tsx
  src/modules/core/components/Fields/InputStatus/index.ts
  src/modules/core/components/FileUpload/FileUpload.tsx
  src/modules/core/components/FileUpload/types.ts
  src/modules/core/components/Preloaders/SpinnerLoader.css
  src/modules/core/components/Preloaders/SpinnerLoader.css.d.ts
  src/modules/core/components/Preloaders/SpinnerLoader.tsx
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/UploadAddressesWidget.tsx
Labels: feature

#2612 Move extensions sagas to separate files
  src/modules/dashboard/sagas/extensions.ts
  src/modules/dashboard/sagas/extensions/colonyExtensionDeprecate.ts
  src/modules/dashboard/sagas/extensions/colonyExtensionEnable.ts
  src/modules/dashboard/sagas/extensions/colonyExtensionInstall.ts
  src/modules/dashboard/sagas/extensions/colonyExtensionUninstall.ts
  src/modules/dashboard/sagas/extensions/colonyExtensionUpgrade.ts
  src/modules/dashboard/sagas/extensions/index.ts
  src/modules/dashboard/sagas/extensions/updateWhitelist.ts
  src/modules/dashboard/sagas/motions/claimMotionRewards.ts
  src/modules/dashboard/sagas/motions/escalateMotion.ts
  src/modules/dashboard/sagas/motions/finalizeMotion.ts
  src/modules/dashboard/sagas/motions/revealVoteMotion.ts
  src/modules/dashboard/sagas/motions/stakeMotion.ts
  src/modules/dashboard/sagas/motions/updateState.ts
  src/modules/dashboard/sagas/motions/voteMotion.ts
  src/modules/dashboard/sagas/utils/index.ts
  src/modules/dashboard/sagas/utils/refreshExtension.ts
Labels: maintenance

#2615 Properly estimate "Create Token" and "Deploy Token Authority" transactions when creating a new Colony
  package-lock.json
  package.json
  src/modules/dashboard/sagas/index.ts
  src/modules/dashboard/sagas/token.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/index.ts
  src/redux/types/actions/token.ts
Labels: bug

#2445 Coin Machine Buy Tokens Widget
  codegen.yml
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/queries/coinMachine.graphql
  src/data/graphql/typeDefs.ts
  src/data/graphql/typeDefs/coinMachine.ts
  src/data/index.ts
  src/data/resolvers/coinMachine.ts
  src/data/staticData/extensionData.ts
  src/i18n/en.json
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.tsx
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/core/sagas/transactions/estimateGasCost.ts
  src/modules/core/sagas/transactions/sendTransaction.ts
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.css
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.css.d.ts
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.tsx
  src/modules/dashboard/components/CoinMachine/BuyTokens/index.ts
  src/modules/dashboard/components/CoinMachine/Chat/Chat.css
  src/modules/dashboard/components/CoinMachine/CoinMachine.css
  src/modules/dashboard/components/CoinMachine/CoinMachine.tsx
  src/modules/dashboard/components/CoinMachine/SaleStateWidget/SaleStateWidget.tsx
  src/modules/dashboard/components/ColonyHome/ColonyUpgrade/ColonyUpgrade.tsx
  src/modules/dashboard/components/CreateColonyWizard/StepCreateToken.tsx
  src/modules/dashboard/components/CreateColonyWizard/StepTokenChoice.tsx
  src/modules/dashboard/components/CreateColonyWizard/TokenSelector.tsx
  src/modules/dashboard/components/UnlockTokenDialog/UnlockTokenForm.tsx
  src/modules/dashboard/sagas/coinMachine/buyTokens.ts
  src/modules/dashboard/sagas/coinMachine/index.ts
  src/modules/dashboard/sagas/index.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/coinMachine.ts
  src/redux/types/actions/index.ts
Labels: feature

#2623 Fix: update force toggle condition in the `Permissions` modal
  src/modules/dashboard/components/PermissionManagementDialog/PermissionManagementForm.tsx
Labels: bug

#2628 Fix motion feed comment box margin
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
Labels: bug

#2620 Add TokenSalesTable component
  src/modules/core/components/Table/TableHeader/TableHeader.tsx
  src/modules/dashboard/components/CoinMachine/CoinMachine.css
  src/modules/dashboard/components/CoinMachine/CoinMachine.tsx
  src/modules/dashboard/components/CoinMachine/TokenPriceStatusIcon/TokenPriceStatusIcon.css
  src/modules/dashboard/components/CoinMachine/TokenPriceStatusIcon/TokenPriceStatusIcon.css.d.ts
  src/modules/dashboard/components/CoinMachine/TokenPriceStatusIcon/TokenPriceStatusIcon.tsx
  src/modules/dashboard/components/CoinMachine/TokenPriceStatusIcon/index.ts
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.css
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.css.d.ts
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/TokenSalesTable.tsx
  src/modules/dashboard/components/CoinMachine/TokenSalesTable/index.ts
Labels: feature

#2621 Add `BuyWidget` non-sale state
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.css
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.css.d.ts
  src/modules/dashboard/components/CoinMachine/BuyTokens/BuyTokens.tsx
Labels: feature
