Repository JoinColony/colonyDapp, pull requests merged in 2022-10, with the labels that each got.

#3925 Prevent jumping of UI when displaying the transaction fee
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.css
Labels: bug

#3882 Date Picker Core Component
  package-lock.json
  package.json
  patches/@floating-ui+core+1.0.1.patch
  src/img/icons.json
  src/img/icons/clock.svg
  src/modules/core/components/DatePicker/CaptionElement.css
  src/modules/core/components/DatePicker/CaptionElement.css.d.ts
  src/modules/core/components/DatePicker/CaptionElement.tsx
  src/modules/core/components/DatePicker/DatePicker.css
  src/modules/core/components/DatePicker/DatePicker.css.d.ts
  src/modules/core/components/DatePicker/DatePicker.md
  src/modules/core/components/DatePicker/DatePicker.tsx
  src/modules/core/components/DatePicker/DatePickerContent.css
  src/modules/core/components/DatePicker/DatePickerContent.css.d.ts
  src/modules/core/components/DatePicker/DatePickerContent.tsx
  src/modules/core/components/DatePicker/InputField.tsx
  src/modules/core/components/DatePicker/NavbarElement.css
  src/modules/core/components/DatePicker/NavbarElement.css.d.ts
  src/modules/core/components/DatePicker/NavbarElement.tsx
  src/modules/core/components/DatePicker/index.ts
  src/modules/core/components/DatePicker/keyTypes.ts
  src/modules/core/components/Fields/DatePicker/DatePicker.css
  src/modules/core/components/Fields/DatePicker/DatePicker.css.d.ts
  src/modules/core/components/Fields/DatePicker/DatePicker.tsx
  src/modules/core/components/Fields/DatePicker/TimePicker.tsx
  src/modules/core/components/Fields/DatePicker/constants.ts
  src/modules/core/components/Fields/DatePicker/index.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureStreamingForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/constants.ts
  webpack.base.js
Labels: feature

#3929 Fix: Avatar uploader gets stuck
  src/modules/core/components/AvatarUploader/AvatarUploadItem.tsx
  src/modules/users/components/UserProfileEdit/UserAvatarUploader.css
  src/modules/users/components/UserProfileEdit/UserAvatarUploader.css.d.ts
  src/modules/users/components/UserProfileEdit/UserAvatarUploader.tsx
Labels: bug

#3939 Decisions: Editor Dialog not disabled
  src/modules/core/components/RichTextEditor/RichTextEditor.tsx
Labels: bug

#3941 Remove `"dev": true` from `package-lock.json`
  package-lock.json
Labels: maintenance

#3885 Add failed motion
  src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.css
  src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/LockedStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3912 Fix error in contract parser ABI text area
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/validation.ts
  src/utils/safes/getContractUsefulMethods.ts
  src/utils/safes/index.ts
Labels: bug

#3868 Add contract interaction to preview dialog
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/DetailsItem/DetailsItem.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.tsx
  src/utils/safes/contractParserValidation.ts
  src/utils/safes/index.ts
Labels: feature

#3949 Disable `Reveal` button in voting widget when the user didn't vote
  src/data/resolvers/motions.ts
Labels: bug

#3905 Fix "Address format is wrong" displayed next to the SafePicker
  src/modules/core/components/SingleUserPicker/SingleUserPicker.tsx
Labels: bug

#3871 Connect "Transfer funds" transaction
  .env.example
  src/data/index.ts
  src/modules/constants.ts
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/core/components/Fields/Select/types.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/AmountBalances/AmountBalances.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/AmountBalances/index.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/RawTransactionSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferFundsSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferNFTSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/index.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/validation.ts
  src/modules/dashboard/components/HookedTokenIcon/HookedTokenIcon.tsx
  src/modules/dashboard/sagas/actions/initiateSafeTransaction.ts
  src/modules/dashboard/sagas/utils/safeHelpers.ts
  src/redux/types/actions/colonyActions.ts
  src/types/index.ts
Labels: feature

#3886 Feature/cancel modal
  src/modules/dashboard/components/Dialogs/CancelStreamingDialog/CancelStreamingDialog.css
  src/modules/dashboard/components/Dialogs/CancelStreamingDialog/CancelStreamingDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/CancelStreamingDialog/CancelStreamingDialog.tsx
  src/modules/dashboard/components/Dialogs/CancelStreamingDialog/CancelStreamingForm.tsx
  src/modules/dashboard/components/Dialogs/CancelStreamingDialog/FundingSourceItem.tsx
  src/modules/dashboard/components/Dialogs/CancelStreamingDialog/index.ts
  src/modules/dashboard/components/Dialogs/CancelStreamingDialog/types.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStages.tsx
Labels: feature

#3953 Disable finalize button during escalation
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
Labels: bug

#3954 Upgrade voting & reveal widgets
  src/modules/dashboard/components/ActionsPage/RevealWidget/RevealWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.css
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
Labels: feature

#3867 feat: locked streaming
  src/modules/dashboard/components/ExpenditurePage/Streaming/LockedStreaming.css
  src/modules/dashboard/components/ExpenditurePage/Streaming/LockedStreaming.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/LockedStreaming.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
Labels: feature

#3952 Improve validation for same param names
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
Labels: bug

#3951 Scroll to the currently checked option in Select component
  src/modules/core/components/Fields/SelectOption/SelectOption.tsx
Labels: feature

#3889 Add stream with no funds to claim
  src/modules/dashboard/components/ExpenditurePage/Stages/LockedStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.css
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/hooks.ts
Labels: feature

#3975 Fix: GasStationPopover causing horizontal overflow
  src/modules/users/components/GasStation/GasStationPopover.css
  src/modules/users/components/GasStation/GasStationPopover.css.d.ts
  src/modules/users/components/GasStation/GasStationPopover.tsx
Labels: bug

#3987 Update draft decision localStorage logic
  src/modules/dashboard/components/ColonyNewDecision/ColonyNewDecision.tsx
  src/modules/dashboard/components/Dialogs/DecisionDialog/DecisionDialog.tsx
Labels: bug

#3985 Decisions: Handle Decisions heading formatting in preview & staking pages
  src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/ActionPageDecisionWithIPFS.css
  src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/ActionPageDecisionWithIPFS.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/ActionPageDecisionWithIPFS.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css.d.ts
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.css
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.css.d.ts
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.tsx
Labels: bug

#3984 Remove unused Gnosis Safe libraries and env variables
  .env.example
  package-lock.json
  package.json
  src/utils/safes/getContractUsefulMethods.ts
Labels: maintenance

#3937 Connect "Contract interaction" transaction
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
  src/modules/dashboard/sagas/actions/initiateSafeTransaction.ts
  src/modules/dashboard/sagas/utils/safeHelpers.ts
Labels: feature

#3999 Handle long strings in SingleUserPicker
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css
Labels: bug

#3963 Add validation schema in streaming payment
  src/modules/core/components/Fields/DatePicker/DatePicker.css
  src/modules/core/components/Fields/DatePicker/DatePicker.css.d.ts
  src/modules/core/components/Fields/DatePicker/DatePicker.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureStreamingForm.tsx
  src/modules/dashboard/components/ExpenditurePage/Streaming/FundingSource/FundingSource.tsx
  src/modules/dashboard/components/ExpenditurePage/Streaming/Limit/Limit.tsx
  src/modules/dashboard/components/ExpenditurePage/Streaming/Rate/Rate.tsx
  src/modules/dashboard/components/ExpenditurePage/Streaming/Rate/index.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/RateItem/RateItem.css
  src/modules/dashboard/components/ExpenditurePage/Streaming/RateItem/RateItem.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/RateItem/RateItem.tsx
  src/modules/dashboard/components/ExpenditurePage/Streaming/RateItem/index.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/types.ts
  src/modules/pages/components/ExpenditurePage/constants.ts
Labels: feature

#3950 Display contract name in control safe dialog
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
  src/utils/safes/getContractUsefulMethods.ts
  src/utils/safes/index.ts
Labels: feature

#3983 Fix `ProgressBar` threshold in `DefaultMotion`
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
Labels: bug

#4012 Integrate motion components with Control Safe dialog
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/validation.ts
Labels: feature

#4006 Handle nested arrays in Contract Interaction validation
  src/utils/safes/contractParserValidation.ts
Labels: bug

#4019 Fix mobile menu not opening in production
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
  src/modules/users/components/HamburgerDropdown/HamburgerDropdown.tsx
  src/modules/users/components/HamburgerDropdown/HamburgerDropdownPopover.tsx
Labels: bug

#4016 Fix: Input max button buggy behaviour when clicked twice
  src/modules/core/components/Fields/Input/InputComponent.tsx
Labels: bug

#3997 Add claim in Split, Staged and Batch payments
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.css
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFundsOther.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFundsRecipients.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimTokens/ClaimTokens.css
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimTokens/ClaimTokens.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimTokens/ClaimTokens.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimTokens/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/types.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/utils.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/FormStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/LockedStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StagesButton/StagesButton.css
  src/modules/dashboard/components/ExpenditurePage/Stages/StagesButton/StagesButton.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StagesButton/StagesButton.tsx
  src/modules/dashboard/components/ExpenditurePage/hooks.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3805 Add edits in locked state in split payment
  src/modules/core/components/UserPickerWithSearch/UserPickerWithSearch.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangeHeader/ChangeHeader.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangeHeader/ChangeHeader.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangeHeader/ChangeHeader.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangeHeader/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeHeader/ChangeHeader.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeItem/ChangeItem.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangedMultiple.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedSplit.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedSplit.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedSplit.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/utils.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedValues/ChangedValues.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedValues/ChangedValues.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialog.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewRecipient/NewRecipient.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewValue/NewValue.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewValue/NewValue.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/types.ts
  src/modules/dashboard/components/ExpenditurePage/Split/LockedSplit.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/Split.css
  src/modules/dashboard/components/ExpenditurePage/Split/Split.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Split/types.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
  src/modules/pages/components/ExpenditurePage/utils.ts
Labels: feature

#3948 Add edit in batch payment
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangeItem/ChangeItem.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangeItem/ChangeItem.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangeItem/ChangeItem.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangeItem/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedAdvanced/ChangedAdvanced.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedAdvanced/ChangedAdvanced.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedAdvanced/ChangedAdvanced.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedAdvanced/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedBatch/ChangedBatch.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedBatch/ChangedBatch.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedBatch/ChangedBatch.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedBatch/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedBatch/utils.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedRecipient/ChangedRecipient.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedSplit/ChangedSplit.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedStaged/ChangedMilestone/ChangedMilestone.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedStaged/ChangedStaged.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewValue/NewValue.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewValue/NewValue.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewValue/NewValue.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/Batch.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploaderItem.css
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploaderItem.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploaderItem.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.css
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/PreviewDialog.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/hooks.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/types.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/utils.ts
  src/modules/dashboard/components/ExpenditurePage/EditButtons/EditButtons.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/ClaimTag/ClaimTag.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/LockedPayments.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/LockedSplit.tsx
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/FormStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/LockedStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StagesButton/StagesButton.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
  src/modules/pages/components/ExpenditurePage/types.ts
  src/modules/pages/components/ExpenditurePage/utils.ts
Labels: feature

#4017 Fix: Many colonies overlap Add New button
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.css
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.css.d.ts
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.tsx
Labels: bug

#4021 Fix selectedContractMethods when deleting a tab
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
Labels: bug

#4025 Fix Motions Query/Subscription `args` local resolver
  src/data/generated.ts
  src/data/graphql/typeDefsSubscriptions.ts
  src/data/resolvers/motions.ts
  src/modules/dashboard/components/ColonyHome/ColonyNavigation/ColonyNavigation.tsx
  src/modules/dashboard/transformers/transformers.ts
  src/utils/events/index.ts
Labels: bug

#4026 Handle long strings in `Select` component
  src/modules/core/components/Fields/Select/Select.css
  src/modules/core/components/Fields/Select/SelectListBox.css
  src/modules/core/components/Fields/Select/SelectListBox.css.d.ts
  src/modules/core/components/Fields/Select/SelectListBox.tsx
  src/modules/core/components/Fields/Select/types.ts
  src/modules/core/components/Fields/SelectOption/SelectOption.css
  src/modules/core/components/Fields/SelectOption/SelectOption.css.d.ts
  src/modules/core/components/Fields/SelectOption/SelectOption.tsx
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.tsx
  src/modules/dashboard/components/ColonyEvents/ColonyEvents.tsx
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/Members/MembersTitle.tsx
Labels: bug
