Repository JoinColony/colonyDapp, pull requests merged in 2022-06, with the labels that each got.

#3399 Search bar UI & functionality added to members page
  src/modules/dashboard/components/Members/Members.css
  src/modules/dashboard/components/Members/Members.css.d.ts
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/dashboard/components/Members/MembersSection.css
  src/modules/dashboard/components/Members/MembersSection.css.d.ts
  src/modules/dashboard/components/Members/MembersSection.tsx
  src/modules/dashboard/components/Members/MembersTitle.css
  src/modules/dashboard/components/Members/MembersTitle.css.d.ts
  src/modules/dashboard/components/Members/MembersTitle.tsx
  src/modules/dashboard/components/Members/filterMembers.ts
  src/modules/dashboard/components/Members/index.ts
Labels: feature

#3412 Better motion page UX
  src/App.tsx
  src/img/icons.json
  src/img/icons/share.svg
  src/modules/core/components/Button/index.ts
  src/modules/core/components/ClipboardCopy/ClipboardCopy.tsx
  src/modules/dashboard/components/ActionsPage/StakeRequiredBanner/StakeRequiredBanner.css
  src/modules/dashboard/components/ActionsPage/StakeRequiredBanner/StakeRequiredBanner.tsx
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.css
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.css.d.ts
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/users/components/TokenActivation/TokenActivationPopover.tsx
  src/modules/users/components/TokenActivationProvider/TokenActivationProvider.tsx
  src/modules/users/components/TokenActivationProvider/index.ts
  src/types/index.ts
Labels: feature

#3431 Update font size in Expenditure Settings section
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css
Labels: bug

#3414 Add title and description of expenditure
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.css
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.tsx
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/index.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.css
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3440 Remove default grouped transactions count from TransactionStatus
  src/modules/users/components/GasStation/TransactionCard/TransactionStatus.tsx
Labels: bug

#3439 [verified recipients] Notification dot alignment
  src/modules/pages/components/RouteLayouts/UserNavigation.css
Labels: bug

#3437 Fix Border on Clickable User Avatar
  src/modules/core/components/ActionsList/ActionsListItem.css
  src/modules/core/components/UserAvatar/UserAvatar.css
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css
  src/modules/users/components/AvatarDropdown/AvatarDropdown.css
Labels: bug

#3453 Add error message when fewer than 3 characters
  src/modules/core/components/Comment/Input/CommentInput.css
  src/modules/core/components/Comment/Input/CommentInput.css.d.ts
  src/modules/core/components/Comment/Input/CommentInput.tsx
Labels: bug

#3455 Fix error message overflow
  src/modules/users/components/GasStation/TransactionCard/GroupedTransactionCard.css
Labels: bug

#3458 Fix Numeral default size
  src/modules/core/components/Numeral/Numeral.css
Labels: bug

#3464 Update the way manage whitelist dialog refreshes
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
Labels: bug

#3460 Address book tx redirects
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialogForm.tsx
  src/modules/dashboard/sagas/whitelist/manageVerifiedRecipients.ts
  src/redux/types/actions/colony.ts
Labels: bug

#3443 Allow overflow of `ManageWhitelistDialog`
  src/modules/core/components/Dialog/Dialog.css
  src/modules/core/components/Dialog/Dialog.css.d.ts
  src/modules/core/components/Dialog/Dialog.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialog.tsx
Labels: bug

#3469 Address Book filter on UserPicker is disabled if there are no addresses
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialog.tsx
Labels: bug

#3470 Fix/3461-magnify-icon
  src/modules/dashboard/components/Members/MembersTitle.css
Labels: bug

#3472 Fix: include @ symbol in user search
  src/modules/core/components/SingleUserPicker/utils.ts
Labels: bug

#3457 Rename Motions and Disputes Extension
  src/data/staticData/extensionData.tsx
  src/utils/hooks/useTitle.ts
Labels: feature

#3364 Update Incoming Funds section
  src/modules/dashboard/components/ColonyEvents/ColonyEvents.tsx
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.css
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.css
  src/modules/dashboard/components/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.tsx
  src/modules/dashboard/components/ColonyHome/ColonyUnclaimedTransfers/index.ts
  src/modules/dashboard/components/TokenCard/TokenCard.css
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfers.css
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfersItem.css
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfersItem.css.d.ts
  src/modules/dashboard/components/UnclaimedTransfers/UnclaimedTransfersItem.tsx
Labels: feature

#3514 Update `contributorsAndWatchers` query resolver to fix members with reputation list
  src/data/resolvers/colony.ts
Labels: bug

#3467 Add Gnosis Safe Control related UAC items
  src/img/icons.json
  src/img/icons/gnosis-logo.svg
  src/img/icons/joystick.svg
  src/img/icons/plus-heavy.svg
  src/img/icons/trash-can.svg
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/Dialogs/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageFundsDialog/ManageFundsDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageGnosisSafeDialog/ManageGnosisSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageGnosisSafeDialog/index.ts
Labels: feature

#3485 Make colony home page mobile responsive
  package.json
  src/modules/core/components/ActionsList/ActionsListItem.css
  src/modules/core/components/ActionsList/ActionsListItem.css.d.ts
  src/modules/core/components/Dialog/Dialog.css
  src/modules/core/components/Dialog/Dialog.css.d.ts
  src/modules/core/components/HamburgerMenu/HamburgerMenu.css
  src/modules/core/components/HamburgerMenu/HamburgerMenu.css.d.ts
  src/modules/core/components/HamburgerMenu/HamburgerMenu.tsx
  src/modules/core/components/MaskedAddress/MaskedAddress.css
  src/modules/core/components/MaskedAddress/MaskedAddress.css.d.ts
  src/modules/core/components/Popover/PopoverWrapper.tsx
  src/modules/core/components/UserAvatar/UserAvatar.css
  src/modules/core/components/UserAvatar/UserAvatar.css.d.ts
  src/modules/dashboard/components/ColonyActions/ColonyActions.css
  src/modules/dashboard/components/ColonyActions/ColonyActions.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.css
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.tsx
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscriptionInfoPopover.css
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscriptionInfoPopover.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscriptionInfoPopover.tsx
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.tsx
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitleHeading.tsx
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitleMenu.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css.d.ts
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFundsManageFunds.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFundsPopover.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFundsSelectedToken.tsx
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.css
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.css.d.ts
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.tsx
  src/modules/pages/components/RouteLayouts/Default/Default.css
  src/modules/pages/components/RouteLayouts/Default/Default.css.d.ts
  src/modules/pages/components/RouteLayouts/Default/Default.tsx
  src/modules/pages/components/RouteLayouts/SimpleNav/SimpleNav.css
  src/modules/pages/components/RouteLayouts/SimpleNav/SimpleNav.css.d.ts
  src/modules/pages/components/RouteLayouts/SimpleNav/SimpleNav.tsx
  src/modules/pages/components/RouteLayouts/UserNavigation.css
  src/modules/pages/components/RouteLayouts/UserNavigation.css.d.ts
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
  src/modules/users/components/AvatarDropdown/AvatarDropdown.css
  src/modules/users/components/AvatarDropdown/AvatarDropdown.css.d.ts
  src/modules/users/components/AvatarDropdown/AvatarDropdown.tsx
  src/modules/users/components/ConnectWalletWizard/ConnectWalletPopover/ConnectWalletPopover.tsx
  src/modules/users/components/ConnectWalletWizard/ConnectWalletPopover/WalletPopoverTemplate.css
  src/modules/users/components/ConnectWalletWizard/ConnectWalletPopover/WalletPopoverTemplate.css.d.ts
  src/modules/users/components/ConnectWalletWizard/StepStart/StepStart.css
  src/modules/users/components/ConnectWalletWizard/StepStart/StepStart.css.d.ts
  src/styles/shared/queries.css
  src/styles/shared/queries.css.d.ts
  src/utils/css/index.ts
Labels: feature

#3523 Add control safe dialog
  src/modules/core/components/Button/AddItemButton.css
  src/modules/core/components/Button/AddItemButton.css.d.ts
  src/modules/core/components/Button/AddItemButton.tsx
  src/modules/core/components/Button/index.ts
  src/modules/core/components/SingleUserPicker/SingleSafePicker.tsx
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css
  src/modules/core/components/SingleUserPicker/SingleUserPicker.css.d.ts
  src/modules/core/components/SingleUserPicker/SingleUserPicker.tsx
  src/modules/core/components/SingleUserPicker/index.ts
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/index.ts
  src/modules/externalUrls.ts
Labels: feature

#3496 Add Remove Safe Dialog
  src/modules/core/components/Fields/Checkbox/Checkbox.css
  src/modules/core/components/Fields/Checkbox/Checkbox.css.d.ts
  src/modules/core/components/Fields/Checkbox/Checkbox.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/RemoveSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.css
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.css.d.ts
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.tsx
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/SafeListItem.css
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/SafeListItem.css.d.ts
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/SafeListItem.tsx
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/index.ts
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/types.ts
Labels: feature

#3407 Add multiple recipients on the expenditure creation page
  src/img/icons.json
  src/img/icons/collapse.svg
  src/img/icons/expand.svg
  src/img/icons/plus-circle.svg
  src/modules/core/components/OmniPicker/AdditionalOmniPicker.tsx
  src/modules/core/components/OmniPicker/types.ts
  src/modules/core/components/OmniPicker/withAdditionalOmniPicker.ts
  src/modules/core/components/UserPickerWithSearch/Dropdown.css
  src/modules/core/components/UserPickerWithSearch/Dropdown.css.d.ts
  src/modules/core/components/UserPickerWithSearch/Dropdown.tsx
  src/modules/core/components/UserPickerWithSearch/UserPickerWithSearch.css
  src/modules/core/components/UserPickerWithSearch/UserPickerWithSearch.css.d.ts
  src/modules/core/components/UserPickerWithSearch/UserPickerWithSearch.tsx
  src/modules/core/components/UserPickerWithSearch/index.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.css
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/index.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/types.d.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.css
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/index.ts
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.css
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.css
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.css.d.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/RouteLayouts/NavBar/NavBar.tsx
  src/modules/pages/components/RouteLayouts/NavBar/WrappedNavBar.css
  src/modules/pages/components/RouteLayouts/NavBar/WrappedNavBar.css.d.ts
  src/modules/pages/components/RouteLayouts/NavBar/WrappedNavBar.tsx
  src/modules/pages/components/RouteLayouts/index.ts
  src/routes/Routes.tsx
Labels: feature

#3540 Improve UX of `MemberInfoPopover`
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.tsx
  src/modules/core/components/InfoPopover/MemberInfoPopover/UserReputation.tsx
Labels: bug

#3554 Feat: Remove BetaCautionAlert
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.css
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.css.d.ts
  src/modules/core/components/BetaCautionAlert/BetaCautionAlert.tsx
  src/modules/core/components/BetaCautionAlert/index.ts
  src/routes/AlwaysAccesibleRoute.tsx
  src/routes/WalletRequiredRoute.tsx
Labels: feature, good-first-issue

#3410 Add submit to draft option
  src/i18n/en.json
  src/img/icons.json
  src/img/icons/share.svg
  src/modules/dashboard/components/Dialogs/StakeExpenditureDialog/StakeExpenditureDialog.css
  src/modules/dashboard/components/Dialogs/StakeExpenditureDialog/StakeExpenditureDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/StakeExpenditureDialog/StakeExpenditureDialog.tsx
  src/modules/dashboard/components/Dialogs/StakeExpenditureDialog/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StageItem.css
  src/modules/dashboard/components/ExpenditurePage/Stages/StageItem.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StageItem.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/index.ts
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.css
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.css
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3529 Add: Joined Colony List
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesDropdown.tsx
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.css
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.css.d.ts
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.tsx
  src/modules/pages/components/RouteLayouts/Default/Default.tsx
Labels: feature

#3530 Add: Mobile responsive Members page
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.css
  src/modules/core/components/InfoPopover/MemberInfoPopover/MemberInfoPopover.css.d.ts
  src/modules/core/components/MembersList/Actions/MemberActions.css
  src/modules/core/components/MembersList/Actions/MemberActions.css.d.ts
  src/modules/core/components/MembersList/Actions/MemberActions.tsx
  src/modules/core/components/MembersList/Actions/MemberActionsPopover.css
  src/modules/core/components/MembersList/Actions/MemberActionsPopover.css.d.ts
  src/modules/core/components/MembersList/MembersListItem.css
  src/modules/core/components/MembersList/MembersListItem.css.d.ts
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/core/components/MembersList/SortingRow/SortingRow.css
  src/modules/core/components/MembersList/SortingRow/SortingRow.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyHomeInfo.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.css.d.ts
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/Members/Members.css
  src/modules/dashboard/components/Members/Members.css.d.ts
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/dashboard/components/Members/MembersSection.css
  src/modules/dashboard/components/Members/MembersSection.css.d.ts
  src/modules/dashboard/components/Members/MembersTitle.css
  src/modules/dashboard/components/Members/MembersTitle.css.d.ts
  src/modules/dashboard/components/Members/MembersTitle.tsx
  src/modules/pages/components/RouteLayouts/Default/Default.css
  src/modules/pages/components/RouteLayouts/Default/Default.tsx
  src/routes/Routes.tsx
Labels: feature
