Repository JoinColony/colonyDapp, pull requests merged in 2022-07, with the labels that each got.

#3542 Add "Transfer Funds" interaction variation
  src/modules/core/components/Fields/AmountTokens/AmountTokens.css
  src/modules/core/components/Fields/AmountTokens/AmountTokens.css.d.ts
  src/modules/core/components/Fields/AmountTokens/AmountTokens.tsx
  src/modules/core/components/Fields/AmountTokens/index.ts
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialog.tsx
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.css
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.css.d.ts
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransferFundsSection.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransferFundsSection.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransferFundsSection.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/index.ts
Labels: feature

#3500 Add ability to lock values
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.tsx
Labels: feature

#3493 Add Existing Gnosis Safe (UI only)
  src/modules/constants.ts
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.css
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.css.d.ts
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.tsx
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/index.ts
Labels: feature

#3561 Add UI to remove expenditure draft
  src/modules/dashboard/components/Dialogs/DeleteDraftDialog/DeleteDraftDialog.css
  src/modules/dashboard/components/Dialogs/DeleteDraftDialog/DeleteDraftDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/DeleteDraftDialog/DeleteDraftDialog.tsx
  src/modules/dashboard/components/Dialogs/StakeExpenditureDialog/StakeExpenditureDialog.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/consts.ts
Labels: feature

#3538 Add: Mobile responsive Funds page
  src/modules/core/components/MaskedAddress/MaskedAddress.css
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.css
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.css.d.ts
  src/modules/dashboard/components/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/ColonyFundingBanner/ColonyFundingBanner.css
  src/modules/dashboard/components/ColonyFundingBanner/ColonyFundingBanner.css.d.ts
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.css
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.css.d.ts
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/routes/Routes.tsx
Labels: feature

#3549 Add: Mobile Responsive Extensions Home Page
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.css
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.css
  src/modules/dashboard/components/Extensions/ExtensionCard.css
  src/modules/dashboard/components/Extensions/ExtensionCard.css.d.ts
  src/modules/dashboard/components/Extensions/Extensions.css
  src/modules/dashboard/components/Extensions/Extensions.css.d.ts
Labels: feature

#3562 Add "Raw transaction" interaction variation
  src/modules/core/components/Fields/Input/Input.tsx
  src/modules/core/components/Fields/InputLabel/InputLabel.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/RawTransactionSection.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransferFundsSection.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/index.ts
Labels: feature

#3570 Add "Contract interaction" transaction variation
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/core/components/Fields/Select/__tests__/__snapshots__/Select.test.tsx.snap
  src/modules/core/components/Fields/Textarea/Textarea.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/index.ts
Labels: feature

#3534 Refactor and add filters to members page
  src/modules/core/components/MembersList/MembersListItem.css
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/ColonyMembers/MemberControls/MemberControls.tsx
  src/modules/dashboard/components/ColonyMembers/MemberControls/index.ts
  src/modules/dashboard/components/ColonyMembers/MembersFilter/MembersFilter.css
  src/modules/dashboard/components/ColonyMembers/MembersFilter/MembersFilter.css.d.ts
  src/modules/dashboard/components/ColonyMembers/MembersFilter/MembersFilter.tsx
  src/modules/dashboard/components/ColonyMembers/MembersFilter/index.ts
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/dashboard/components/Members/MembersTitle.css
  src/modules/dashboard/components/Members/filterMembers.ts
Labels: feature

#3592 Update tooltip positioning for `MembersListItem`
  src/modules/core/components/MembersList/MembersListItem.css
Labels: bug

#3555 Add provider caching for domain balances
  src/modules/core/sagas/utils/extendedJsonRpcProvider.ts
Labels: maintenance

#3607 Add multi-transaction functionality to Gnosis Safe Control dialog
  src/modules/core/components/Fields/AmountTokens/AmountTokens.css
  src/modules/core/components/Fields/AmountTokens/AmountTokens.css.d.ts
  src/modules/core/components/Fields/AmountTokens/AmountTokens.tsx
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/core/components/Fields/Input/index.ts
  src/modules/core/components/IconTooltip/IconTooltip.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/RawTransactionSection.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/TransferFundsSection.tsx
Labels: feature

#3473 Add locked values
  src/modules/core/components/UserPickerWithSearch/UserPickerWithSearch.css
  src/modules/core/components/UserPickerWithSearch/UserPickerWithSearch.css.d.ts
  src/modules/core/components/UserPickerWithSearch/UserPickerWithSearch.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/BalanceSelect.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/LockedExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/constants.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/index.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/CollapseExpandButtons.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/LockedPayments.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.css
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/index.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/types.d.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient.css
  src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/consts.ts
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/LockedTitleDescriptionSection.tsx
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.css
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.tsx
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/index.ts
  src/modules/dashboard/components/ExpenditurePage/utils.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureTemplate.css.d.ts
Labels: feature

#3627 Introduce `ExtendedJsonRpcProvider` proper caching bypass
  src/modules/core/sagas/utils/extendedJsonRpcProvider.ts
Labels: maintenance

#3628 Add missing Metatransactions Gas Station Annotation Message Descriptor
  src/i18n/en.json
Labels: maintenance

#3631 Fix Broadcaster Human Readable Error Generator
  src/modules/core/sagas/utils/errorMessages.ts
Labels: maintenance

#3630 Ensure Gas Prices is at least 2 GWEI when on Gnosis Chain
  src/modules/core/sagas/utils/getGasPrices.ts
Labels: maintenance

#3429 Add logs of the expenditure
  src/i18n/en-system-messages.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
  src/modules/dashboard/components/ActionsPageFeed/types.ts
  src/modules/dashboard/components/ExpenditurePage/LogsSection/LogsSection.css
  src/modules/dashboard/components/ExpenditurePage/LogsSection/LogsSection.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/LogsSection/LogsSection.tsx
  src/modules/dashboard/components/ExpenditurePage/LogsSection/constants.ts
  src/modules/dashboard/components/ExpenditurePage/LogsSection/index.ts
  src/modules/dashboard/components/ExpenditurePage/TitleDescriptionSection/TitleDescriptionSection.css
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.css
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.css.d.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3642 Revert form names for Colony creation & improve validation error msgs
  src/modules/dashboard/components/CreateColonyWizard/StepColonyName.tsx
Labels: bug

#3655 Fix Yet More Transactions Message Descriptors
  src/i18n/en.json
Labels: maintenance

#3656 Add gnosis transaction preview dialog
  src/modules/core/components/Fields/Form/ActionForm.tsx
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/DetailsItem/DetailsItem.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/DetailsItem/DetailsItem.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/DetailsItem/DetailsItem.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/DetailsItem/index.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/SafeTransactionPreview.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionPreview/AddressDetailsView/AddressDetailsView.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionPreview/AddressDetailsView/AddressDetailsView.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionPreview/AddressDetailsView/AddressDetailsView.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionPreview/AddressDetailsView/index.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/constants.ts
Labels: feature

#3685 Refactor: remove decimal styles from padding
  src/modules/core/components/Fields/Select/Select.css
Labels: bug, good-first-issue
