Repository JoinColony/colonyDapp, pull requests merged in 2022-09, with the labels that each got.

#3763 Connect new decision to local storage
  package-lock.json
  package.json
  src/modules/core/components/RichTextEditor/RichTextEditor.tsx
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.css
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.css.d.ts
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.tsx
  src/modules/dashboard/components/Dialogs/DecisionDialog/DecisionDialog.tsx
  src/modules/dashboard/components/Dialogs/DecisionDialog/DecisionDialogForm.tsx
  src/modules/dashboard/components/Dialogs/DecisionDialog/index.ts
Labels: feature

#3785 Connect safe picker on Control Safe dialog with colony's safes
  src/modules/core/components/SingleUserPicker/SingleSafePicker.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/index.ts
Labels: feature

#3806 Fix history in edit decision (adding missing commits from older branch)
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.tsx
  src/modules/dashboard/components/Dialogs/DecisionDialog/DecisionDialog.tsx
Labels: bug

#3794 Add empty string as ipfs hash fallback where missing
  src/modules/dashboard/sagas/actions/createDomain.ts
  src/modules/dashboard/sagas/actions/editColony.ts
  src/modules/dashboard/sagas/actions/editDomain.ts
  src/modules/dashboard/sagas/actions/enterRecovery.ts
  src/modules/dashboard/sagas/actions/managePermissions.ts
  src/modules/dashboard/sagas/actions/manageReputation.ts
  src/modules/dashboard/sagas/actions/mintTokens.ts
  src/modules/dashboard/sagas/actions/moveFunds.ts
  src/modules/dashboard/sagas/actions/payment.ts
  src/modules/dashboard/sagas/actions/unlockToken.ts
  src/modules/dashboard/sagas/actions/versionUpgrade.ts
  src/modules/dashboard/sagas/colonyCreate.ts
  src/modules/dashboard/sagas/motions/createEditDomainMotion.ts
  src/modules/dashboard/sagas/motions/editColonyMotion.ts
  src/modules/dashboard/sagas/motions/managePermissionsMotion.ts
  src/modules/dashboard/sagas/motions/manageReputationMotion.ts
  src/modules/dashboard/sagas/motions/moveFundsMotion.ts
  src/modules/dashboard/sagas/motions/paymentMotion.ts
  src/modules/dashboard/sagas/motions/rootMotion.ts
  src/modules/dashboard/sagas/motions/stakeMotion.ts
  src/modules/dashboard/sagas/utils/index.ts
  src/modules/dashboard/sagas/utils/uploadIfsWithFallback.ts
  src/modules/dashboard/sagas/whitelist/manageVerifiedRecipients.ts
  src/modules/users/sagas/user.ts
Labels: bug

#3769 Decision: Resolver & staking UI for Simple Decisions
  src/data/resolvers/motions.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/ActionPageDecisionWithIPFS.css
  src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/ActionPageDecisionWithIPFS.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/ActionPageDecisionWithIPFS.tsx
  src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/index.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/utils/colonyMotions.ts
  src/utils/events/index.ts
Labels: feature

#3826 Maintenance: Rename Gnosis Safe to Safe
  src/img/icons.json
  src/img/icons/safe-logo.svg
  src/modules/constants.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/core/components/Fields/AmountTokens/AmountTokens.tsx
  src/modules/core/components/SingleUserPicker/SingleNFTPicker.tsx
  src/modules/core/components/SingleUserPicker/SingleSafePicker.tsx
  src/modules/core/components/SingleUserPicker/SingleUserPicker.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetSafe/DetailsWidgetSafe.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.tsx
  src/modules/dashboard/components/Dialogs/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/DetailsItem/DetailsItem.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/DetailsItem/DetailsItem.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/DetailsItem/DetailsItem.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/DetailsItem/index.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionPreview/AddressDetailsView/AddressDetailsView.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionPreview/AddressDetailsView/AddressDetailsView.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionPreview/AddressDetailsView/AddressDetailsView.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionPreview/AddressDetailsView/index.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/RawTransactionSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferFundsSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferNFTSection.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferNFTSection.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferNFTSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/index.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/constants.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/index.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/index.ts
  src/modules/dashboard/components/Dialogs/ManageGnosisSafeDialog/index.ts
  src/modules/dashboard/components/Dialogs/ManageSafeDialog/ManageSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageSafeDialog/index.ts
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/SafeListItem.tsx
  src/modules/dashboard/sagas/utils/getSafeCoreSDK.ts
  src/modules/externalUrls.ts
Labels: maintenance

#3761 Create decisions objection modal
  src/modules/core/components/Comment/Comment.tsx
  src/modules/core/components/RichTextEditor/RichTextEditor.css
  src/modules/core/components/RichTextEditor/RichTextEditor.tsx
  src/modules/core/components/RichTextEditor/index.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidgetFlow.tsx
  src/modules/dashboard/components/Dialogs/RaiseObjectionDialog/RaiseObjectionDialog.tsx
  src/modules/dashboard/components/Dialogs/RaiseObjectionDialog/RaiseObjectionDialogForm.css
  src/modules/dashboard/components/Dialogs/RaiseObjectionDialog/RaiseObjectionDialogForm.css.d.ts
  src/modules/dashboard/components/Dialogs/RaiseObjectionDialog/RaiseObjectionDialogForm.tsx
Labels: feature

#3830 Fix: Colonies list height
  src/modules/pages/components/RouteLayouts/Default/Default.css
Labels: bug

#3755 Implement contract functions parser
  .env.example
  src/modules/constants.ts
  src/modules/core/components/Fields/InputStatus/InputStatus.tsx
  src/modules/core/components/Fields/Textarea/Textarea.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css.d.ts
  src/utils/getContractUsefulMethods.ts
Labels: feature

#3837 Refactor: Replace motions resolver action name strings with an enum
  src/data/resolvers/motions.ts
  src/types/colonyMotions.ts
Labels: maintenance

#3693 Add split locked
  src/modules/dashboard/components/ExpenditurePage/Split/LockedSplit.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/Split.css
  src/modules/dashboard/components/ExpenditurePage/Split/Split.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Split/Split.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/SplitEqual/SplitEqual.css
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.css
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/index.ts
  src/modules/dashboard/components/ExpenditurePage/Split/index.ts
  src/modules/dashboard/components/ExpenditurePage/Split/types.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/FormStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StagesButton/StagesButton.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
  src/modules/pages/components/ExpenditurePage/types.ts
Labels: feature

#3861 Fix: Tidy up Install Governance Extension message
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.css
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.css.d.ts
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.tsx
Labels: bug

#3823 Decisions: Connect Decisions list to query
  src/data/generated.ts
  src/data/graphql/subscriptions.graphql
  src/data/graphql/typeDefsSubscriptions.ts
  src/data/resolvers/motions.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.tsx
  src/modules/dashboard/transformers/transformers.ts
  src/types/colonyActions.ts
  src/utils/events/getAnnotationFromSubgraph.ts
Labels: feature

#3853 Add start streaming button
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialog.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/FormStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/index.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/constants.ts
  src/modules/pages/components/ExpenditurePage/types.ts
Labels: feature

#3864 Add decisions page route & its integration
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.tsx
  src/modules/dashboard/sagas/motions/createDecisionMotion.ts
  src/routes/Routes.tsx
  src/routes/routeConstants.ts
  src/utils/hooks/useTitle.ts
Labels: feature

#3840 Add a 10% stake visibility threshold on Motions page
  src/modules/core/components/ProgressBar/ProgressBar.css
  src/modules/core/components/ProgressBar/ProgressBar.css.d.ts
  src/modules/core/components/ProgressBar/ProgressBar.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingSlider.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidgetFlow.tsx
  src/modules/dashboard/components/ActionsPage/TotalStakeWidget/SingleTotalStake.tsx
  src/modules/dashboard/components/ActionsPage/TotalStakeWidget/TotalStakeWidget.css
  src/modules/dashboard/components/ActionsPage/TotalStakeWidget/TotalStakeWidget.css.d.ts
Labels: feature

#3831 Add decision draft list item and dialog to confirm decision deletion
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/core/components/ActionsList/index.ts
  src/modules/dashboard/components/ActionsPage/StakingValidationError/StakingValidationError.tsx
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.css
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.css.d.ts
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.tsx
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisionsWrapper.tsx
  src/modules/dashboard/components/ColonyDecisions/DraftDecisionItem/DraftDecisionItem.css
  src/modules/dashboard/components/ColonyDecisions/DraftDecisionItem/DraftDecisionItem.css.d.ts
  src/modules/dashboard/components/ColonyDecisions/DraftDecisionItem/DraftDecisionItem.tsx
  src/modules/dashboard/components/ColonyDecisions/DraftDecisionItem/index.ts
  src/modules/dashboard/components/ColonyDecisions/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyNewDecision/ColonyNewDecision.tsx
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.css
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.tsx
  src/modules/dashboard/components/Dialogs/ConfirmDeleteDialog/ConfirmDeleteDialog.css
  src/modules/dashboard/components/Dialogs/ConfirmDeleteDialog/ConfirmDeleteDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/ConfirmDeleteDialog/ConfirmDeleteDialog.tsx
  src/modules/dashboard/components/Dialogs/ConfirmDeleteDialog/index.ts
  src/modules/dashboard/components/Dialogs/DecisionDialog/DecisionDialog.tsx
  src/modules/dashboard/components/Dialogs/RemoveDraftDecisionDialog/RemoveDraftDecisionDialog.css
  src/modules/dashboard/components/Dialogs/RemoveDraftDecisionDialog/RemoveDraftDecisionDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/RemoveDraftDecisionDialog/RemoveDraftDecisionDialog.tsx
  src/modules/dashboard/components/Dialogs/RemoveDraftDecisionDialog/index.ts
  src/modules/dashboard/sagas/motions/createDecisionMotion.ts
  src/types/index.ts
  src/utils/colonyMotions.ts
Labels: feature

#3863 Fix Invite button misalignment
  src/modules/core/components/ClickableHeading/ClickableHeading.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyMembers/MembersSubsection.tsx
Labels: bug

#3825 Add funding source in streaming payment
  src/modules/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/FundingSource/FundingSource.css
  src/modules/dashboard/components/ExpenditurePage/Streaming/FundingSource/FundingSource.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/FundingSource/FundingSource.tsx
  src/modules/dashboard/components/ExpenditurePage/Streaming/FundingSource/index.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/Streaming.css
  src/modules/dashboard/components/ExpenditurePage/Streaming/Streaming.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/Streaming.tsx
  src/modules/dashboard/components/ExpenditurePage/Streaming/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/index.ts
  src/modules/dashboard/components/ExpenditurePage/Streaming/types.ts
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/constants.ts
  src/modules/pages/components/ExpenditurePage/types.ts
  src/modules/pages/components/ExpenditurePage/utils.ts
Labels: feature

#3681 Restructure & extract IPFS metadata
  package-lock.json
  package.json
  src/data/resolvers/colony.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItemWithIPFS/ActionsPageFeedItemWithIPFS.tsx
  src/modules/dashboard/components/HookedColonyAvatar/HookedColonyAvatar.ts
  src/modules/dashboard/hooks/useColonyMetadataChecks.ts
  src/modules/dashboard/sagas/actions/createDomain.ts
  src/modules/dashboard/sagas/actions/editColony.ts
  src/modules/dashboard/sagas/actions/editDomain.ts
  src/modules/dashboard/sagas/actions/enterRecovery.ts
  src/modules/dashboard/sagas/actions/managePermissions.ts
  src/modules/dashboard/sagas/actions/manageReputation.ts
  src/modules/dashboard/sagas/actions/mintTokens.ts
  src/modules/dashboard/sagas/actions/moveFunds.ts
  src/modules/dashboard/sagas/actions/payment.ts
  src/modules/dashboard/sagas/actions/unlockToken.ts
  src/modules/dashboard/sagas/actions/versionUpgrade.ts
  src/modules/dashboard/sagas/colonyCreate.ts
  src/modules/dashboard/sagas/motions/createEditDomainMotion.ts
  src/modules/dashboard/sagas/motions/editColonyMotion.ts
  src/modules/dashboard/sagas/motions/managePermissionsMotion.ts
  src/modules/dashboard/sagas/motions/manageReputationMotion.ts
  src/modules/dashboard/sagas/motions/moveFundsMotion.ts
  src/modules/dashboard/sagas/motions/paymentMotion.ts
  src/modules/dashboard/sagas/motions/rootMotion.ts
  src/modules/dashboard/sagas/motions/stakeMotion.ts
  src/modules/dashboard/sagas/utils/index.ts
  src/modules/dashboard/sagas/utils/ipfsUploadAnnotation.ts
  src/modules/dashboard/sagas/utils/ipfsUploadWithFallback.ts
  src/modules/dashboard/sagas/whitelist/manageVerifiedRecipients.ts
  src/modules/users/sagas/user.ts
  src/utils/colonyActions.ts
  src/utils/events/index.ts
  src/utils/hooks/useUserAvatarImageFromIPFS.ts
Labels: feature

#3906 Fix copy address label tooltip positioning
  src/modules/core/components/Popover/Tooltip.tsx
Labels: bug

#3757 Display batch error
  src/modules/dashboard/components/ExpenditurePage/Batch/Batch.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploader.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploaderItem.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.css
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/index.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/PreviewDialog.css
  src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/PreviewDialog.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/hooks.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/types.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/utils.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
Labels: feature

#3728 Add batch payment
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialog.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/Batch.css
  src/modules/dashboard/components/ExpenditurePage/Batch/Batch.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/Batch.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploader.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploaderItem.css
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploaderItem.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/CSVUploaderItem.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/CSVUploader/index.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/DownloadTemplate/DownloadTemplate.css
  src/modules/dashboard/components/ExpenditurePage/Batch/DownloadTemplate/DownloadTemplate.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/DownloadTemplate/DownloadTemplate.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/DownloadTemplate/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/DownloadTemplate/index.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.css
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/LockedBatch.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/LockedBatch/index.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/PreviewDialog.css
  src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/PreviewDialog.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/PreviewDialog.tsx
  src/modules/dashboard/components/ExpenditurePage/Batch/PreviewDialog/index.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/hooks.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/index.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/types.ts
  src/modules/dashboard/components/ExpenditurePage/Batch/utils.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/ClaimTag/ClaimTag.css
  src/modules/dashboard/components/ExpenditurePage/Payments/LockedPayments.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/LockedStages.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
  src/modules/pages/components/ExpenditurePage/types.ts
  src/modules/pages/components/ExpenditurePage/utils.ts
Labels: feature

#3892 Refactor: Move DefaultMotion content into separate component
  src/modules/dashboard/components/ActionsPage/ActionPageMotionContent/ActionPageMotionContent.css
  src/modules/dashboard/components/ActionsPage/ActionPageMotionContent/ActionPageMotionContent.css.d.ts
  src/modules/dashboard/components/ActionsPage/ActionPageMotionContent/ActionPageMotionContent.tsx
  src/modules/dashboard/components/ActionsPage/ActionPageMotionContent/index.ts
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
Labels: feature

#3919 Add V2 IPFS metadata support for decisions
  package-lock.json
  package.json
  src/data/resolvers/colony.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionPageDecisionWithIPFS/ActionPageDecisionWithIPFS.tsx
  src/modules/dashboard/sagas/motions/createDecisionMotion.ts
Labels: feature

#3824 Add a new modal after making an edit
  src/img/icons/arrow-right.svg
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeHeader/ChangeHeader.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeHeader/ChangeHeader.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeHeader/ChangeHeader.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeHeader/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeItem/ChangeItem.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeItem/ChangeItem.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeItem/ChangeItem.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangeItem/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangedMultiple.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangedMultiple.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/ChangedMultiple.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedMultiple/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedValues/ChangedValues.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedValues/ChangedValues.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChangedValues/ChangedValues.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChnagedRecipients/ChangedRecipients.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChnagedRecipients/ChangedRecipients.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChnagedRecipients/ChangedRecipients.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/ChnagedRecipients/index.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialog.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialogForm.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialogForm.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/EditExpenditureDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewDelay/NewDelay.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewDelay/NewDelay.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewDelay/NewDelay.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewRecipient/NewRecipient.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewRecipient/NewRecipient.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewRecipient/NewRecipient.tsx
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewValue/NewValue.css
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewValue/NewValue.css.d.ts
  src/modules/dashboard/components/Dialogs/EditExpenditureDialog/NewValue/NewValue.tsx
  src/modules/externalUrls.ts
  src/modules/pages/components/ExpenditurePage/utils.ts
Labels: feature

#3902 Add loading spinner to contract interaction's ABI fetching and parsing
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/ContractInteractionSection.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransactionTypesSection.css.d.ts
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/TransactionTypesSection/TransferNFTSection.tsx
Labels: feature
