Repository JoinColony/colonyDapp, pull requests merged in 2022-08, with the labels that each got.

#3586 Add Control Safe Dialog's Transfer NFT type variation (UI only)
  src/img/icons.json
  src/img/icons/nft-icon.svg
  src/modules/core/components/SingleUserPicker/SingleNFTPicker.tsx
  src/modules/core/components/SingleUserPicker/index.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/GnosisNFTTransfer.css
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/GnosisNFTTransfer.css.d.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/GnosisNFTTransfer.tsx
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/TransactionTypesSection/index.ts
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/index.ts
Labels: feature

#3698 Add missing support for V2 metadata in colonyActions
  src/utils/colonyActions.ts
  src/utils/events/index.ts
Labels: bug

#3653 Feat: Create new component for the 3 dots button
  src/modules/core/components/Button/ThreeDotsButton.css
  src/modules/core/components/Button/ThreeDotsButton.css.d.ts
  src/modules/core/components/Button/ThreeDotsButton.tsx
  src/modules/core/components/Button/index.ts
  src/modules/core/components/Comment/Actions/CommentActions.css.d.ts
  src/modules/core/components/Comment/Actions/CommentActions.tsx
  src/modules/core/components/MembersList/Actions/MemberActions.css
  src/modules/core/components/MembersList/Actions/MemberActions.css.d.ts
  src/modules/core/components/MembersList/Actions/MemberActions.tsx
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.tsx
Labels: feature, good-first-issue

#3517 Add escrow funds
  src/modules/dashboard/components/Dialogs/DeleteDraftDialog/DeleteDraftDialog.tsx
  src/modules/dashboard/components/Dialogs/EscrowFundsDialog/EscrowFundsDialog.css
  src/modules/dashboard/components/Dialogs/EscrowFundsDialog/EscrowFundsDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/EscrowFundsDialog/EscrowFundsDialog.tsx
  src/modules/dashboard/components/Dialogs/EscrowFundsDialog/EscrowFundsDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EscrowFundsDialog/index.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3702 Update colonymetadata destructuring
  src/data/generated.ts
  src/data/graphql/typeDefs.ts
  src/i18n/en-actions.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/hooks/useColonyMetadataChecks.ts
  src/utils/colonyActions.ts
Labels: bug

#3654 Add switch component to select "equal" or "unequal" split
  src/modules/dashboard/components/Dialogs/StakeExpenditureDialog/StakeExpenditureDialog.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/BalanceSelect.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/LockedExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/Split.css
  src/modules/dashboard/components/ExpenditurePage/Split/Split.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Split/Split.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/types.ts
Labels: feature

#3676 Add slider
  src/modules/core/components/Slider/Slider.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/Split.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.css
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/index.ts
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3667 Add "Linked assets" section to home sidebar
  src/data/generated.ts
  src/data/graphql/fragments.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colony.ts
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHome/ColonySafes/ColonySafes.css
  src/modules/dashboard/components/ColonyHome/ColonySafes/ColonySafes.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonySafes/ColonySafes.tsx
  src/modules/dashboard/components/ColonyHome/ColonySafes/index.ts
  src/modules/dashboard/sagas/actions/addExistingSafe.ts
Labels: feature

#3724 Correct merge: `TransactionTypes.TRANSFER_NFT`
  src/modules/dashboard/components/Dialogs/GnosisControlSafeDialog/GnosisControlSafeForm.tsx
Labels: bug

#3618 add cancel expenditure dialog
  src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureDialog.css
  src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureDialog.tsx
  src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/CancelExpenditureForm.tsx
  src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/index.ts
  src/modules/dashboard/components/Dialogs/CancelExpenditureDialog/types.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.css
  src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/LinkedMotions/LinkedMotions.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StageItem.css
  src/modules/dashboard/components/ExpenditurePage/Stages/StageItem.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StageItem.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/index.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3705 Add permissions to gnosis dialogs
  src/modules/dashboard/components/Dialogs/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageGnosisSafeDialog/ManageGnosisSafeDialog.tsx
Labels: feature

#3717 Add decisions page UI
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.css
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.css.d.ts
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.tsx
  src/modules/dashboard/components/ColonyDecisions/constants.ts
  src/modules/dashboard/components/ColonyDecisions/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHome/ColonyNavigation/ColonyNavigation.tsx
  src/modules/dashboard/components/ColonyNewDecision/ColonyNewDecision.tsx
  src/modules/dashboard/components/ColonyNewDecision/index.ts
  src/modules/dashboard/components/Dialogs/NewDecisionDialog/NewDecisionDialog.tsx
  src/modules/dashboard/components/Dialogs/NewDecisionDialog/index.ts
  src/routes/Routes.tsx
  src/routes/routeConstants.ts
  src/utils/hooks/useTitle.ts
Labels: feature

#3527 add ability to claim expenditure
  src/modules/dashboard/components/Dialogs/EscrowFundsDialog/EscrowFundsDialog.tsx
  src/modules/dashboard/components/Dialogs/EscrowFundsDialog/EscrowFundsDialogForm.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/ClaimTag/ClaimTag.css
  src/modules/dashboard/components/ExpenditurePage/Payments/ClaimTag/ClaimTag.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/ClaimTag/ClaimTag.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/ClaimTag/index.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/CollapseExpandButtons.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/LockedPayments.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.css
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/types.d.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient/LockedRecipient.css
  src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient/LockedRecipient.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient/LockedRecipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.css
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/ClaimFunds.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/ClaimFunds/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/constants.ts
  src/modules/dashboard/components/ExpenditurePage/TimeRelativeShort/TimeRelativeShort.tsx
  src/modules/dashboard/components/ExpenditurePage/TimeRelativeShort/index.ts
  src/modules/dashboard/components/ExpenditurePage/hooks.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.css
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/types.ts
  src/modules/pages/components/ExpenditurePage/utils.ts
Labels: feature

#3727 COLONY_EXTENSION_DETAILS_ROUTE Handle invalid extension Id
  src/data/staticData/helpers.ts
  src/data/staticData/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyHome.tsx
  src/modules/dashboard/components/Extensions/Extensions.tsx
  src/routes/Routes.tsx
Labels: bug

#3694 Add unequal split
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/types.d.ts
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.css
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Split/SplitUnequal/SplitUnequal.tsx
  src/modules/dashboard/components/ExpenditurePage/Split/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
Labels: feature

#3732 Add decisions list UI with filtering, sorting & pagination
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ColonyDecisions/ColonyDecisions.tsx
  src/types/colonyActions.ts
  src/utils/colonyMotions.ts
Labels: feature

#3743 Fix incorrect spelling in ManageFundsDialog
  src/modules/dashboard/components/Dialogs/ManageFundsDialog/ManageFundsDialog.tsx
Labels: bug

#3736 Add remove safe action page
  scripts/provision_submodules.sh
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colonyActions.ts
  src/i18n/en-actions.ts
  src/i18n/en-events.ts
  src/modules/constants.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetSafe/DetailsWidgetSafe.css
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetSafe/DetailsWidgetSafe.css.d.ts
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetSafe/DetailsWidgetSafe.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetSafe/index.ts
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeed.tsx
  src/modules/dashboard/hooks/index.ts
  src/modules/dashboard/hooks/useColonyMetadataChecks.ts
  src/modules/dashboard/hooks/useExtendedColonyActionType.ts
  src/modules/dashboard/hooks/useReputationEarned.ts
  src/types/colonyActions.ts
  src/utils/colonyActions.ts
  src/utils/events/index.ts
Labels: feature

#3746 Fix 99% staking bug
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/Dialogs/RaiseObjectionDialog/RaiseObjectionDialog.tsx
Labels: bug

#3725 Add Decision Preview Page
  src/i18n/en-actions.ts
  src/i18n/en.json
  src/img/icons.json
  src/img/icons/emoji-decisions.svg
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.css.d.ts
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.css
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.css.d.ts
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.tsx
  src/modules/dashboard/components/DecisionPreview/index.ts
  src/routes/Routes.tsx
  src/routes/routeConstants.ts
  src/types/colonyActions.ts
  src/utils/hooks/useTitle.ts
Labels: feature

#3758 Add initial setup for safe core SDK transactions
  package-lock.json
  package.json
  src/modules/constants.ts
  src/modules/dashboard/sagas/utils/getSafeCoreSDK.ts
Labels: feature

#3703 Staged payment
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/LockedPayments.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/Payments.tsx
  src/modules/dashboard/components/ExpenditurePage/Payments/types.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/LockedRecipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Staged/Milestone/Milestone.css
  src/modules/dashboard/components/ExpenditurePage/Staged/Milestone/Milestone.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/Milestone/Milestone.tsx
  src/modules/dashboard/components/ExpenditurePage/Staged/Milestone/index.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/Staged.css
  src/modules/dashboard/components/ExpenditurePage/Staged/Staged.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/Staged.tsx
  src/modules/dashboard/components/ExpenditurePage/Staged/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/index.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/types.ts
Labels: feature

#3759 Replace `ITEMS_PER_SECTION` value & members clean up
  src/modules/dashboard/components/ColonyHome/ColonyMembers/MembersSubsection.tsx
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/Members/MembersSection.tsx
Labels: maintenance

#3714 Staged payment locked
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/LockedExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.css
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
  src/modules/pages/components/ExpenditurePage/index.tsx
Labels: feature

#3740 Add release milestone
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.css
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/LockedStaged/LockedStaged.tsx
  src/modules/dashboard/components/ExpenditurePage/Staged/constants.ts
  src/modules/dashboard/components/ExpenditurePage/Staged/types.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/Stages.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureForm.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
Labels: feature

#3762 Make decision preview route wallet restricted
  src/routes/Routes.tsx
Labels: feature

#3768 Add rounding to staking amount logic in transform function
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/Dialogs/RaiseObjectionDialog/RaiseObjectionDialog.tsx
Labels: bug

#3764 Fix not being able to remove safes with equal addresses
  src/modules/core/components/Fields/Checkbox/Checkbox.tsx
  src/modules/dashboard/components/ColonyHome/ColonySafes/ColonySafes.tsx
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/RemoveSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/RemoveSafeDialogForm.tsx
  src/modules/dashboard/components/Dialogs/RemoveSafeDialog/SafeListItem.tsx
  src/modules/dashboard/sagas/actions/manageExistingSafes.ts
  src/redux/types/actions/colonyActions.ts
Labels: bug

#3775 Add tooltip to force action toggles
  src/i18n/en.json
  src/modules/core/components/Fields/ForceToggle/ForceToggle.css
  src/modules/core/components/Fields/ForceToggle/ForceToggle.css.d.ts
  src/modules/core/components/Fields/ForceToggle/ForceToggle.tsx
  src/modules/core/components/Fields/ForceToggle/index.ts
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.tsx
  src/modules/dashboard/components/Dialogs/CreateDomainDialog/CreateDomainDialogForm.tsx
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EditDomainDialog/EditDomainDialogForm.tsx
  src/modules/dashboard/components/Dialogs/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.tsx
  src/modules/dashboard/components/Dialogs/PermissionManagementDialog/PermissionManagementForm.tsx
  src/modules/dashboard/components/Dialogs/TokenMintDialog/TokenMintForm.tsx
  src/modules/dashboard/components/Dialogs/TransferFundsDialog/TransferFundsDialogForm.tsx
  src/modules/dashboard/components/Dialogs/UnlockTokenDialog/UnlockTokenForm.tsx
Labels: maintenance

#3776 Add activate button when part of tokens is activated
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.css.d.ts
  src/modules/dashboard/components/ActionsPage/StakingWidget/StakingWidget.tsx
  src/modules/dashboard/components/Dialogs/RaiseObjectionDialog/RaiseObjectionDialogForm.tsx
Labels: bug
