Repository JoinColony/colonyDapp, pull requests merged in 2022-03, with the labels that each got.

#3211 Improve Icon's alignment
  src/modules/core/components/DecisionHub/DecisionOption.css
  src/modules/core/components/Fields/InputLabel/InputLabel.css
  src/modules/core/components/Fields/InputLabel/InputLabel.css.d.ts
  src/modules/core/components/Fields/InputLabel/InputLabel.tsx
  src/modules/core/components/Fields/InputLabel/__tests__/__snapshots__/InputLabel.test.tsx.snap
  src/modules/core/components/Fields/Radio/CustomRadio.css
  src/modules/core/components/Fields/Radio/__tests__/__snapshots__/Radio.test.tsx.snap
  src/modules/core/components/Fields/Select/__tests__/__snapshots__/Select.test.tsx.snap
  src/modules/core/components/Fields/Toggle/Toggle.css
  src/modules/core/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
  src/modules/core/components/Icon/Icon.css
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.css
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.css
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/TotalStakeWidget/TotalStakeWidget.css
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteDetails.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.css
  src/modules/dashboard/components/CreateColonyWizard/StepColonyName.css
  src/modules/users/components/GasStation/TransactionCard/TransactionStatus.css
Labels: bug

#3219 Consistent font sizing and alignment in UserNavigation
  src/modules/core/components/MemberReputation/MemberReputation.css
  src/modules/core/components/MemberReputation/MemberReputation.css.d.ts
  src/modules/core/components/MemberReputation/MemberReputation.tsx
  src/modules/core/components/Numeral/Numeral.css
  src/modules/core/components/Numeral/Numeral.css.d.ts
  src/modules/core/components/Numeral/Numeral.tsx
  src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.css
  src/modules/pages/components/RouteLayouts/UserNavigation.css
  src/modules/pages/components/RouteLayouts/UserNavigation.css.d.ts
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.css
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.css.d.ts
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.tsx
Labels: bug

#3222 Update cypress selectors & optimise existing tests
  cypress.json
  cypress/.eslintrc.js
  cypress/e2e/1-logins.js
  cypress/e2e/2-actions.js
  cypress/support/commands.js
  src/modules/core/components/Avatar/Avatar.tsx
  src/modules/core/components/Comment/Comment.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.tsx
  src/modules/pages/components/RouteLayouts/HistoryNavigation.tsx
Labels: feature

#3226 Change text for no reputation in colony message
  src/modules/dashboard/components/NotEnoughReputation/NotEnoughReputation.css
  src/modules/dashboard/components/NotEnoughReputation/NotEnoughReputation.css.d.ts
  src/modules/dashboard/components/NotEnoughReputation/NotEnoughReputation.tsx
  src/modules/externalUrls.ts
Labels: maintenance

#3233 Add LoadingTemplate delayed/failed updates
  src/img/naked-mole-without-bg.svg
  src/modules/pages/components/LoadingTemplate/LoadingTemplate.css
  src/modules/pages/components/LoadingTemplate/LoadingTemplate.css.d.ts
  src/modules/pages/components/LoadingTemplate/LoadingTemplate.tsx
Labels: feature

#3167 Add testing framework skeleton & several initial tests
  .gitignore
  cypress.json
  cypress/.eslintrc.js
  cypress/e2e/1-logins.js
  cypress/e2e/2-actions.js
  cypress/fixtures/colony.json
  cypress/support/commands.js
  cypress/support/generate.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/modules/core/components/Avatar/Avatar.tsx
  src/modules/core/components/Comment/Comment.tsx
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/core/components/Fields/Select/__tests__/__snapshots__/Select.test.tsx.snap
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.tsx
  src/modules/pages/components/RouteLayouts/HistoryNavigation.tsx
Labels: feature

#3224 Add test for comments
  cypress/e2e/2-actions.js
  cypress/e2e/4-comments.js
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/core/components/Comment/Actions/CommentActions.tsx
  src/modules/core/components/Comment/Actions/CommentActionsPopover.tsx
  src/modules/core/components/Comment/Dialogs/BanComment/BanComment.tsx
  src/modules/core/components/Comment/Dialogs/DeleteComment/DeleteComment.tsx
  src/modules/core/components/Comment/Input/CommentInput.tsx
  src/modules/core/components/Fields/Textarea/TextareaAutoresize.tsx
  src/modules/users/components/AvatarDropdown/AvatarDropdownPopover.tsx
Labels: feature

#3218 Whitelisted modal content
  src/img/icons/search.svg
  src/modules/core/components/Fields/Checkbox/Checkbox.css
  src/modules/core/components/Fields/Checkbox/Checkbox.tsx
  src/modules/core/components/UserCheckbox/UserCheckbox.css
  src/modules/core/components/UserCheckbox/UserCheckbox.css.d.ts
  src/modules/core/components/UserCheckbox/UserCheckbox.tsx
  src/modules/core/components/UserCheckbox/index.ts
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialogForm.css
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialogForm.css.d.ts
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialogForm.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/NoWhitelistedAddressesState/NoWhitelistedAddressesState.css
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/NoWhitelistedAddressesState/NoWhitelistedAddressesState.css.d.ts
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/NoWhitelistedAddressesState/NoWhitelistedAddressesState.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/NoWhitelistedAddressesState/index.ts
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/WhitelistedAddresses/WhitelistedAddresses.css
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/WhitelistedAddresses/WhitelistedAddresses.css.d.ts
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/WhitelistedAddresses/WhitelistedAddresses.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/WhitelistedAddresses/index.ts
Labels: feature

#3227 Add test for extension management
  cypress/e2e/5-extensions.js
  src/modules/core/components/Dialog/ConfirmDialog.tsx
  src/modules/core/components/Fields/Radio/CustomRadio.tsx
  src/modules/core/components/Fields/RadioGroup/CustomRadioGroup.tsx
  src/modules/dashboard/components/ColonyHome/ColonyNavigation/ColonyNavigation.tsx
  src/modules/dashboard/components/ColonyHome/ColonyNavigation/NavItem.tsx
  src/modules/dashboard/components/Extensions/ExtensionActionButton.tsx
  src/modules/dashboard/components/Extensions/ExtensionCard.tsx
  src/modules/dashboard/components/Extensions/ExtensionDetails.tsx
  src/modules/dashboard/components/Extensions/ExtensionSetup.tsx
  src/modules/dashboard/components/Extensions/ExtensionStatus.tsx
  src/modules/dashboard/components/Extensions/ExtensionUninstallConfirmDialog/ExtensionUninstallConfirmDialog.tsx
  src/modules/dashboard/components/Extensions/Extensions.tsx
  src/modules/dashboard/components/Whitelist/ColonyPolicySelector/ColonyPolicySelector.tsx
  src/modules/users/components/GasStation/GasStationHeader/GasStationHeader.tsx
Labels: feature

#3239 Fix agreement IPFS upload logic & disabled primary button css
  src/data/staticData/extensionData.tsx
  src/modules/core/components/Button/Button.css
  src/modules/dashboard/sagas/whitelist/extensionEnable.ts
Labels: bug

#3220 Add address tab in ManageWhitelist modal
  src/modules/core/components/CSVUploader/CSVUploader.tsx
  src/modules/core/components/CSVUploader/CSVUploaderItem.css
  src/modules/core/components/Fields/InputStatus/InputStatus.tsx
  src/modules/core/components/UploadAddresses/DownloadTemplate.css
  src/modules/core/components/UploadAddresses/DownloadTemplate.css.d.ts
  src/modules/core/components/UploadAddresses/DownloadTemplate.tsx
  src/modules/core/components/UploadAddresses/UploadAddresses.css
  src/modules/core/components/UploadAddresses/UploadAddresses.css.d.ts
  src/modules/core/components/UploadAddresses/UploadAddresses.tsx
  src/modules/core/components/UploadAddresses/index.ts
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialogForm.tsx
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/UploadAddressesWidget.tsx
  src/modules/dashboard/components/Whitelist/UploadAddressesWidget/index.ts
  src/modules/dashboard/components/Whitelist/Whitelist.tsx
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/UploadAddressesExtensionWidget.css
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/UploadAddressesExtensionWidget.css.d.ts
  src/modules/dashboard/components/Whitelist/WhitelistAddresses/UploadAddressesExtensionWidget.tsx
  src/utils/whitelistValidation.ts
Labels: feature

#3254 Prevent extra margin in DefaultMotion tags
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
Labels: bug

#3248 Whitelist UI dialog styles fix
  src/modules/core/components/Dialog/Dialog.css
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialogForm.css
Labels: bug

#3022 Add `Vesting` feature
  .env.example
  package-lock.json
  package.json
  src/data/generated.ts
  src/data/graphql/queries/vesting.graphql
  src/data/graphql/typeDefs/vesting.ts
  src/data/index.ts
  src/data/resolvers/vesting.ts
  src/i18n/en.json
  src/modules/core/sagas/transactions/estimateGasCost.ts
  src/modules/core/sagas/transactions/sendTransaction.ts
  src/modules/dashboard/components/ColonyHome/ColonyNavigation/ColonyNavigation.tsx
  src/modules/dashboard/components/CreateUserWizard/StepConfirmTransaction.tsx
  src/modules/dashboard/components/Vesting/ClaimTokensPage.tsx
  src/modules/dashboard/components/Vesting/UnwrapTokensPage.tsx
  src/modules/dashboard/components/Vesting/Vesting.css
  src/modules/dashboard/components/Vesting/Vesting.css.d.ts
  src/modules/dashboard/components/Vesting/VestingPageLayout.tsx
  src/modules/dashboard/components/Vesting/index.ts
  src/modules/dashboard/sagas/index.ts
  src/modules/dashboard/sagas/vesting/claimAllocation.ts
  src/modules/dashboard/sagas/vesting/index.ts
  src/modules/dashboard/sagas/vesting/unwrapToken.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/index.ts
  src/redux/types/actions/vesting.ts
  src/routes/Routes.tsx
  src/routes/WalletRequiredRoute.tsx
  src/routes/routeConstants.ts
  src/types/index.ts
Labels: feature

#3273 Fix `canColonyMintNativeToken` resover to work with all tokens
  src/data/resolvers/colony.ts
Labels: bug

#3277 Add Standard Number display formatting to StakesListItem
  src/modules/users/components/TokenActivation/StakesTab/StakesListItem.tsx
Labels: feature

#3247 Add colony related tests
  cypress.json
  cypress/e2e/2-createColony.js
  cypress/e2e/6-updateColony.js
  cypress/fixtures/images/jaya-the-beast.png
  cypress/support/commands.js
  package-lock.json
  package.json
  src/modules/core/components/FileUpload/FileUpload.tsx
  src/modules/core/components/FileUpload/__tests__/__snapshots__/FileUpload.test.tsx.snap
  src/modules/core/components/IndexModal/IndexModal.tsx
  src/modules/core/components/IndexModal/IndexModalItem.tsx
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/dashboard/components/ColonyFundingMenu/ColonyFundingMenu.tsx
  src/modules/dashboard/components/ColonyHome/ColonyFunding/ColonyFunding.tsx
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.tsx
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscriptionInfoPopover.tsx
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/ColonyTotalFunds/ColonyTotalFunds.tsx
  src/modules/dashboard/components/CreateColonyWizard/StepSelectToken.tsx
  src/modules/dashboard/components/CreateColonyWizard/StepTokenChoice.tsx
  src/modules/dashboard/components/Dialogs/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/Dialogs/ColonyActionsDialog/ColonyActionsDialog.tsx
  src/modules/dashboard/components/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
  src/modules/dashboard/components/SubscribedColoniesList/SubscribedColoniesList.tsx
  src/modules/pages/components/LandingPage/LandingPage.tsx
Labels: feature

#3243 Add tests for colony actions
  cypress/e2e/3-actions.js
  cypress/support/commands.js
  src/modules/core/components/DomainDropdown/DomainDropdown.tsx
  src/modules/core/components/DomainDropdown/DomainDropdownItem.tsx
  src/modules/core/components/Fields/Input/Input.tsx
  src/modules/core/components/Fields/Input/InputComponent.tsx
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/core/components/Fields/Select/SelectListBox.tsx
  src/modules/core/components/Fields/Select/__tests__/Select.test.tsx
  src/modules/core/components/Fields/Select/__tests__/__snapshots__/Select.test.tsx.snap
  src/modules/core/components/Fields/SelectOption/SelectOption.tsx
  src/modules/core/components/Fields/Textarea/Textarea.tsx
  src/modules/core/components/SingleUserPicker/ItemDefault.tsx
  src/modules/core/components/SingleUserPicker/SingleUserPicker.tsx
  src/modules/dashboard/components/ColonyHome/ColonyDomainSelector/ColonyDomainSelector.tsx
  src/modules/dashboard/components/ColonyHome/ColonyFunding/TokenItem.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.tsx
  src/modules/dashboard/components/Dialogs/ColonyActionsDialog/ColonyActionsDialog.tsx
  src/modules/dashboard/components/Dialogs/CreateDomainDialog/CreateDomainDialogForm.tsx
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EditDomainDialog/EditDomainDialogForm.tsx
  src/modules/dashboard/components/Dialogs/ExpendituresDialog/ExpendituresDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageDomainsDialog/ManageDomainsDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageFundsDialog/ManageFundsDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageReputationDialog/ManageReputationDialog.tsx
  src/modules/dashboard/components/Dialogs/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: feature

#3260 Add tests for colony actions (REMIX)
  cypress/e2e/3-actions.js
  src/modules/core/components/Fields/Checkbox/Checkbox.tsx
  src/modules/core/components/IconTooltip/IconTooltip.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/RecoveryAction.tsx
  src/modules/dashboard/components/ActionsPage/ApproveExitWidget/ApproveExitWidget.tsx
  src/modules/dashboard/components/ActionsPage/InputStorageWidget/InputStorageWidget.tsx
  src/modules/dashboard/components/ActionsPage/MultisigWidget/MultisigWidget.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/components/ColonyHome/ColonyFunding/TokenItem.tsx
  src/modules/dashboard/components/Dialogs/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageFundsDialog/ManageFundsDialog.tsx
  src/modules/dashboard/components/Dialogs/PermissionManagementDialog/PermissionManagementCheckbox.tsx
  src/modules/dashboard/components/Dialogs/PermissionManagementDialog/PermissionManagementDialog.tsx
  src/modules/dashboard/components/Dialogs/PermissionManagementDialog/PermissionManagementForm.tsx
  src/modules/dashboard/components/Dialogs/RecoveryModeDialog/RecoveryModeDialogForm.tsx
  src/modules/dashboard/components/Dialogs/UnlockTokenDialog/UnlockTokenForm.tsx
Labels: feature
