Repository JoinColony/colonyDapp, pull requests merged in 2022-11, with the labels that each got.

#4052 Don't abbreviate numbers less than 7 digits
  src/modules/core/components/Numeral/Numeral.tsx
  src/utils/numbers/numberFormatter.ts
Labels: feature

#3855 Add start stream modal
  src/modules/dashboard/components/Dialogs/StartStreamDialog/FundingSource/FundingSource.css
  src/modules/dashboard/components/Dialogs/StartStreamDialog/FundingSource/FundingSource.css.d.ts
  src/modules/dashboard/components/Dialogs/StartStreamDialog/FundingSource/FundingSource.tsx
  src/modules/dashboard/components/Dialogs/StartStreamDialog/FundingSource/index.ts
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StartStreamDialog.css
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StartStreamDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StartStreamDialog.tsx
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StartStreamDialogForm.tsx
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StreamingDetails/EndDate.tsx
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StreamingDetails/FormattedDateAndTime.tsx
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StreamingDetails/StreamingDetails.css
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StreamingDetails/StreamingDetails.css.d.ts
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StreamingDetails/StreamingDetails.tsx
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StreamingDetails/index.ts
  src/modules/dashboard/components/Dialogs/StartStreamDialog/StreamingDetails/utils.ts
  src/modules/dashboard/components/Dialogs/StartStreamDialog/index.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/FormStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Streaming/RateItem/RateItem.css
Labels: feature

#4018 Implement safe transaction motion page
  package-lock.json
  package.json
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colonyActions.ts
  src/data/resolvers/motions.ts
  src/i18n/en-actions.ts
  src/i18n/en-events.ts
  src/i18n/en-motions.ts
  src/img/icons.json
  src/img/icons/ether.svg
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/core/components/Avatar/Avatar.tsx
  src/modules/dashboard/components/ActionsPage/ActionPageMotionContent/ActionPageMotionContent.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultMotion.tsx
  src/modules/dashboard/components/ActionsPage/ActionsPage.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidget.tsx
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
  src/modules/dashboard/components/ActionsPage/staticMaps.ts
  src/modules/dashboard/components/Dialogs/ColonyTokenManagementDialog/ColonyTokenManagementDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeDialog.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
  src/modules/dashboard/components/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialog.tsx
  src/modules/dashboard/sagas/actions/editColony.ts
  src/modules/dashboard/sagas/motions/finalizeMotion.ts
  src/modules/dashboard/sagas/motions/index.ts
  src/modules/dashboard/sagas/motions/initiateSafeTransactionMotion.ts
  src/redux/actionTypes.ts
  src/redux/types/actions/colonyActions.ts
  src/redux/types/actions/motion.ts
  src/types/colonyActions.ts
  src/types/colonyMotions.ts
  src/utils/colonyActions.ts
  src/utils/events/getAnnotationFromSubgraph.ts
  src/utils/events/index.ts
  src/utils/saga/effects.ts
Labels: feature

#3579 Add delay to `GasStationPopover`
  src/modules/core/components/Popover/Popover.tsx
  src/modules/users/components/GasStation/GasStationPopover.tsx
Labels: feature

#4067 Add ForceToggle to ControlSafeDialog
  src/data/resolvers/motions.ts
  src/i18n/en.json
  src/modules/core/components/Fields/index.ts
  src/modules/core/components/TokenEditDialog/TokenEditDialog.tsx
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetSafeTransaction/components/ContractSection.tsx
  src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.tsx
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/SafeTransactionPreview.tsx
  src/modules/dashboard/components/Dialogs/CreateDomainDialog/CreateDomainDialogForm.tsx
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EditColonyDetailsDialog/EditColonyDetailsDialogForm.tsx
  src/modules/dashboard/components/Dialogs/EditDomainDialog/EditDomainDialogForm.tsx
  src/modules/dashboard/components/Dialogs/NetworkContractUpgradeDialog/NetworkContractUpgradeDialogForm.tsx
  src/modules/dashboard/components/Dialogs/PermissionManagementDialog/PermissionManagementForm.tsx
  src/modules/dashboard/components/Dialogs/TokenMintDialog/TokenMintForm.tsx
  src/modules/dashboard/components/Dialogs/TransferFundsDialog/TransferFundsDialogForm.tsx
  src/modules/dashboard/components/Dialogs/UnlockTokenDialog/UnlockTokenForm.tsx
  src/utils/events/index.ts
Labels: maintenance, feature

#4065 Add improvements and bug fixes to Safe Control
  src/data/resolvers/motions.ts
  src/i18n/en.json
  src/modules/dashboard/components/ActionsPage/DetailsWidget/DetailsWidgetSafeTransaction/components/ContractSection.tsx
  src/utils/events/index.ts
Labels: bug, maintenance

#4068 Rename expenditure option to "Multiple"
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/pages/components/ExpenditurePage/types.ts
Labels: bug

#4066 change location of the "Another token" button
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.css
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Recipient/Recipient.tsx
Labels: bug

#3888 Add active stream with funds to claim
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/FormStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/LockedStages.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.css
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/StreamingStagesLocked.tsx
  src/modules/dashboard/components/ExpenditurePage/Stages/StreamingStages/StreamingStagesLocked/hooks.ts
  src/modules/dashboard/components/ExpenditurePage/Stages/utils.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/LockedSidebar.tsx
Labels: feature

#4064 Add User Agent Data Types for Typescript
  package-lock.json
  package.json
  src/modules/core/components/RichTextEditor/Toolbar.tsx
  tsconfig.base.json
  tsconfig.json
Labels: bug

#4074 Remove scrollbar from expenditure dropdown
  src/modules/core/components/Fields/Select/Select.tsx
  src/modules/core/components/Fields/Select/SelectHorizontal.tsx
  src/modules/core/components/UserPickerWithSearch/Dropdown.css
  src/modules/core/components/UserPickerWithSearch/Dropdown.css.d.ts
  src/modules/core/components/UserPickerWithSearch/Dropdown.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
Labels: bug

#3819 Fix: typos
  Readme.md
Labels: bug

#4075 Add more misc fixes and improvements to Safe Control
  package-lock.json
  package.json
  src/data/resolvers/motions.ts
  src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.tsx
  src/modules/dashboard/hooks/useFetchSafeTransactionData.ts
  src/modules/dashboard/sagas/motions/manageReputationMotion.ts
  src/modules/dashboard/transformers/transformers.ts
  src/utils/events/index.ts
  src/utils/safes/getContractUsefulMethods.ts
Labels: bug, maintenance

#4079 Improve instructions in 2nd step of adding a safe
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.css
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.css.d.ts
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/AddExistingSafeDialogForm.tsx
  src/modules/dashboard/components/Dialogs/AddExistingSafeDialog/ConnectSafe.tsx
  src/modules/externalUrls.ts
Labels: feature
