Repository JoinColony/colonyDapp, pull requests merged in 2022-05, with the labels that each got.

#3352 Improve border radius on avatar hover
  src/modules/core/components/ActionsList/ActionsListItem.css
Labels: bug

#3261 Testing token activation and deactivation & claiming stakes
  cypress/e2e/2-createColony.js
  cypress/e2e/3-actions.js
  cypress/e2e/4-comments.js
  cypress/e2e/5-extensions.js
  cypress/e2e/6-updateColony.js
  cypress/e2e/7-userSettings.js
  cypress/e2e/8-motions.js
  cypress/e2e/9-tokenActivation.js
  cypress/support/commands.js
  src/modules/dashboard/components/ActionsPage/FinalizeMotionAndClaimWidget/FinalizeMotionAndClaimWidget.tsx
  src/modules/pages/components/RouteLayouts/UserNavigation.tsx
  src/modules/users/components/TokenActivation/StakesTab/ClaimAllButton.tsx
  src/modules/users/components/TokenActivation/StakesTab/StakesListItem.tsx
  src/modules/users/components/TokenActivation/StakesTab/StakesTab.tsx
  src/modules/users/components/TokenActivation/TokenActivationContent/TokenActivationContent.tsx
  src/modules/users/components/TokenActivation/TokensTab/ChangeTokenStateForm.tsx
  src/modules/users/components/TokenActivation/TokensTab/TokensTab.tsx
  src/modules/users/components/UserTokenActivationButton/UserTokenActivationButton.tsx
Labels: feature

#3354 Improve alignment of icons in the gas station
  src/modules/core/components/DomainDropdown/DomainDropdownItem.css
  src/modules/dashboard/components/ColonyHome/ColonyDomainSelector/CreateDomainButton.css
  src/modules/users/components/GasStation/MessageCard/MessageCardStatus.tsx
  src/modules/users/components/GasStation/TransactionCard/GroupedTransactionCard.css
  src/modules/users/components/GasStation/TransactionCard/TransactionStatus.css
  src/modules/users/components/GasStation/TransactionCard/TransactionStatus.css.d.ts
  src/modules/users/components/GasStation/TransactionCard/TransactionStatus.tsx
Labels: bug

#3355 Added IconTooltip sizing + copy update
  src/modules/core/components/MembersList/MembersListItem.tsx
Labels: bug

#3346 Add action title for "New whitelisted addresses/address"
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colonyActions.ts
  src/i18n/en-actions.ts
  src/i18n/en-events.ts
  src/modules/core/components/ActionsList/ActionsListItem.tsx
  src/modules/dashboard/components/ActionsPage/ActionsComponents/DefaultAction.tsx
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageEvent/ActionsPageEvent.tsx
  src/modules/dashboard/hooks/useColonyMetadataChecks.ts
  src/utils/colonyActions.ts
  src/utils/events/index.ts
Labels: feature

#3357 Display important copy to warn about Award Reputation
  src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.css
  src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.css.d.ts
  src/modules/dashboard/components/Dialogs/AwardAndSmiteDialogs/ManageReputationDialogForm/ManageReputationDialogForm.tsx
  src/modules/dashboard/components/Dialogs/ManageReputationDialog/ManageReputationDialog.tsx
  src/modules/externalUrls.ts
Labels: feature

#3363 Plug network fees into CreatePaymentDialog validation
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
Labels: bug

#3362 Add validation for toDomain value
  src/modules/dashboard/components/Dialogs/TransferFundsDialog/TransferFundsDialogForm.tsx
Labels: bug

#3323 Add incoming funds aside in home layout
  src/modules/dashboard/components/ColonyHome/ColonyHomeLayout.tsx
  src/modules/dashboard/components/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.css
  src/modules/dashboard/components/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyUnclaimedTransfers/ColonyUnclaimedTransfers.tsx
  src/modules/dashboard/components/ColonyHome/ColonyUnclaimedTransfers/index.ts
Labels: feature

#3370 Fix `ActionsListItem` decimals logic
  src/modules/core/components/ActionsList/ActionsListItem.tsx
Labels: bug

#3374 Fix CreateDomainButton icon going out of bounds
  src/modules/dashboard/components/ColonyHome/ColonyDomainSelector/CreateDomainButton.css
Labels: bug

#3310 Fix & consolidate the whole set of cypress tests
  .circleci/config.yml
  cypress.json
  cypress/e2e/2-createColony.js
  cypress/e2e/3-actions.js
  cypress/e2e/6-updateColony.js
  cypress/e2e/8-tokenActivation.js
  cypress/e2e/9-motions.js
  cypress/support/commands.js
  src/i18n/en-motions.ts
  src/modules/core/components/Fields/RadioGroup/CustomRadioGroup.tsx
  src/modules/dashboard/components/ActionsPage/VoteWidget/VoteWidget.tsx
  src/modules/dashboard/components/ColonyActions/ColonyActions.tsx
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
Labels: feature

#3389 Resolves confusing characters & warnings
  package-lock.json
  package.json
  src/modules/dashboard/components/CreateColonyWizard/StepUserName.tsx
  src/modules/dashboard/components/CreateUserWizard/StepUserName.tsx
  src/modules/dashboard/components/Dialogs/CreatePaymentDialog/CreatePaymentDialogForm.tsx
  src/modules/users/components/UserProfileEdit/UserProfileEdit.tsx
Labels: bug

#3375 Manage address book
  src/i18n/en-actions.ts
  src/i18n/en-events.ts
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/dashboard/components/ColonyHomeActions/ColonyHomeActions.tsx
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/Dialogs/AdvancedDialog/AdvancedDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageDomainsDialog/ManageDomainsDialog.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistActiveToggle.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/ManageWhitelistDialogForm.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/NoWhitelistedAddressesState/NoWhitelistedAddressesState.tsx
  src/modules/dashboard/components/Dialogs/ManageWhitelistDialog/WhitelistedAddresses/WhitelistedAddresses.tsx
Labels: maintenance

#3398 New "Join this colony" button
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonySubscription/ColonySubscription.tsx
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyTitle/ColonyTitle.tsx
Labels: feature

#3396 Display user feedback when IPFS fails to provide annotations
  src/modules/core/components/CalloutCard/CalloutCard.css
  src/modules/core/components/CalloutCard/CalloutCard.css.d.ts
  src/modules/core/components/CalloutCard/CalloutCard.md
  src/modules/core/components/CalloutCard/CalloutCard.tsx
  src/modules/core/components/CalloutCard/index.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItemWithIPFS/ActionsPageFeedItemWithIPFS.css
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItemWithIPFS/ActionsPageFeedItemWithIPFS.css.d.ts
  src/modules/dashboard/components/ActionsPageFeed/ActionsPageFeedItemWithIPFS/ActionsPageFeedItemWithIPFS.tsx
Labels: feature

#3395 Split members to contributors & watchers in the side panel - UI only
  src/modules/dashboard/components/ColonyHome/ColonyFunding/ColonyFunding.css
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/MembersSubsection.tsx
Labels: feature

#3388 Add invite to colony button
  src/modules/core/components/Button/Button.css
  src/modules/core/components/Button/Button.css.d.ts
  src/modules/core/components/Button/Button.tsx
  src/modules/core/components/Button/index.ts
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.css.d.ts
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/MembersSubsection.tsx
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/InviteLinkButton/InviteLinkButton.tsx
  src/modules/dashboard/components/InviteLinkButton/index.ts
  src/modules/dashboard/components/InviteLinkButton/styles.css
  src/modules/dashboard/components/InviteLinkButton/styles.css.d.ts
Labels: feature

#3393 Add top parameters (expenditure type, team, owner and balance) on the expenditure creation page
  src/modules/core/components/Fields/FormSection/FormSection.css
  src/modules/core/components/Fields/FormSection/FormSection.css.d.ts
  src/modules/core/components/Fields/FormSection/FormSection.tsx
  src/modules/core/components/Fields/FormSection/index.tsx
  src/modules/core/components/Fields/Select/SelectHorizontal.css
  src/modules/core/components/Fields/Select/SelectHorizontal.css.d.ts
  src/modules/core/components/Fields/Select/SelectHorizontal.tsx
  src/modules/core/components/Fields/Select/index.ts
  src/modules/core/components/Fields/index.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.css.d.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/ExpenditureSettings.tsx
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/consts.ts
  src/modules/dashboard/components/ExpenditurePage/ExpenditureSettings/index.ts
  src/modules/dashboard/components/ExpenditurePage/index.ts
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.css
  src/modules/pages/components/ExpenditurePage/ExpenditurePage.tsx
  src/modules/pages/components/ExpenditurePage/ExpenditureTemplate.css.d.ts
Labels: feature

#3400 Add contributors & watchers data
  src/data/generated.ts
  src/data/graphql/queries.graphql
  src/data/graphql/typeDefs.ts
  src/data/resolvers/colony.ts
  src/modules/core/components/MembersList/MembersList.tsx
  src/modules/core/components/MembersList/MembersListItem.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/ColonyHome/ColonyMembers/MembersSubsection.tsx
  src/modules/dashboard/components/Members/Members.tsx
  src/utils/hooks/useAvatarDisplayCounter.ts
Labels: feature

#3404 Members page contributors/watchers (UI only)
  src/modules/dashboard/components/Members/Members.tsx
  src/modules/dashboard/components/Members/MembersSection.css
  src/modules/dashboard/components/Members/MembersSection.css.d.ts
  src/modules/dashboard/components/Members/MembersSection.tsx
Labels: feature

#3394 Add "Total reputation in team" section
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.css
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.css.d.ts
  src/modules/dashboard/components/ColonyMembers/ColonyMembers.tsx
  src/modules/dashboard/components/Members/Members.css
  src/modules/dashboard/components/Members/Members.css.d.ts
  src/modules/dashboard/components/Members/Members.tsx
Labels: feature
