Repository JoinColony/colonyDapp, pull requests merged in 2023-02, with the labels that each got.

#4186 Add old colony metadata version handling to manage safe saga
  src/modules/dashboard/sagas/actions/manageExistingSafes.ts
Labels: bug

#4196 Fix New Decision dialog scrolling up on state change
  src/modules/core/components/RichTextEditor/RichTextEditor.tsx
  src/modules/dashboard/components/DecisionPreview/DecisionPreview.tsx
Labels: bug

#4198 Update version warning on Control Safe
  package-lock.json
  package.json
  src/modules/dashboard/components/Dialogs/ControlSafeDialog/ControlSafeForm.tsx
Labels: maintenance

#4163 Add incorporation modal with slides
  src/modules/core/components/Dialog/Dialog.css
  src/modules/core/components/Dialog/Dialog.css.d.ts
  src/modules/core/components/Dialog/Dialog.tsx
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/DAOIncorporationDialog.css
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/DAOIncorporationDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/DAOIncorporationDialog.tsx
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/CostPanel.tsx
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/HowPanel.tsx
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/TabPanels.css
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/TabPanels.css.d.ts
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/WhyPanel.tsx
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/TabPanels/index.ts
  src/modules/dashboard/components/Dialogs/DAOIncorporationDialog/constants.ts
Labels: feature

#4161 Add payment dialog
  src/modules/dashboard/components/Dialogs/IncorporationPaymentDialog/IncorporationPaymentDialog.css
  src/modules/dashboard/components/Dialogs/IncorporationPaymentDialog/IncorporationPaymentDialog.css.d.ts
  src/modules/dashboard/components/Dialogs/IncorporationPaymentDialog/IncorporationPaymentDialog.tsx
  src/modules/dashboard/components/Dialogs/IncorporationPaymentDialog/constants.ts
  src/modules/dashboard/components/Dialogs/IncorporationPaymentDialog/index.ts
  src/modules/dashboard/components/Incorporation/IncorporationForm/Protectors/Protectors.tsx
  src/modules/dashboard/components/Incorporation/IncorporationForm/types.ts
  src/modules/pages/components/IncorporationPage/IncorporationPage.tsx
  src/modules/pages/components/IncorporationPage/constants.ts
Labels: feature
